### ISSUE TITLE
Renovate converts Python major tilde ranges to minor tilde ranges when upgrading major version

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#10285]
When marking `~=` on a minor, for example `click~=7.1`, we're actually marking we're good with any minor version, as long as the major version is 7. This means that a package that installs our package, and requires `click~=7.2`, will be ok (no conflict).
But, when Renovate adds a path (like `8.0.1`), this means our package won't work with future versions like 8.1. So, the range is narrowed for future versions support and we lost the entire flexibility of the tilde operator here.
I'd expect the range to keep the major/minor/patch restrictions, meaning if we stuck with major only before an upgrade (`click~=7.1`), we need to keep this range condition after the upgrade (`click~=8.0` instead of `click~=8.0.1`).

Hope this clarifies the issue better..

_Originally posted by @ofir123 in https://github.com/renovatebot/renovate/discussions/10278#discussioncomment-815611_

**Comment by MaronHatoum** [comment]
I tried to reproduce this issue with: https://github.com/MaronHatoum/renovate-10285

Renovate created new[ PR](https://github.com/MaronHatoum/renovate-10285/pull/1) which contains a new update for click dependency from `~=7.1 -> ~=8.1`
![image](https://user-images.githubusercontent.com/98313426/183906847-425182b1-b7f5-40a4-b660-c1c1c3788561.png)


- I think this is expected behavior, so we can close this issue.
