### ISSUE TITLE
New filesync manager to sync files from a upstream repository

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#10404]
**What would you like Renovate to be able to do?**

We are discussing how to update a `schedule.json` file from a upstream repository in #7507, and @rarkins said:

> The ideal solution is a new filesync manager in Renovate itself that sends PRs updating the file :)

I think the `filesync` manager idea deserves its own issue, as more people than just Renovate bot maintainers can benefit from this feature. Feel free to close the issue if you disagree! 😉 

Currently there's no way - or at least no easy way - to tell Renovate that you want to sync file(s) between your repository and a upstream repository.

You'd need to be able to tell Renovate:

- What's the upstream repository
- What files you want to sync, say only a `schedule.json` file, or a full directory (probably a regex)
- How often you want Renovate to check for differences (can use our existing scheduling options for this)

Any change to the upstream file should result in a update PR, under the default settings.

If you needed to "mirror" a full repository, you'd use `git-submodules` or `git subtree` to do this, so I think I'd be okay to limit the total size of the input to whatever seems reasonable to process.

**Did you already have any implementation ideas?**

Nope, this is out of my league. 😄

**Comment by rarkins** [comment]
Yes, this seems to make a lot of sense, so we just need to work out how to fit it into Renovate in practice. Single file is easiest to start with, but we should plan for multiple in future. We should also work out how to "optimize" it, e.g. so that we don't need to download and compare byte-for-byte every single run. Ideally we can use `HEAD` requests with something like cached E-Tag values for that.

**Comment by HonkingGoose** [comment]
Duplicate of #4759
