### ISSUE TITLE
Self-hosted composer registry on self-hosted GitLab gives wrong package url

### ISSUE THREAD

**Issue by mrgesco** [renovatebot/renovate#10649]
**How are you running Renovate?**

- [x] Self hosted

Please select which platform you are using:
- [x] GitLab self-hosted

Renovate version: 25.31.0

**Describe the bug**

I have created a Composer registry on a self-hosted GitLab instance and trying to use two composer repositories on a project.

When renovate parses the composer file and tries to check the version, it gives a 404 error while trying to check on packagist instead of the right repository url.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
DEBUG: Datasource 404 (repository=***REDACTED***)
       "datasource": "packagist",
       "lookupName": "***REDACTED***",
       "url": "https://packagist.org/p/***REDACTED***.json"
DEBUG: Failed to look up dependency ***REDACTED*** (repository=***REDACTED***, packageFile=composer.json, dependency=***REDACTED***)
....
DEBUG: packageFiles with updates (repository=***REDACTED***)
"config": {
    "composer": [
    {
        "packageFile": "composer.json",
        "deps": [
        ......
        {
            "depType": "require",
            "depName": "***REDACTED***",
            "currentValue": "^3.0",
            "datasource": "packagist",
            "lockedVersion": "3.0.0",
            "depIndex": 18,
            "updates": [],
            "warnings": [
            {
                "topic": "***REDACTED***",
                "message": "Failed to look up dependency ***REDACTED***"
            }
            ]
        }
        ],
        "lockFiles": ["composer.lock"],
        "registryUrls": [
           "https://wpackagist.org",
           "https://<GITLAB_URL>/api/v4/group/<GOURP_ID>/-/packages/composer",
           "https://packagist.org"
        ],
    }
...
DEBUG: exec completed (repository=***REDACTED***, branch=renovate/lock-file-maintenance)
       "cmd": "composer update --with-dependencies --ignore-platform-reqs --no-ansi --no-interaction --no-scripts --no-autoloader",
       "durationMs": 6604,
       "stdout": "",
       "stderr": "Loading composer repositories with package information\nUpdating dependencies\nLock file operations: 0 installs, 1 update, 0 removals\n- Installing ***REDACTED***/***REDACTED*** (3.0.0):
```
</details>

**Have you created a minimal reproduction repository?**

https://github.com/mrgesco/renovate-20210629

- [x] I have provided a minimal reproduction repository

**Comment by rarkins** [comment]
Where's the repo?

**Comment by HonkingGoose** [comment]
I think this is the repo: https://github.com/mrgesco/renovate-20210629 😉

**Comment by mrgesco** [comment]
> Where's the repo?
Sorry... issue edited

**Comment by mrgesco** [comment]
Any update on this issue?

**Comment by HonkingGoose** [comment]
I think we're still at the stage where we're figuring out what's going wrong, and if/how we want to fix it.

**Comment by herndlm** [comment]
Interesting, I seem to be having the same problem but not related to GitLab. My composer.json has 2 custom repos, basically looking like this
```json
"repositories": [
        {
            "type": "composer",
            "url": "https://foo/bar/"
        },
        {
            "type": "composer",
            "url": "https://baz"
        }
]
```
And I see that renovate is able to lookup packages from baz but not the ones from foo/bar because it tries to look on packagist.
```
DEBUG: Datasource 404 (repository=acd/analytics.icis.com)
08:02:45
         "datasource": "packagist",
08:02:45
         "lookupName": "vendor/package",
08:02:45
         "url": "https://packagist.org/p/vendor/package.json
08:02:45
  DEBUG: Failed to look up dependency vendor/package (repository=xxx, packageFile=composer.json, dependency=vendor/package)
```
I can though access `https://foo/bar/p/vendor/package.json` just perfectly fine.

I'll try to debug / fix this later, but any hints would be appreciated.

**Comment by herndlm** [comment]
@mrgesco this might have been fixed with my changes that were released in 29.34.0. Let me know if it works now. If not fixed yet - I might be able to help out here. But I need at least a redacted output of your https://<GITLAB_URL>/api/v4/group/<GOURP_ID>/-/packages/composer/packages.json

**Comment by viceice** [comment]
create a public reproduction on gitlab.com

**Comment by viceice** [comment]
or better create a public composer package on gitlab.com and a public consuming reproduction repo on github.com

**Comment by LeoniePhiline** [comment]
@viceice PR #14160 fixes this.

Problem was that platform token was not used for `'packagist'` context requests.

**Comment by viceice** [comment]
It's currently intended to not use the platform token for `packagist`. You should be able to simply add an additional host rule for `packagist`.

**Comment by LeoniePhiline** [comment]
Part of the issue is that when authentication to one of the composer manager's `repositoryUrls` fails, the user is not informed; not even in debug mode. This code path misses all diagnostics output. 

This means that there are two separate issues:

If a platform provides an "all in one" feature set, such as gitlab (repo, ci/cd, package registries for multiple languages/ecosystems, docker dependency proxy etc.) then users would (today) expect renovate to authenticate with the token they were instructed to configure as environment variable. (Paraphrasing: "You only need to configure RENOVATE_TOKEN and GITHUB_COM_TOKEN.")

1. The documentation could reflect (easily understandable and obvious to new users) that the same credentials must be configured multiple times because renovate lacks the logic to know how to handle the "all in one" platform. It's just a matter of perspective in the current situation: Users experience their platform as "one" while renovate handles each of the platform's services as if they were entirely unrelated to each other.  Next to that, Renovate's output should make it obvious that authentication against the platform's package registry fails and therefore the package registry URL is skipped. 
2. The other part is refactoring renovate into a more modern idea of what a platform is today, given that these have changed and gotten far more feature rich over the years. This includes that in the generic and specific platform initialization code, each platform should know what it provides and configure renovate to correctly consume all of its services. (Currently the generic code adds configuration after the specific platform init code has returned. This architecture brings mess with it when platforms need to be configured for the specific services the platform itself know about. It might be helpful to move more knowledge into the platform-specific code.)

**Comment by mrgesco** [comment]
@herndlm After a while I finally had time to recheck this bug.
With the update, the fix for me was to add a hostRule with the token to access my private registry

`module.exports = {
    hostRules: [
      {
        matchHost: 'https://<GITLAB_URL>/api/v4/group/<group-id>/',
        username: '___token___',
        password: process.env.MY_SUPER_SECRET_TOKEN,
      }
    ],
    autodiscover: false,
    dryRun: false,
};
`
