### ISSUE TITLE
Renovate update docker image tag faster than image download availability

### ISSUE THREAD

**Issue by mbelang** [renovatebot/renovate#10662]
**How are you running Renovate?**

- [x] WhiteSource Renovate hosted app on github.com
- [ ] Self hosted

If using the hosted app, please skip to the next section.
Otherwise, if self-hosted, please complete the following:

Please select which platform you are using:

- [ ] Azure DevOps (dev.azure.com)
- [ ] Azure DevOps Server
- [ ] Bitbucket Cloud (bitbucket.org)
- [ ] Bitbucket Server
- [ ] Gitea
- [x] github.com
- [ ] GitHub Enterprise Server
- [ ] gitlab.com
- [ ] GitLab self-hosted

Renovate version: ...

**Describe the bug**
Renovate updates Dockerfile image tag faster that the image availability.
...

**Relevant debug logs**

See the pull request
![renovate](https://user-images.githubusercontent.com/5888932/123854936-4e73e900-d8ed-11eb-850b-e5999db7ce4f.png)

Failure in CI
![ci](https://user-images.githubusercontent.com/5888932/123855467-f12c6780-d8ed-11eb-947c-f9d9851cb56d.png)

From my local machine
```
docker pull python:3.9.6-slim-buster
3.9.6-slim-buster: Pulling from library/python
no matching manifest for linux/amd64 in the manifest list entries
```

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

It is a bit hard to reproduce as you have to wait for a new version of a public docker image do be release and then wait for renovate to create the PR that kicks a CI pipeline that builds the image.

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [x] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

...

**Comment by HonkingGoose** [comment]
Until we get around to fixing this in our code, you could try adding a custom `packageRules` for Docker datasources in your `renovate.json` file:

```json
  "packageRules": [
    {
      "matchDatasources": ["docker"],
      "stabilityDays": 1
    }
  ]
```

This will make it so that Renovate bot waits a full day before opening any Docker updates.
Example: say `python:3.9.6-slim buster` releases today, you'd get a Renovate bot update PR tomorrow.

Link to our docs for the used properties:

- https://docs.renovatebot.com/configuration-options/#matchdatasources
- https://docs.renovatebot.com/configuration-options/#stabilitydays

**Comment by viceice** [comment]
another solution is to use `amd64/python:3.9.5-slim-buster`  image.

**Comment by HonkingGoose** [comment]
> another solution is to use `amd64/python:3.9.5-slim-buster` image.

@viceice can you explain why this would a better image? How does using a different image prevent this problem? I have the feeling I'm missing something here... 😄

**Comment by viceice** [comment]
That image points directly to the amd64 image, the `python` image points to a image manifest list, which can contain more platforms. 

because the python images for multiple platforms are build in parallel, it can happen that the amd64 versions are not yet available in the manifest list, but renovate founds the list and will update the tag.

so renovate can't know from image name which platform it is targted later.

**Comment by rarkins** [comment]
Best solution is as @viceice suggests - use amd64/ prefix.
