### ISSUE TITLE
Refactor code to follow Luxon 2 upgrade guide

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#10910]
**What would you like Renovate to be able to do?**

The package Luxon 2 was upgraded with PR #10905, and all tests pass. 
So we don't _have to_ make further changes.

That said, I still think it's a good idea to adjust our code to follow their recommendations. This will probably make upgrading to a future major version of Luxon a bit easier.

**Did you already have any implementation ideas?**

Follow Luxon 2 upgrade guide, make changes to the code where needed.

Link to upgrade guide: https://moment.github.io/luxon/#/upgrading?id=breaking-signature-changes

I cannot help with the code refactoring.

**Comment by viceice** [comment]
https://github.com/renovatebot/renovate/blob/91a7e6b660a0ac0b66cf54a24bde3855d0633235/lib/versioning/node/index.spec.ts#L52-L53

should use `jest.spy`

**Comment by viceice** [comment]
All other code looks goot to me

**Comment by HonkingGoose** [comment]
I suspect this might be a `good first issue`, so I've labeled it as such.

**Comment by MaronHatoum** [comment]
Hi
can you please assign this issue to me?

**Comment by munierujp** [comment]
How about using other more popular libraries (e.g. [date-fns](https://npmjs.com/package/date-fns), [dayjs](https://npmjs.com/package/dayjs))?

<img width="1293" alt="スクリーンショット 2022-04-02 20 09 20" src="https://user-images.githubusercontent.com/20086673/161380536-186c2e30-76cd-450e-aec8-21524de36564.png">

https://www.npmtrends.com/date-fns-vs-dayjs-vs-luxon

cf. https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by rarkins** [comment]
@munierujp thanks for the suggestion. Can you do a quick check whether the functions we use are all supported by the other lib(s)?

**Comment by munierujp** [comment]
@rarkins I would be able to do it because there are few places where Luxon is used in this project. However, it will take some time.

**Comment by munierujp** [comment]
@rarkins Luxon is used in 18 files now.

<details>
<summary>Show used functions per files</summary>

- `lib/modules/datasource/metadata.ts`
  - `fromISO`
  - `isValid`
  - `toISO`
- `lib/modules/datasource/maven/index.ts`
  - `fromFormat`
  - `isValid`
  - `toISO`
- `lib/modules/datasource/maven/util.ts`
  - `fromISO`
  - `toJSDate`
- `lib/modules/platform/github/index.spec.ts`
  - `now`
  - `minus`
  - `toISO`
- `lib/modules/platform/github/index.ts`
  - `fromISO`
  - `diffNow`
  - `negate`
  - `toMillis`
- `lib/modules/versioning/node/index.spec.ts`
  - `fromISO`
- `lib/modules/versioning/node/index.ts`
  - `local`
  - `fromISO`
- `lib/util/cache/package/file.ts`
  - `local`
  - `fromISO`
  - `plus`
- `lib/util/cache/package/redis.ts`
  - `local`
  - `fromISO`
  - `plus`
- `lib/util/http/github.spec.ts`
  - `local`
  - `toISO`
  - `minus`
- `lib/util/http/github.ts`
  - `local`
  - `fromISO`
  - `toISO`
  - `plus`
- `lib/workers/repository/process/limits.spec.ts`
  - `local`
  - `toISO`
  - `minus`
- `lib/workers/repository/process/limits.ts`
  - `local`
  - `startOf`
  - `fromISO`
- `lib/workers/repository/update/branch/index.ts`
  - `fromISO`
  - `plus`
  - `local`
- `lib/workers/repository/update/branch/schedule.ts`
  - `local`
  - `setZone`
  - `toISO`
  - `startOf`
  - `diff`
  - `toJSDate`
- `lib/workers/repository/update/pr/changelog/release-notes.spec.ts`
  - `local`
  - `minus`
- `lib/workers/repository/update/pr/changelog/release-notes.ts`
  - `fromJSDate`
  - `fromISO`
  - `local`
  - `diff`
- `lib/workers/repository/updates/generate.ts`
  - `fromISO`

</details>

Here is correspondence table of functions which is used:

|Luxon|date-fns|dayjs|
|---|---|---|
|`diff()`|`differenceIn~()`|`diff()`|
|`diffNow()`|`differenceIn~()`|`diff()`|
|`fromFormat()`|`parse()`|[CustomParseFormat](https://day.js.org/docs/en/plugin/custom-parse-format)|
|`fromISO()`|`parseISO()`|`dayjs()`|
|`fromJSDate()`|not necessary|`dayjs()`|
|`isValid()`|`isValid()` or `isDate()`|`isValid()`|
|`local()`|not necessary|`dayjs()`|
|`minus()`|`subDays()`|`subtract()`|
|`negate()`|` * -1`|` * -1`|
|`now()`|not necessary|`dayjs()`|
|`plus()`|`addDays()`|`add()`|
|`setZone()`|[date-fns-tz](https://www.npmjs.com/package/date-fns-tz)|[Timezone Plugin](https://day.js.org/docs/en/plugin/timezone)|
|`startOf()`|`startOf~()`|`startOf()`|
|`toISO()`|`formatISO()`|`toISOString()`|
|`toJSDate()`|not necessary||`toDate()`|
|`toMillis()`|`getTime()`|`valueOf `|

Since date-fns uses the JS Date as is, some functions are not necessary.

**Comment by rarkins** [comment]
I'm leaning towards date-fns. What do you think? And were you interested in doing this refactoring yourself?

**Comment by viceice** [comment]
ok, thanks.

we should compare the required package sizes too, so we don't switch to a more popular bigger library.

so i prefer to only switch to a smaller library, as we currently don't need any new functionality.

**Comment by munierujp** [comment]
@rarkins 

> I'm leaning towards date-fns. What do you think? And

When I deal with dates in JS, I prefer to use date-fns because it is easy to use since it is function-based.

>And were you interested in doing this refactoring yourself?

I think most parts can be done, but the process of dealing with time zones may be difficult for me. This is a problem with my skills 😅

**Comment by munierujp** [comment]
@viceice dayjs seem to be much smaller in size than Luxon.

https://github.com/you-dont-need/You-Dont-Need-Momentjs#brief-comparison

However, I have not actually checked.

**Comment by rarkins** [comment]
I'm not too worried about size for Renovate itself, but it would be nice if our code is "browser ready" wherever possible. In that case dayjs has an advantage due to its size (pre tree shaking).

**Comment by viceice** [comment]
i personally prefer luxon because I'm a fan of object oriented programming.

**Comment by viceice** [comment]
@HonkingGoose There is nothing to migrate for us. so the primary goal of this issue is resolved.

@rarkins Should we close this issue and open a new for the other discussion? Or should we rename this issue?

**Comment by rarkins** [comment]
Let's close this.
