### ISSUE TITLE
Use Renovate to keep forks in sync with source

### ISSUE THREAD

**Issue by mrlubos** [renovatebot/renovate#11008]
**What would you like Renovate to be able to do?**

I'd like to use Renovate to keep my repository up-to-date. My repository B is a fork of repository A which doesn't belong to me, and I'd like to keep my HEAD in sync with the latest changes in repository A while I add my own features in my fork.

**Did you already have any implementation ideas?**

Not really, but it sounds like a good use case in the sense that repository A becomes a dependency of my repository B. In most forks I assume you want to stay in sync with the source project. Sometimes you only need a single feature and once it gets implemented in the original repository you can drop your fork, but you need to remember to check the source and update your fork until then. There is [another bot](https://github.com/wei/pull) specifically for this purpose, but Renovate feels like a more suitable candidate to handle this functionality.

**Comment by HonkingGoose** [comment]
It's really easy to abuse actions that update forks. I've seen that `wei/pull` action get abused by a spammer to annoy many people who collaborated on `github/docs`.

The setup was that the spammer used the `wei/pull` action to update their fork of `github/docs` with a `wei/pull` roll-up PR.
The action would "refresh" the PR with new commits each time upstream `github/docs` updated. The new commits had mentions of users so like:

`#issue_number @HonkingGoose docs: fix typo`

Each time that PR updated, the commits would get rebased/remade, so everybody who was mentioned got pinged again.

It was not possible to ignore the `wei/pull` action messages, so you kept getting pinged, with no option to stop the messages...... Many GitHub users complained at the action maker, and they managed to turn off the action for the spammer somehow...

I'm mentioning this example because I worry that allowing things like this can provide spammers the tools to annoy a lot of people at once, which will then sour people on using/contributing to Renovate bot...

**Comment by mrlubos** [comment]
> It's really easy to abuse actions that update forks. I've seen that `wei/pull` action get abused by a spammer to annoy many people who collaborated on `github/docs`.
> 
> The setup was that the spammer used the `wei/pull` action to update their fork of `github/docs` with a `wei/pull` roll-up PR.
> The action would "refresh" the PR with new commits each time upstream `github/docs` updated. The new commits had mentions of users so like:
> 
> `#issue_number @HonkingGoose docs: fix typo`
> 
> Each time that PR updated, the commits would get rebased/remade, so everybody who was mentioned got pinged again.
> 
> It was not possible to ignore the `wei/pull` action messages, so you kept getting pinged, with no option to stop the messages...... Many GitHub users complained at the action maker, and they managed to turn off the action for the spammer somehow...
> 
> I'm mentioning this example because I worry that allowing things like this can provide spammers the tools to annoy a lot of people at once, which will then sour people on using/contributing to Renovate bot...

Hi, thanks for this, interesting! Would this issue have occurred also when people do manual sync with upstream? I haven't come across it before, how common is that? Does it still happen today or has it been solved somehow?

**Comment by HonkingGoose** [comment]
I managed to find the issue on `wei/pull` that complains about the same spammer that was bothering the `github/docs` contributor: https://github.com/wei/pull/issues/267

The spammer used a `commit-lint` bot to _mention/ping_ users on the PR that`wei/pull` regularly updates/refreshes.

The root cause was **not** with `wei/pull` itself, but I'm still rembering the pull bot for making this mess (_which it didn't_). So this goes to show how damaging this can be to the reputation of a project.

---

> Would this issue have occurred also when people do manual sync with upstream?

Yes, if people create _new_ commits on their clone/fork, they can cause linkbacks/mentions as well...

I managed to accidentally spam a `tailwindcss` repo once with a badly done `git rebase -i --root`, so you don't need to have a bot to spam. 🙈 Luckily once I removed/deleted my bad fork, the linkbacks were gone as well. So no permanent harm done...

**Comment by rarkins** [comment]
This does seem like a philosophical Renovate topic - keep things updated - but I'm not sure it fits in with our architecture.

First of all, can it be done with a Pull Request? We could probably raise a pull request directly from the upstream repo commit to the forked child repo, without needing to make any commits ourselves.

But here's the problem, it's not properly up-to-date unless it has the exact same commits/SHAs as in the upstream repo. If we or GitHub "recreate" any of the commits then it defeats its purpose. I think we'd need GitHub to support FF merge commits in order to achieve that, but it doesn't: https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/about-merge-methods-on-github

Technically I know how to do what the pull app is doing - it's a single PATCH API command to the fork, and we do it ourselves when in forking Renovate mode - but doing that doesn't fit in with our typical workflow.

**Comment by mrlubos** [comment]
> This does seem like a philosophical Renovate topic - keep things updated - but I'm not sure it fits in with our architecture.
> 
> First of all, can it be done with a Pull Request? We could probably raise a pull request directly from the upstream repo commit to the forked child repo, without needing to make any commits ourselves.
> 
> But here's the problem, it's not properly up-to-date unless it has the exact same commits/SHAs as in the upstream repo. If we or GitHub "recreate" any of the commits then it defeats its purpose. I think we'd need GitHub to support FF merge commits in order to achieve that, but it doesn't: https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/about-merge-methods-on-github
> 
> Technically I know how to do what the pull app is doing - it's a single PATCH API command to the fork, and we do it ourselves when in forking Renovate mode - but doing that doesn't fit in with our typical workflow.

Thank you! I think that answers the question so I will close the issue. However, if you ever decide to reconsider, I'd be only happy to also use you for this purpose. I will go with the other available solution in the meantime

**Comment by HonkingGoose** [comment]
@mrlubos I did find another "easy but manual way" to sync your fork with upstream:

GitHub now provides a button to merge `upstream/main` into the forks `main` branch. Go to your forks "homepage" on GitHub, and find the "fetch upstream" button. This should just fast-forward merge, _if_ you did not push any commits of your own to the forks `main` branch. 😉 

The [GitHub docs, syncing a fork from the web ui](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork#syncing-a-fork-from-the-web-ui) explain this in full.

**Comment by rarkins** [comment]
Was it your idea that renovate would just force push the new commit to your repo silently/without PR?

**Comment by mrlubos** [comment]
I'm not sure if this is a question for me, but my idea was to have an explicit pull request. Essentially the same way it already works for regular dependencies. I've seen projects where the fork was modified and behind the upstream by a lot and it was so painful to update because upstream introduced many breaking changes. The way I had to deal with it was going merge commit by merge commit and track all the changes and update the fork to play nice with them. I suspect having regular maintenance updates on the fork would've prevented this pain months/years later.

**Comment by rarkins** [comment]
I think due to GitHub's no-ff limitation that wouldn't be possible to achieve with pull requests. Although the *content* of your head commit would be the same as your upstream, your head commit SHA would not be, so it would not be "clean".
