### ISSUE TITLE
Remove Gitlab Approvers on MR creation

### ISSUE THREAD

**Issue by cjpearson** [renovatebot/renovate#11106]
**What would you like Renovate to be able to do?**

#10981 is working great for automerge updates, but it doesn't remove approvers when automerge is not enabled.

In our setup, we want some updates to still be merged by a human, but we want to skip our default approval rules. Is it possible to also remove approvers on MR creation?

**Did you already have any implementation ideas?**

**Comment by rarkins** [comment]
I think we could change it from Boolean to enum, Eg always/automerge/never where always is the new option you're asking for

**Comment by cjpearson** [comment]
Yeah, that would definitely work for us.

**Comment by antonym** [comment]
+1, we were trying to get automerge on Gitlab working and the unchecking of "Prevent editing approval rules in merge requests" did not seem to work.  Our settings were:

```
  "packageRules": [
    {
      "matchManagers": ["dockerfile"],
      "enabled": true,
      "automerge": true,
      "platformAutomerge": true,
      "automergeType": "branch",
      "rebaseWhen": "behind-base-branch"
    }
```

but we were getting the 406 Not Acceptable, Branch cannot be merged. Automerge works great with approvers, but it would be nice to have certain cases automerge without approvers.

**Comment by rarkins** [comment]
I don't think we're actually clear on what needs to be done here, e.g. which API used, and under which conditions. Can anyone elaborate?

**Comment by antonym** [comment]
We are running on GitLab SaaS running:

`renovate/renovate:31.53.2@sha256:e638885dc70836373709aab1f97257a450709241e0ab6ad3eb71d87140cf0161`

We have a version in a Dockerfile we'd like to auto maintain as it increments and push the image to the registry when there is an update. We are setting the following in the repo's renovate.json:

```
  "packageRules": [
    {
      "matchManagers": ["dockerfile"],
      "enabled": true,
      "automerge": true,
      "platformAutomerge": true,
      "automergeType": "branch",
      "rebaseWhen": "behind-base-branch"
    }
```

This would let the repository automerge the commit, leveraging the built-in GitLab merge functionality when tests pass and would merge the commit to the main branch directly so that a human doesn't need to press the approve button. Our repos currently have approver set to 1 so this causes the `automergeType: PR` to not automerge.

As it stands right now, automerge fails with a 406 from the GitLab API so it falls back to creating a PR with an approver. Once a human has approved it, it then is able to automerge. We have tried to set `Prevent editing approval rules in merge requests` on and off to see if it works according to this document but it never seems to auto approve the MR according to the document [here](https://github.com/renovatebot/renovate/blob/main/docs/usage/configuration-options.md#gitlabignoreapprovals).

It seems like this functionality may have an issue as it stands today that is preventing it from altering the approvers on the fly. Is there anymore information that would be helpful?

**Comment by TheBous** [comment]
Something new here?

**Comment by rarkins** [comment]
Closing in favor of #5709
