### ISSUE TITLE
support for bumpVersion with helm-requirements

### ISSUE THREAD

**Issue by dudicoco** [renovatebot/renovate#12099]
### What would you like Renovate to be able to do?

The `helmv3` manager supports bumping the chart version automatically within `Chart.yaml` whenever a dependency is updated: https://github.com/renovatebot/renovate/blob/main/lib/manager/helmv3/update.ts

It would be great to have the same functionality for the `helm-requirements` manager.

### If you have any ideas on how this should be implemented, please tell us here.

I assume the code should be pretty similar to the `helmv3` code.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by morremeyer** [comment]
I suggest to close this issue. Helm v2, which used the `requirements.yaml` file, is end of life since November 2020.

Helm v3 uses the `dependencies` section in the `Chart.yaml`, which already supports `bumpVersion`. While you can still use the `requirements.yaml` file, it is recommended to use the new format.
Migration to the new format is trivial by moving the `dependencies` section into the `Chart.yaml` file.

Source: https://helm.sh/docs/faq/changes_since_helm2/#consolidation-of-requirementsyaml-into-chartyaml

**Comment by viceice** [comment]
Closing, since helm v2 is EOL since more than 2 years and most helm charts are migrated to helm v3 too, so they are not usable either.
