### ISSUE TITLE
Refactor global config to singleton class

### ISSUE THREAD

**Issue by pret-a-porter** [renovatebot/renovate#12639]
### Describe the proposed change(s).

As part of #9996 global config class can implement next interface:
```
interface GlobalConfig {
  set(config: RenovateConfig | RepoGlobalConfig): void
  get(): RepoGlobalConfig;
  reset(): void;
}
```

**Comment by HonkingGoose** [comment]
I think you mean singleton, not single-tone. 🎵

**Comment by pret-a-porter** [comment]
@HonkingGoose yeah, indeed :))

**Comment by HonkingGoose** [comment]
@zharinov, @viceice and @JamieMagee, can you take a look at this issue, and say if this is a good course of action or not? In the linked issue [^issue] you also got asked to look at the proposal before starting, so that's why I'm asking for your review here as well.

[^issue]: https://github.com/renovatebot/renovate/issues/9996#issuecomment-913129658

**Comment by pret-a-porter** [comment]
Yeah, I had provided few examples but did not receive any feedback

**Comment by viceice** [comment]
@pret-a-porter  please go ahead, looks good so far. 🤗
