### ISSUE TITLE
Authentication failure after update to v30

### ISSUE THREAD

**Issue by wjentner** [renovatebot/renovate#13054]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

30.2.1

### Please select which platform you are using if self-hosting.

GitLab self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

kubernetes v1.21.7; gitlab community edition 14.5.2

### Describe the bug

After updating to v30.x.x
Renovate-bot prints has an `Authentication failure`.

We are using the helm chart to deploy renovate in our cluster as a cronjob.
When downgrading to v29.x.x renovate continuous to work.

### Relevant debug logs

<details><summary>Logs</summary>

```
renovate-bot-manual-5fk-qzklr renovate FATAL: Authentication failure
renovate-bot-manual-5fk-qzklr renovate  INFO: Renovate is exiting with a non-zero code due to the following logged errors
renovate-bot-manual-5fk-qzklr renovate        "loggerErrors": [
renovate-bot-manual-5fk-qzklr renovate          {
renovate-bot-manual-5fk-qzklr renovate            "name": "renovate",
renovate-bot-manual-5fk-qzklr renovate            "level": 60,
renovate-bot-manual-5fk-qzklr renovate            "logContext": "67bKnpgTSodJzQrXUQRwe",
renovate-bot-manual-5fk-qzklr renovate            "msg": "Authentication failure"
renovate-bot-manual-5fk-qzklr renovate          }
renovate-bot-manual-5fk-qzklr renovate        ]
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by roobre** [comment]
I believe this could be related to:

> config: Renovate will now fail if RENOVATE_CONFIG_FILE is specified without a file extension

(https://github.com/renovatebot/renovate/releases/tag/30.0.0)

This should have been fixed here: https://github.com/renovatebot/helm-charts/pull/170

But unfortunately the line introduced in that PR will not be evaluated because the whole `env` section is guarded by another if: https://github.com/renovatebot/helm-charts/blob/5e50b02fcc60139538e07e1079464ce0fa9ddb6a/charts/renovate/templates/cronjob.yaml#L88

As a workaround, this can be specified in the `values.yml`

```
  env:
    RENOVATE_CONFIG_FILE: /usr/src/app/config.json
```
