### ISSUE TITLE
Detect semantic commit scope

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#1308]
Right now we:
- Retrieve the most recent commit messages (up to 30 on GitHub)
- Pass the array of messages to `conventional-commits-detector`
- If any type is found, then enable angular style semantic commits

Ideally we should
- Avoid false positives
- Customise for non-angular

**Comment by rarkins** [comment]
Related to https://github.com/singapore/renovate-config/issues/8 from @edmorley

**Comment by rarkins** [comment]
I thought of ignoring the eslint-style commits, but then found I'd need to ignore jquery too. Basically any commit message with "something: foo bar" is detected as a semantic commit.

I'm thinking:
1. Reduce the total commit messages we pass to conventional-commits-detector
2. Pass them one at a time and then look at how many true/false there are and we apply our own decision whether to enable
3. If we detect, non-angular, perhaps we can also set the semantic commit scope to null too, so just the semantic commit type is used

One more thing to consider: once semantic commits have been detected by Renovate, Renovate's *own* semantic commits will *keep semantic commits enabled* even if everyone else in the repository is no longer using them!

**Comment by edmorley** [comment]
I think that this kind of thing is probably quite hard to auto-detect reliably. Matching against `<anything>: ...` will catch cases where people occasionally use arbitrary strings to represent subcomponents of their apps (such as `docs: foo` or `frontend: bar`), which aren't really the same as the fix/chore/... semantic categories. (It will also catch patterns like `{Ticket,Bug,...} 1234: foo` which don't match the semantic style either).

An alternative might be to match against a fixed list of strings (eg `{fix,chore,...}`) instead. Whilst this would mean a few cases go undetected (perhaps because they use alternate wordings like `{bugfix, refactor, ...}`), those cases would have still required manual configuration since the default Renovate PR titles/commit messages wouldn't match the style they use.

That all said, erring on the side of false positives may not necessarily be a bad thing - it's easy to turn off and and least people then know the feature exists (compared to it defaulting to off, or erring on the side of false negatives).

**Comment by rarkins** [comment]
Renovate now:
- Uses only last 10 commits
- Only auto enables semantic commits if "angular" type is found

Still to do:
- Detect if commit scope should be null or not (e.g. just "chore:" and not "chore(deps):"
