### ISSUE TITLE
Use example commit messages rather than PR body in onboarding PR

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#1315]
In #1314 I mistakenly thought that the bullet point examples given in our onboarding PR (mozilla/treeherder#3025) were what the commit messages would be. However it looks like they are instead the PR body content.

To help people figure out if the commit message style needs customising before the onboarding PR is merged, I think it might be better to use the commit messages rather than the PR body text in the examples. (Or if that's not desired, to make it clearer that what's shown is not the commit message.)

**Comment by rarkins** [comment]
Sounds reasonable, especially as it would help give a better preview of what's to come. 

On a related note, the way that Renovate commits/PRs *ultimately* appear in your base branch is dependent on how you merge them - merge commit, squash commit, or rebase commit. I typically use squash commits on non-Renovate PRs to squash the branch into a single `master` commit so then the PR title is what is shown, but for Renovate PRs I prefer rebase commits these days so that the GPG-signed commit gets landed onto `master` instead. 

Also on a related note, I need to double check that grouped PRs (e.g. monorepos) have a commit message that makes sense.

**Comment by rarkins** [comment]
Here's an example monorepo commit message:

![image](https://user-images.githubusercontent.com/6311784/34177519-2617a7e8-e504-11e7-8673-30b0db7282de.png)

**Comment by rarkins** [comment]
So for grouped PRs you’d *lose* details because currently we list every dep update whereas the commit message doesn’t have that. I don’t mind though.

**Comment by rarkins** [comment]
Waiting on #1747
