### ISSUE TITLE
autodiscoverFilter with commas

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#13168]
This seems to be breaking our setup where we define the filter similar to this:

```
export RENOVATE_AUTODISCOVER_FILTER="project/{a,b,c,d,*-app}"
```

This gets mapped to the following value in 31.2.2

```
"autodiscoverFilter": "project/{a,b,c,d,*-app}"
```

But it breaks to the following after that.

```
"autodiscoverFilter": [
    "project/{a",
    "b",
    "c",
    "d",
    "*-app}"
]
```

_Originally posted by @cascornelissen in https://github.com/renovatebot/renovate/issues/13100#issuecomment-996645166_

**Comment by rarkins** [comment]
@secustor I don't think we have any way to distinguish between an intentional list separated by commas vs a single string which includes commas. Here's our code:

https://github.com/renovatebot/renovate/blob/8b3b80c3e41d97f78d0ee884feb4a02603b4f081/lib/workers/global/config/parse/cli.ts#L50-L59

**Comment by rarkins** [comment]
I think this is a workaround: `RENOVATE_AUTODISCOVER_FILTER=["project/{a,b,c,d,*-app}"]`

But we probably should revert this in v31 and document it as a breaking change (for edge cases) for v32

**Comment by cascornelissen** [comment]
Just tried out what you suggested @rarkins but that results in the following (stripped out a bit for brevity)

```
"autodiscoverFilter": ["[project/{a", "b}]"]
```

**Comment by secustor** [comment]
@rarkins WDYT about implement the optional regex interpreter before the breaking version, so that user can migrate in the meanwhile?

e.g "project/{a,b,c,d,*-app}" --> "regex:project\/(a|b|c|d|.*-app)"

**Comment by rarkins** [comment]
Maybe use `/ ... /` as the indicator though, or could that be a valid glob pattern?

**Comment by secustor** [comment]
As I am aware the trailing `/` is not valid in glob, but I have proposed `regex:` as we use it in different places already.     
E.g. versioning. https://docs.renovatebot.com/modules/versioning/

**Comment by viceice** [comment]
we are also using `/ ... /` for regex

- https://docs.renovatebot.com/configuration-options/#allowedversions
- https://docs.renovatebot.com/configuration-options/#matchcurrentversion

**Comment by morremeyer** [comment]
I've been dealing with an edge case regarding the escaping of slashes in the last few days: 

We run renovate self-hosted, deployed with the helm chart. This is managed by terraform. The configuration looks as follows (some parts left out for brevity):

```hcl
resource "helm_release" "renovate" {
  repository = "https://docs.renovatebot.com/helm-charts"
  chart      = "renovate"
  version    = "31.64.0"

  name      = "renovate"
  namespace = "renovate"

  values = [yamlencode({
    cronjob = {
      # Run only once per hour as we manage *a lot* of repositories
      schedule          = "23 * * * *"
      concurrencyPolicy = "Forbid"
    }

    redis = {
      enabled = true
    }

    renovate = {
      config = jsonencode({
        autodiscover = true

        onboardingConfig = {
          extends = [
            "github>anaconda/renovate-config"
          ]
        }
      })
    }
  })]
}
```

Due to the fact that we're using hcl with `yamlencode` and `jsonencode` nested inside of it, we can't effectively use `/` as regex delimiter and use an `autodiscoverFilter` that excludes repositories due to

* a regex with `!/(org\/repo|org\/repo2)/` would be valid: with `/` as delimiter, the `/` for the repo name must be escaped
* the `\` needed to escape the `/` cant be used here as `\/` is not a valid escape sequence in HCL, therefore terraform will fail
* Escaping in any other way will produce `!/(org\\/repo|org\\/repo2)/` in the `config.json`.

Therefore, support for something else than `/`, preferably `%` as this is not a valid character in repository URLs, at least on GitHub.

If there's interest for this, I can try opening a PR for it.

**Comment by viceice** [comment]
Did you tested `!/(org/repo|org/repo2)/`, i think regex is smart enough to properly detect.

**Comment by morremeyer** [comment]
@viceice I did, but actually had a typo in the string that made it fail. Thank you for making me check it again - it works as you described.

**Comment by rarkins** [comment]
@secustor @viceice I forget the current status of this one after the various rollbacks and commits

**Comment by viceice** [comment]
No idea, sorry. 🤷‍♂️

**Comment by secustor** [comment]
The commit which introduced this has been reverted.
