### ISSUE TITLE
Branch prefix description is not updated in the onboarding PR

### ISSUE THREAD

**Issue by hkdobrev** [renovatebot/renovate#1359]
When changing `renovate.json` in the `renovate/config` branch, the description is successfully updated in regards to the pull requests it would create.

However, when I change the `branchPrefix` setting to `renovate-`, the description still mentions:

> Use `renovate/` as prefix for all branch names

I think this should also be taken into account when re-rendering the onboarding PR description.

**Comment by rarkins** [comment]
Thanks. This is a kind of "generic" problem with that onboarding description process. It essentially just extracts the list of preset descriptions and then lists them one by one. If you have a preset that overrides a previous one then you usually end up with both descriptions, which may contradict. And if you use raw config instead if a preset, then you get no description with that.

The solution - eventually - will be that presets can explicitly list other presets that they negate or override, and then the onboarding PR can interpret that to know what description to generate or suppress.

**Comment by hkdobrev** [comment]
@rarkins Interesting. I would have thought there's a merging process from all presets producing one final configuration and only then the description is generated. Do you mean that renovate doesn't know which description takes precedence in the merging?

**Comment by rarkins** [comment]
The onboarding PR approach to descriptions is as simple as "Extract the descriptions from every preset in the top level `extends` array". 

The way the *config* is merged is as you probably expect, and is quite complex and cascading. The reason you can't use logic is if you have a scenario like:
- Preset "foo" sets config "a" to value true and "b" to true
- Preset "bar" sets "b" to false and "c" to false

The resulting config is a is true, b is false and c is false. But we can't completely remove the entire "foo" description because it also probably refers to "a".

It also gets more complex because field "b" might be a mergeable object too, e.g. both might be applying settings to "docker" and therefore they are *merged* instead of bar overwriting foo.

**Comment by hkdobrev** [comment]
OK, I think I got it.

I don't know much about the renovate system, but if I were you, I'd then generate the description from the presets and configuration keys present in the JSON. I think it'd be easy to then give priority to descriptions coming from the configuration keys. 

However, for that to work, the description needs to be moved away from presets and that I guess comes with BC. Also, I suppose you wouldn't want all descriptions from config keys coming from presets. Either way, there isn't really a simple solution to that.

**Comment by rarkins** [comment]
My goal is to make presets good enough and searchable enough that most users can use them and zero manual config objects, and also allow presets to define which other rules they override (if at all), and then the construction of description will still be pretty easy. I used to "reverse engineer" descriptions from raw config and it was pretty tough to keep consistent. Thanks for your feedback!

**Comment by hkdobrev** [comment]
Perhaps, if there's a preset with an argument for the branch prefix, the description could still be generated correctly.
