### ISSUE TITLE
Define a policy for breaking changes

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#13801]
### What would you like Renovate to be able to do?

I've copy/pasted the original comment from @Arabus https://github.com/renovatebot/renovate/pull/12266#issuecomment-1021031857 into this issue.

> The usual deprecation / breaking change stuff, i.e.:
> I propose you define a policy for breaking changes e.g., what to do in emergency/security cases, what to do with regular feature updates like this.

### If you have any ideas on how this should be implemented, please tell us here.

> Example (following SemVer as guiding principle):
> 
> - In case of emergency changes breaking changes can happen directly with the next major release
> - In case of regular breaking changes, a deprecation period of one major version must be maintained i.e., the breaking feature must be gated behind a feature flag, preserving the deprecated default until the next major release

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by HonkingGoose** [comment]
## Show users what version of Renovate is running now

Part of the problem is that there's no easy way for users to know which version of Renovate is running on the GitHub hosted app. I had the idea to "Show the Renovate version in the `prBody`", see issue #13006. Which at least shows what they're running now, but it doesn't help with the "Help Renovate suddenly updated to a new major which breaks my workflow" part.

## How to warn our users of upcoming changes?

I think the bigger issue here is that we have no easy/reliable way to alert our users to upcoming changes. Nobody is going to follow/subscribe to our release notes, as there are too many to keep up with.

## Highlight tradeoffs when using GitHub hosted app

Maybe part of the solution is to explain the benefits and drawbacks of using the hosted app.
We could add a text like this to our "Running Renovate" page: [^running-renovate]

```markdown
## Benefits/drawbacks of using the hosted app

Benefits:

- You're always up-to-date automatically
- You're always on a version that the maintainers care about
- You're getting new features/bugfixes regularly

Drawbacks:

- Zero control over what version of Renovate runs
- Sudden breaking changes to behavior
```

[^running-renovate]: https://docs.renovatebot.com/getting-started/running/

**Comment by rarkins** [comment]
Our policy is this: when we make breaking changes, we increment a major version. This is per the SemVer spec. Claims about the "guiding principle" of SemVer appear to be made up and certainly can not be found at https://semver.org/

**Comment by Arabus** [comment]
I assume there is a communication error here. I should have included a "as a guiding principle for a versioning scheme" there. Semver makes no claims about a deprecation policy, which is why I stated that you should decide on one. "None" can be a valid (albeit granted to cause discussions) policy. My example was simply using SemVer as a policy for versioning not for deprecation.

Concerning #12266 it looked like the discussion was diverging from the actual change towards whether and how to release it in a manner causing the least ruckus for your users. Which is why I made the above suggestion because it allows you to make breaking changes in a more gentle way while still allowing progressive users to make use of them already (and merging them sap).

If you already have a policy regarding the release then I fail to understand the goal of the discussion in #12266
