### ISSUE TITLE
Update version in .scalafmt.conf file

### ISSUE THREAD

**Issue by andreisilviudragnea** [renovatebot/renovate#13877]
### What would you like Renovate to be able to do?

Renovate should be able to update the `version` field inside the `.scalafmt.conf` file.

### If you have any ideas on how this should be implemented, please tell us here.

I suppose it should be easy to implement custom file handling.

### Is this a feature you are interested in implementing yourself?

Yes

**Comment by rarkins** [comment]
You may need both a datasource as well as manager. Where is the authoritative list of scala versions? e.g. is there a github repo with releases?

**Comment by kluen** [comment]
# New package manager questionnaire

**Did you read our documentation on adding a package manager?**

- [x] I've read the [adding a package manager](adding-a-package-manager.md) documentation.

## Basics

### Name of package manager
[Scalafmt](https://scalameta.org/scalafmt/). It is not a package manager, but a code formatter. The configuration file `.scalafmt.conf` requires you to set the version of the formatter you want to use.

### What language does this support?
Scala

### How popular is this package manager?
It is the de-facto standard.

### Does this language have other (competing?) package managers?

- [ ] Yes (give names)
- [x] No

At least nothing that seems to be actively developed.

---

## Package File Detection

### What type of package files and names does it use?
`.scalafmt.conf`

### What [fileMatch](../usage/configuration-options.md/#filematch) pattern(s) should be used?


### Is it likely that many users would need to extend this pattern for custom file names?

- [ ] Yes
- [x] No

### Is the fileMatch pattern likely to get many "false hits" for files that have nothing to do with package management?
---

## Parsing and Extraction

### Can package files have "local" links to each other that need to be resolved?
No.

### Is there a reason why package files need to be parsed together (in serial) instead of independently?
No.

### What format/syntax is the package file in?

- [ ] JSON
- [ ] TOML
- [ ] YAML
- [x] Custom (explain below)

The format is in HOCON, see https://scalameta.org/scalafmt/docs/configuration.html

### How do you suggest parsing the file?

- [x] Off the shelf parser
- [ ] Using regex
- [ ] Custom-parsed line by line
- [ ] Other

### Does the package file structure distinguish between different "types" of dependencies? e.g. production dependencies, development dependencies, etc?

- [ ] Yes, production and development dependencies
- [x] No, all dependencies are treated the same

### List all the sources/syntaxes of dependencies that can be extracted

Just the HOCON field `version`.

### Describe which types of dependencies above are supported and which will be implemented in future
n/a

---

## Versioning

### What versioning scheme does the package file(s) use?
SemVer, e.g `1.0.0`

### Does this versioning scheme support range constraints, e.g. `^1.0.0` or `1.x`?

- [ ] Supports range constraints (e.g `^1.0.0` or `1.x`)
- [x] No

---

## Lookup

### Is a new datasource required? Provide details

- [ ] Yes, provide details.
- [x] No.

Not entirely sure, but the versions should be accessible from GitHub releases.
See https://github.com/scalameta/scalafmt/releases

### Will users need the capability to specify a custom host/registry to look up? Can it be found within the package files, or within other files inside the repository, or would it require Renovate configuration?
No.

### Do the package files have any "constraints" on the parent language (e.g. supports only v3.x of Python) or platform (Linux, Windows, etc.) that should be used in the lookup procedure?
No.

### Will users need the ability to configure language or other constraints using Renovate config?
No.

---

## Artifacts

### Are lock files or checksum files used? Are they mandatory?
No.

### If so, what tool and exact commands should be used if updating one or more package versions in a dependency file?
No.

### If applicable, describe how the tool maintains a cache and if it can be controlled via CLI or environment variables? Do you recommend the cache be kept or disabled/ignored?
n/a

### If applicable, what command should be used to generate a lock file from scratch if you already have a package file? This will be used for "lock file maintenance"
n/a

## Other

### Is there anything else to know about this package manager?
No.

**Comment by rarkins** [comment]
Looks like it should be fairly easy if the file format is simple and it can reuse our existing github releases datasource.

**Comment by kluen** [comment]
One thing that comes to mind: Is it possible (also, wanted) for Renovate to execute other tools as part of the update?

One thing that Scala-Steward (a similar tool which is Scala-only) does, is it runs scalafmt after bumping the version. This way you don't get failing builds if you have formatting checks, but rather a PR that contains both the version bump and formatting changes, if there are any.
