### ISSUE TITLE
Feature request: dry run / verbose test mode

### ISSUE THREAD

**Issue by dylang** [renovatebot/renovate#1399]
As we tweak our config, it runs renovate in the PR which has caused some confusion.

We don't want any merges or pull requests generated or merged, especially during work hours until we know we are happy with the configuration.

It would be helpful if there was some kind of `dry run` or verbose test mode that would do everything short of creating or modifying pull requests, and instead just log those intentions, so the engineers responsible for configuring renovate know they did everything correctly and no unintentional PR's or updates were created or merged in the process.

**Comment by rarkins** [comment]
Hi @dylang, this would be a nice feature. Generally though my expectation is that you will wait until you're happy with the configuration until merging the onboarding PR.

In the meantime you can set a schedule like first day of the month, and you will get an almost dry-run as a result. But also add `"updateNotScheduled": false` too so that any existing PRs are left alone when out of schedule.

**Comment by dylang** [comment]
> you will wait until you're happy with the configuration until merging the onboarding PR

This only works if we know the configuration is correct. :) 

We're still tweaking, trying to figure out why PR's aren't getting assigned, why dozens of packages haven't been getting updates, and what some settings mean or how they should be be used.

You've created an awesome and impressive beast, and we're just trying to figure out how to best control before we set it lose on our repos. :)

**Comment by rarkins** [comment]
Well, I'm happy to help and thanks for your feedback. I'll try to fix any outright bugs if you find them. I've classified this as a fix because from what you *describe*, it should already be supported. If it's not then I'll fix it, if it is then we need to go into more details to work out where the difference is between your repository structure and everyone else's that's tried so far.

One of the design goals is to make it "insanely" configurable but of course flexibility comes at the cost of complexity. Adding presets is an attempt to abstract away as much of it as possible, and it's an ongoing thing to improve that.

If you're struggling too much getting config right, perhaps try forking your own repo and running it on the fork to avoid disturbing other users? Renovate by default ignores forks, but you can force it on by adding `"renovateFork": true` to its `renovate.json`.

If you just have questions rather than features or fixes, feel free to spam https://github.com/renovateapp/config-help/issues too

BTW did you stumble on Renovate because it's using `changelog` as a dependency, or was it just a coincidence?

**Comment by dylang** [comment]
> If you're struggling too much getting config right, perhaps try forking your own repo and running it on the fork to avoid disturbing other users

Excellent idea.

> BTW did you stumble on Renovate because it's using changelog as a dependency, or was it just a coincidence?

I didn't realize that, nice! I keep forgetting about that module, would it be helpful if I gave you contributor access? 

I learned about this from @SpainTrain who recommended it after setting it up at <a href="https://www.myhomezen.com/hello">homezen</a>.

**Comment by rarkins** [comment]
> I didn't realize that, nice! I keep forgetting about that module, would it be helpful if I gave you contributor access?

You already gave me contributor access :)

But if you could install Renovate there, it would be great - some of those dependencies are very out of date.

**Comment by dylang** [comment]
> You already gave me contributor access :)

Haha, sorry, I've been out of touch with my open source work for a while.

> But if you could install Renovate there, it would be great - some of those dependencies are very out of date.

Added!
