### ISSUE TITLE
Remove dependencies

### ISSUE THREAD

**Issue by alexeagle** [renovatebot/renovate#1503]
This might not be a job for renovate but I am curious what are your thoughts.
It would be awesome to remove unused dependencies, if you could figure out which ones they are or at least have a heuristic that is often right.

**Comment by rarkins** [comment]
Relevant: https://github.com/depcheck/depcheck

**Comment by destroyerofbuilds** [comment]
Not sure whether this should be a direct feature in Renovate, given the risk of false-positives, but because the act of upgrading dependencies has consequences (resources utilization by Renovate, triggering new releases of libraries, etc.) it would be nice if Renovate had a story around this particular situation.

As noted above, there are a few benefits to understanding unused dependencies:
* Avoid the cost of upgrading those dependencies (Time for Renovate to run, CI execution, etc.)
* Avoid triggering a new release of a library because of an upgraded unused dependency.

I recently came across the service that will report unused dependencies (For example Renovate):

![unused](https://user-images.githubusercontent.com/10657293/36159931-92eda0d0-10a5-11e8-861e-fb020522271d.png)

However, I believe it also demonstrates how false positives can happen as I believe `pnpm` is invoked as a CLI tool, not imported/required.

**Comment by alexeagle** [comment]
I think a tool would have fewer false positives if it instrumented every
script under node_modules, ran all the build/release tooling and tests,
then detected which packages had no scripts run. But I don't think it's
practical to run the release tooling...

**Comment by destroyerofbuilds** [comment]
> I think a tool would have fewer false positives if it instrumented every
script under node_modules, ran all the build/release tooling and tests,
then detected which packages had no scripts run.

I think that would be sufficient.

> But I don't think it's
practical to run the release tooling...

I would agree. Right now Renovate can upgrade a project without actually installing anything to disk, let alone run a project's `test` script in `package.json`.

Perhaps Renovate could make the feature opt-in, and when you opt-in, you whitelist packages that Renovate should just assume are used.

Though, I would also like to argue that perhaps this isn't an issue for Renovate to solve. The fact that a dependency isn't used is usually the result of a refactor, and perhaps the project's build should detect that a dependency isn't used any longer.

**Comment by hulkish** [comment]
Wouldn't the risk here be adverted if renovate just makes a pr recommending these kinds of changes?

**Comment by destroyerofbuilds** [comment]
> Wouldn't the risk here be adverted if renovate just makes a pr recommending these kinds of changes?

My personal preference would be to detect unused packages as part of a project's build so that a refactor is not pushed to GitHub until any unused dependencies from a refactor are removed.

Moving this workflow to a Renovate PR has the following disadvantages:
* Consumers of the project are still downloading the unused dependency (if it's a run time dependency) until the Renovate PR has been accepted.
* The Renovate PR will lead to a notification sent to all project members, even though the unused dependency was introduced by a single member of the team.

I don't see any advantages of moving this workflow to a Renovate PR.

**Comment by hulkish** [comment]
> I recently came across the service that will report unused dependencies

@destroyerofbuilds can u elaborate on this?

**Comment by destroyerofbuilds** [comment]
@hulkish there is a Software-as-a-Service that will process a project using a set of programmatic rules and report issues as _Alerts_ on pull requests.

The service is LGTM - https://lgtm.com/projects/g/singapore/renovate

I heard about it a few weeks ago and began exploring it for use in a few open source projects.
