### ISSUE TITLE
Consider Ubuntu `22.04` Jammy Jellyfish stable

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#15220]
### Describe the proposed change(s).

Ubuntu `22.04` Jammy Jellyfish will become a stable LTS release soon.

We'll need to fix the code so Renovate proposes upgrades from `20.04` to `22.04`.

I _think_ this is part of the code to fix:

https://github.com/renovatebot/renovate/blob/2c087e86f78503c7f22d93bc88f97a86e3b33a3f/lib/modules/versioning/ubuntu/index.spec.ts#L198-L201

Or do we want to wait until the `22.04.1` release before considering Jellyfish stable?

Related discussions:

- https://github.com/renovatebot/renovate/pull/12528
- https://github.com/renovatebot/renovate/issues/12535

**Comment by rarkins** [comment]
It actually already is, e.g.

![image](https://user-images.githubusercontent.com/6311784/164431835-8976c124-4835-4eef-89ac-edf51ccf887c.png)

But we just merged a PR to delay by one day because the Ubuntu website still lists it as "Future" LTS right now and not current:

![image](https://user-images.githubusercontent.com/6311784/164431986-0062b785-10a5-4af2-a2d7-c490f6ca6147.png)

**Comment by HonkingGoose** [comment]
Whoops, I was wrong. 🙃 Sorry for the noise!
