### ISSUE TITLE
Make required minimum access level configurable

### ISSUE THREAD

**Issue by Taucher2003** [renovatebot/renovate#15421]
### What would you like Renovate to be able to do?

Currently, autodiscovery is hardcoded to only find projects, where the bot has at least Developer Permissions. In some cases, you need to check for a different access level (but can't do that, as it is currently hardcoded).

In my case, I want the bot to discover all projects where the bot is member of (also if it is just invited as a guest).
This is mostly useful for selfhosted GitLab Instances because you have some possibilities to have users which are not on Developer Level, but still have permission to do some things in the project.

We are currently working around the problem of paying an additional ultimate seat just for a bot user. We theoretically could use a group access token (which as a bot does not consume a seat) but we need the automation instance wide and therefore, the solution with group access tokens does not scale well (as that would also require using multiple renovate runs, each with its own token).

### If you have any ideas on how this should be implemented, please tell us here.

While autodiscovering the projects the bot has access to, the required access level is hardcoded to 30 (= Developer). https://github.com/renovatebot/renovate/blob/2d0cdd7ad4cfc3ecd1630d0722fa84d81ffae380/lib/modules/platform/gitlab/index.ts#L144

This can be implemented by changing the hardcoded 30 to a configurable variable.

### Is this a feature you are interested in implementing yourself?

No because of the required CLA

**Comment by rarkins** [comment]
The levels below developer do not appear to be suited to do what Renovate requires:

![image](https://user-images.githubusercontent.com/6311784/166460367-a641ffea-1ab8-49cc-a888-df8f8538ab94.png)

![image](https://user-images.githubusercontent.com/6311784/166461202-7c9204c6-298d-4335-b6d6-9a84e9d369b7.png)

Do you have guest accounts which can bypass these controls, or you're content with it erroring for what it needs to do?

Re: CLA is that because you object, or you have lawyers who object? "I work for a company which pays for gitlab ultimate but is not willing to let me contribute to your open source project" is an interesting combination if so.

**Comment by Taucher2003** [comment]
> The levels below developer do not appear to be suited to do what Renovate requires:

By default, yes. On gitlab.com / SaaS you also don't have the possibility to adjust that. However on self-managed, you can do some more things, because you have full access (even with the possibility to modify small things of the code, to adjust them to your need). \
I can understand if you say, that this is not default behaviour of GitLab and therefore will not be supported. However, that would also add the possibility to limit autodiscovery in the other direction, as example only projects where the bot is at least maintainer

> Do you have guest accounts which can bypass these controls, or you're content with it erroring for what it needs to do?

First, on self-managed you have some more options (not directly with modifiable permissions, but in the way a user is set up) so we have a guest user currently used for Renovate. For now, the repositories are specified in the cli params but that will also get messy to maintain as the number of projects which use the renovate grows.

> Re: CLA is that because you object, or you have lawyers who object?

It's a personal decision of me, I don't want to think about anything legal related just for some small open source contributions

**Comment by rarkins** [comment]
I think this risks confusion and support problems so would prefer not to do it. People who have platform problems (such as branch protection) always try to force us to prove it's not Renovate's fault, because they know they're unlikely to get anyone from GitHub/GitLab/etc to look at the problem with any speed.
