### ISSUE TITLE
Reevaluate REST vs GraphQL for GitHub PRs

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#15497]
### Describe the proposed change(s).

We switched from GraphQL to REST because GraphQL POST can't support caching like a REST GET can. However I believe in the latest iteration of our intelligent PR caching, we always fetch at least one page anyway.

Therefore, I want to reevaluate if we should restore the GraphQL approach if there are any benefits making it worth it (but with same approach - 100 per page for empty cache, 20 if cache exists). For example maybe comment fetching is better? I'm not sure though with caching whether comment fetching advantages from GraphQL are nullified.

To reiterate on the way our intelligent caching works:
- If no cache, we fetch PRs, up to a limit of 10 pages, with 100 PRs per page
- If a cache exists, we fetch the first 20 PRs sorted by last-modified-date, compare dates to our cache, and only keep fetching more pages if we need

I'm also interested in increasing or maybe even lifting completely the 10 page limit so that we don't expire old closed/ignored PRs so quickly on active projects.

**Comment by zharinov** [comment]
The reason behind switching to REST was to leverage its support for HTTP caching mechanism (i.e. `ETag` and `If-Modified-Since` headers). This proved to be unusable due to instability of `ETag` thanks to `pushed_at` frequent changes, while `If-Modified-Since` just doesn't work at all.

I don't see any good reason to switch back to GraphQL for now. One reason might be to simulate `If-Modified-Since` behavior using exact pagination (`before`/`after`), but this would have more complicated the code to maintain. Another one is comments fetching, but seems like we don't need them to be fetched for each PR.
