### ISSUE TITLE
Separate rules for repos with lockfiles

### ISSUE THREAD

**Issue by kesne** [renovatebot/renovate#1612]
Right now, we're putting configuration in repos based on if a lockfile is present or not. Would it be possible to have the option to define configuration that applies for repos with lockfiles separately? This would let us avoid in-repo configuration. Not sure how much demand there would be for this, just thought I would bring it up.

**Comment by rarkins** [comment]
Can you give some example of configuration differences you apply based on lock file or no lockfile?

**Comment by kesne** [comment]
Yeah for sure! As an example, we want to apply `upgradeInRange` to our apps with lockfiles, but we don't want this configuration to apply for libs with no lockfiles (i.e. we want to keep the ranges wide). It's easy enough to define configuration in the repo for now, just thought it could be useful for others.

**Comment by rarkins** [comment]
Right now there is no obvious or elegant way to achieve this I can think of, otherwise I would have a shot at implementing it. It's kind of complicated because of things like (a) there are more languages supported than just JS, and (b) monorepos, etc.

If you are applying common config across many repos you may be interested in defining your own "preset" package which could include one setting for app and another for library. Then each repo just gets a single `extends` value and you can make updates "centrally". Kind of like ESLint configs :)

**Comment by destroyerofbuilds** [comment]
>  but we don't want this configuration to apply for libs with no lockfiles (i.e. we want to keep the ranges wide)

Please consider using lockfiles in _all_ projects. Your library can still have wide semver ranges in the `package.json` file, but having a lockfile means that you can pull down a git commit at any time, and get _exactly_ the same dependencies, and as a consequence, the same build experience (build success or build failure, but either way, a reproducible build)
