### ISSUE TITLE
Support "old" rubygems index

### ISSUE THREAD

**Issue by narwold** [renovatebot/renovate#16126]
### What would you like Renovate to be able to do?

Using the well-known sidekiq gems, there is a private repo for the pro&enterprise versions.
but https://enterprise.contribsys.com/api/v1/dependencies?gems=.. doesn't exist, resulting in 404s on the Renovate side.

However, the "old" versions of rubygems endpoints are available : https://enterprise.contribsys.com/info/sidekiq-ent
(see issue https://github.com/mperham/sidekiq/issues/4988)

We need Renovate to auto fallback to the old but still used configurations.

For more discussion, see https://github.com/renovatebot/renovate/discussions/11407#discussioncomment-1300392

### Reproduction

1. Add the following to a project's Gemfile:

```
source 'https://enterprise.contribsys.com/' do
  gem 'sidekiq-ent', '< 3'
  gem 'sidekiq-pro', '< 6'
end
```

2. Add the following to the Renovate config:

```
    {
      "hostType": "rubygems",
      "matchHost": "https://enterprise.contribsys.com",
      "username": "<sidekiq_username>",
      "encrypted": {
        "password": "<encrypted_sidekiq_password>"
      }
    },
```

### If you have any ideas on how this should be implemented, please tell us here.

Current endpoints are hardcoded in `lib/modules/datasource/rubygems/get.ts`. We need the ability to fallback to the "old" endpoints. However, these don't seem to support JSON, so a new parser might be necessary.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
Does this really require the enterprise version to reproduce? I thought there was a link to a public registry in the other discussion. It's not really a reproduction unless others can run it (also needs to be in a repo)

**Comment by rarkins** [comment]
Would be good to know what order of registries bundler itself tries

**Comment by narwold** [comment]
https://enterprise.contribsys.com/info/sidekiq-ent is the public link, but somewhere along the line I believe it requires auth to install the dependency.

**Comment by rarkins** [comment]
That's ok, I think we have solved an important step if we just get past the failed lookup step

**Comment by narwold** [comment]
Agreed

**Comment by rarkins** [comment]
After looking into your PR, I have some ideas to discuss:

Apart from our hardcoded Rubygems rule, we don't know which servers support versions, API, or both.

We ideally don't want to waste API calls trying and retrying.

So for each unique host, we ideally want to discover/fail just once, then remember it until stopped.

Maybe we should always try `/versions` first? It should be lighter weight for any registry which supports it.

But then we need to add logic so that we still retrieve and aggressively cache metadata about package and releases to *supplement* the results from `/versions`.

We could do this in two steps:
- Refactor to always try `/versions` first for a host, and remember permanently if it works or not
- If `/versions` is not available then try the API

This should mean:
- backwards compatible with Rubygems, because versions will work
- change other hosts to use versions instead of API if they support both (which potentially means loss of metadata)
- hosts with only versions will now be supported

Then the second step is to add the metadata retrieval via API in addition to `/versions`.

Are we ok to break it into two steps and risk losing metadata for some private hosts temporarily, or should we combine the steps?

**Comment by narwold** [comment]
If we "add logic so that we still retrieve and aggressively cache metadata", wouldn't this ultimately mean the same number of API calls if we didn't assume caching? Because instead of checking API then versions, you're checking versions then API, but you're still checking both. The key part it seems to me would be caching the response. Does this sound right?

I would think that whichever version is considered more modern would make sense to check first, but I'm by no means an expert in the Ruby dependency ecosystem.

So I guess we're looking at 2 questions/asks:
1) Cache at the appropriate times
2) Determine which is the best order to fetch, knowing that we may want to do both anyway.

**Comment by rarkins** [comment]
We cache the versions endpoint least aggressively (eg 15 minutes) but any metadata we get from the API (such as source URLs) we cache for Eg a day. So it's not the same

**Comment by narwold** [comment]
You probably don't cache 404s to indicate that something is unreachable to allow for instant fallback?

**Comment by rarkins** [comment]
Not yet but we should if we go down this path

**Comment by narwold** [comment]
OK, so I feel like that (caching 404s) would be the more important step to avoiding the extra calls, correct?

The order seems like a separate discussion, and I'm not sure which way it should be. One could also argue that hitting the API first could be more efficient since it's querying for a single gem, whereas `versions` lists all dependencies.

**Comment by rarkins** [comment]
We should remember for each host if it supports the versions endpoint. If not (e.g. 404) then there's no need for us to try again for every lookup. Is that what you meant too?

In that case here are our logic paths:

- Does versions exist? [remember this value per host] If so then use it for the list of releases, cache break it every 15 minutes or so because it's efficient. Then use the API if it exists to supplement the release information, such as sourceUrl, releaseTimestamp, etc. Cache those aggressively (e.g. 24 hours)
- If versions endpoint does not exist, then try the API for both versions and metadata, and break cache the usual time (e.g. 30 minutes)

**Comment by narwold** [comment]
Right. That all makes sense. The only thing I'm questioning is the order. If `versions` doesn't give us metadata, then we'll have to check the API anyway, won't we? In this case, does it make more sense to check the API first and have the maximum potential gain right away? Or I guess, maybe now that I'm thinking about it and countering my own argument, the pitfall of that would be that you have to check and cache 404s for multiple API endpoints vs just one `versions` endpoint. In that case, I suppose `versions` first makes sense.

**Comment by rarkins** [comment]
The backstory as I understand it is that rubygems added an API and then they discovered that the API doesn't scale as they need and Bundler use crushes it and therefore Bundler switched to using the more efficient `/versions` endpoint, and now it seems third party vendors have mimicked that (some not even supporting the API at all?).

So what I'm proposing is essentially:
- Heavy use of `/versions` to detect versions, and
- Limited, heavily cached use of the API to supplement versions with metadata

To try API first would mean we can't achieve that balance. Perhaps only Rubygems has the scalability problem but still, we may as well mimic that behavior for all.

**Comment by hugopochart** [comment]
Hello,

Do you have any updates on this issue?

**Comment by narwold** [comment]
> Hello,
> 
> Do you have any updates on this issue?

I've been poking at this in https://github.com/renovatebot/renovate/pull/16312. Haven't had a chance to look at the failing tests. Anyone is welcome to contribute.

**Comment by jdemangeon** [comment]
Hello @narwold 

Me and @hugopochart have been working on the 2 remaining uncovered lines from tests.
Here's the corresponding PR -> https://github.com/narwold/renovate/pull/1

Let us known if it's ok on your side :) 

Thanks a lot 👌
