### ISSUE TITLE
Renovate fails to process intentionally-missing (conditionally-included) gradle file

### ISSUE THREAD

**Issue by GrahamBorland** [renovatebot/renovate#16447]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

Renovate logs a warning because of a conditional reference to one Gradle file which is expected to be missing in a clean checkout of the repo.

In the root **build.gradle**:
```gradle
// passwords for code signing
if (new File('secure.gradle').exists()) {
    apply from: 'secure.gradle'
}
```
This was working fine up until a few days ago, but now Renovate reports an error in the dashboard issue:
> These problems occurred while renovating this repository.
> 
> - WARN: Failed to process Gradle file

### Relevant debug logs

<details><summary>Logs</summary>

```
WARN: Failed to process Gradle file
{
  "scriptFilePath": "secure.gradle"
}
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by GrahamBorland** [comment]
Ignoring the missing file with `ignorePaths` didn't cure the issue, so reopening.
```json
  "ignorePaths": [
    "secure.gradle"
  ],
```

**Comment by Churro** [comment]
Currently, file parsing for gradle works context-insensitive and without actually invoking `gradle build`, renovate cannot evaluate the `if (new File('secure.gradle').exists())` statement to find out if `secure.gradle` exists or not. 

Now since a few days, `apply from` is matched by the gradle manager and, as `secure.gradle` apparently doesn't exist, a warning is shown. So basically, this is expected behavior.

**Comment by GrahamBorland** [comment]
Thanks for the info. I was able to fix the problem in my case by using a `.properties` file instead of a conditionally-applied `.gradle` file, so this is no longer an issue for me.
