### ISSUE TITLE
Handle post-preset resolution validation errors

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#1647]
This preset inside `extends` is not being raised as a config error:
```
   ":timezone(Europe/Brussel)",
```

Should we (a) look explicitly for that preset and validate it? After all, it's a "default" preset..

Or (b) should we validate presets post-resolve too?

The challenge with (b) is that a validation problem in an upstream preset would cause a config error which stops Renovate, even though the user may have no control over it and it could be nested several levels deep. However, it could also be a nasty error with undesired side-effects - but it's pretty hard for us to deduce if that's the case.

**Comment by rarkins** [comment]
Seeking feedback from users on this. If a bad commit is made to a preset you use (maybe even one of the project’s default ones) and it fails validation, do you want to either:

(A) keep going and risk that behaviour is wrong?
(B) have Renovate raise a warning and stop processing until it’s fixed? Note: you may not have control over this upstream

Or.. (C) make it configurable? Adds complexity if so

**Comment by HonkingGoose** [comment]
If a bad commit breaks a preset, and it therefore fails validation, then the bot should definitely raise a warning and stop doing stuff. This seems to me much more preferable than just silently "eating the error" and risking undefined/wrong behavior.

So for me, I'll take: `(B) have Renovate raise a warning and stop processing until it’s fixed? Note: you may not have control over this upstream`

I don't know how complete the warning would be...
If it's just "stuffs broken, good luck figuring it out", that's not very handy.

Maybe we could do a `git bisect` in combination with the renovate npm-validator?
So that we could pinpoint to the user which commit broke stuff?
We probably would have a known good commit (One of Renovate bot's good commits), and the bad commit is somewhere between the last known good commit and the newest commit(s) at repository `HEAD`.

Or maybe we could just say: "the previous commit from renovatebot was good", that was at `$working-time`, now it's broken, and say something like: _A commit was made between `$working-time` and `$time-warning-was-raised`, please check the commits made to your Renovate config file made in this timeframe._

**Comment by viceice** [comment]
We should tests to completely validate our internal presets if we don't already have them.

I think most of config issues are already catched and posted as issue to the repo. If an error is catched, renovate already stops further processing. So we need to find out the missing validation parts.

**Comment by rarkins** [comment]
I think it's possible that we do validate this now, but I'm not certain. Next step is a reproduction repo to confirm if it's still relevant or not.
