### ISSUE TITLE
Our repo is `disabled`, but we have no understanding as to why...?

### ISSUE THREAD

**Issue by AlexanderMann** [renovatebot/renovate#16602]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

In the UI, all of our jobs are showing `disabled`, and if we click on any of them, we simply get 404s for the `logs` requests.

🔢  Most recent job id is: 737987040
:octocat: Organization name is `mdg-private`

@abernix and myself ran this locally and got the below logging. Looks as though everything succeeded?

We saw all of our Renovate PRs/issues etc. stop updating at `2022-07-01T15:53:16Z`. We recently did a _tonne_ of housekeeping to try and tidy up our endless sea of Renovate updates (we have a Monorepo, it's a beast, etc.) and in closing maybe a hundred Renovate PRs really quickly, I wouldn't be too surprised if we managed to 🔪 something on your end or expose a scale 🐛 ? (taking a shot in the dark there)

Any help you can offer twould be much appreciated. Love the product and totally understand if we've reached the limit of what we can do with you lot on the Open Source Free Hosted Version 🙇 

### Relevant debug logs

<details><summary>Logs</summary>

```
       },
       "hostStats": {
         "api.github.com": {"requestCount": 867, "requestAvgMs": 721, "queueAvgMs": 0},
         "auth.docker.io": {"requestCount": 6, "requestAvgMs": 752, "queueAvgMs": 0},
         "circleci.com": {"requestCount": 3, "requestAvgMs": 648, "queueAvgMs": 0},
         "index.docker.io": {"requestCount": 28, "requestAvgMs": 571, "queueAvgMs": 0},
         "plugins.gradle.org": {
           "requestCount": 230,
           "requestAvgMs": 269,
           "queueAvgMs": 0
         },
         "registry.npmjs.org": {
           "requestCount": 185,
           "requestAvgMs": 3998,
           "queueAvgMs": 0
         },
         "registry.terraform.io": {
           "requestCount": 8,
           "requestAvgMs": 5032,
           "queueAvgMs": 0
         },
         "repo.maven.apache.org": {
           "requestCount": 13316,
           "requestAvgMs": 190,
           "queueAvgMs": 0
         }
       },
       "totalRequests": 14643
 INFO: Repository finished (repository=mdg-private/monorepo)
       "durationMs": 901283
DEBUG: Renovate exiting
```

</details>

### Have you created a minimal reproduction repository?

No reproduction, but I have linked to a public repo where it occurs

**Comment by rarkins** [comment]
When repos take too long to process then they "time out" on our job workers after maximum 40 minutes. This means the job gets killed and the worker restarted before it can complete or push the log in progress. Right now we don't have the ability to assign varying resources per job, so essentially repos in this category have hit our limits for what we can do in the hosted app for now. We are working on a solution for the future where we can assign variable resources on a per-job basis, but it's not going to be ready soon. Repos such as yours which continuously time out (never finish a job) get automatically disabled, which is what happened here. I removed the disabling on your repo and tried it again today, but it unfortunately timed out again so I put the disabling back again.

When you run it locally it would be interesting to know how long each step takes. Maybe there's the chance we can optimize things so that runs can complete faster, e.g. process at most 2 branches in a run or something like that.

**Comment by y3ti** [comment]
@rarkins we have the same issue. I ran renovate locally and fixed all the issues (we had some timeouts to private repos). Can you re-enable our repo (`brave/search`, most recent job: `#752517070`)?

**Comment by abernix** [comment]
@rarkins 

> When you run it locally it would be interesting to know how long each step takes.

The mode that we ran and included the debug output above ran in 15 minutes, however, it's of course worth noting that it is running in `dryRun` mode, so potentially much less time than a full run.  A second ran I did this morning took just 9 minutes in dry-run mode.

> Maybe there's the chance we can optimize things so that runs can complete faster, e.g. process at most 2 branches in a run or something like that.

That would be a very reasonable option to explore on our end and we're happy to dig in: perhaps it would be prudent for us to only enable a single manager at a time?  Or a subset of the monorepo?  (Certain `package.json` files?).  Happy to limit it from whatever direction seems reasonable.  

Looking at the log output, two things stand out to me:

1. The time spent going through the 125 branches (`DEBUG: Processing 125 branches`)
2. The time spent fetching changelogs, but that seems like it's something that's substantially faster on the second run — likely due to a cache win?

Suggestions on the best approach?  Should I land some changes to the renovation configuration to narrow things down a bit and then ping you for a re-try?

**Comment by zharinov** [comment]
> That would be a very reasonable option to explore on our end and we're happy to dig in: perhaps it would be prudent for us to only enable a single manager at a time? Or a subset of the monorepo? (Certain package.json files?). Happy to limit it from whatever direction seems reasonable.

Probably, you may want to play with some of these options:
https://docs.renovatebot.com/configuration-options/#branchconcurrentlimit
https://docs.renovatebot.com/configuration-options/#prconcurrentlimit
https://docs.renovatebot.com/configuration-options/#prhourlylimit

**Comment by abernix** [comment]
Ok, just landed some changes.  I wasn't sure how aggressively to start, so we've set the following in our repository configuration, all of which were previously set to `0`:

```
  "prConcurrentLimit": 0,
  "prHourlyLimit": 5,
  "branchConcurrentLimit": 5,
```

Given my understanding of `prConcurrentLimit`, I think it should be fine left at `0` given that `branchConcurrentLimit` is set.  Does that sound right?

A local run of this with dry-run enabled completes in **under 8 minutes**.  Half of that time appeared to be fetching changelogs, as I noted above in my previous comment.  A subsequent re-run spent much less time on the changelogs and finished up in **under 3 minutes.**.  I'm assuming there's caching that is working!

I'm happy to make additional tweaks if you have additional suggestions, but could we try re-enabling it again for another run with these changes?

**Comment by rarkins** [comment]
Hi all, I'm currently vacationing in a cabin so interacting from mobile. Will try to reenable any repos listed above in the next day or two. 

Interesting observation re: changelogs. @zharinov maybe our intelligent caching can be enhanced for the changelogs use case too? Although I thought it maybe would be already

**Comment by zharinov** [comment]
> Given my understanding of prConcurrentLimit, I think it should be fine left at 0 given that branchConcurrentLimit is set. Does that sound right?

Personally I would prefer to set these options like this:
```ts
  "prConcurrentLimit": 5,
  "prHourlyLimit": 0,
  "branchConcurrentLimit": 5,
```

This would ensure new PRs won't stack up every hour until previously open PRs are merged. Additionally, `branchConcurrentLimit` would help to prevent flooding your repository with branches that aren't linked to any PR (yet).

**Comment by zharinov** [comment]
> Maybe our intelligent caching can be enhanced for the changelogs use case too? Although I thought it maybe would be already

@rarkins It uses cached raw data, but rendering it to Markdown seems quite heavy, so there may be room for improvement.

**Comment by abernix** [comment]
@rarkins please enjoy your vacation.  this can wait.

I'll also make the changes @zharinov suggested above during my tomorrow.

**Comment by abernix** [comment]
@zharinov Why do you recommend `prHourlyLimit: 0`?  Doesn't that make the number of PRs it'll open per hour _unlimited_?

**Comment by rarkins** [comment]
@y3ti I re-enabled brave/search but it looks like it's going to exceed the maximum execution time again. We'll keep trying to optimize this.

**Comment by y3ti** [comment]
@rarkins I works again. Thank you!

**Comment by zharinov** [comment]
> @zharinov Why do you recommend `prHourlyLimit: 0`? Doesn't that make the number of PRs it'll open per hour _unlimited_?

Here is the code which determines how many PR Renovate is about to create during particular run:
```ts
const hourlyRemaining = await getPrHourlyRemaining(config);
const concurrentRemaining = await getConcurrentPrsRemaining(config, branches);
return Math.min(hourlyRemaining, concurrentRemaining);
```

**Comment by AlexanderMann** [comment]
@zharinov we've merged the recommended changes and are ready to give this another shot!

(also, many thanks to @abernix for running with this for me, been on vacation 🌴 )

**Comment by abernix** [comment]
@rarkins if you're in charge of re-enabling, I guess we'd be ready for that now to see how it goes.

...and then if turns out that we're running up against upper bounds again, we can try to tie things down even more!

**Comment by sylvestre** [comment]
@rarkins I made the same change for gecko. Could you please enable github/sylvestre/gecko-dev/ too ?
thanks

**Comment by AlexanderMann** [comment]
So it looks like we're still disabled...which...le' bummer. @rarkins @zharinov do you know whether this is because of our beastie of a repo, or just not having been turned back on yet?

fwiw, I'm kinda thinking/wondering that _maybe_ we should bite the bullet and run Renovate as a container in CI for ourselves with just a bigger box. Seems like it might help you lot out, and would mean debugging for us is all "in house". Thoughts?

**Comment by rarkins** [comment]
I'm giving your repo a retry now

**Comment by AlexanderMann** [comment]
@rarkins circling back before my end of week, where'd we land here? Anything additional we can do for you all?

**Comment by rarkins** [comment]
The repo has been tried and timed out 16 times since re-enablement, so will be put back to permanent disabled mode. Unfortunately we do not have the ability to use differently sized compute VMs per repo and do not plan to increase our default size.

To close out this issue from your original question, the repo is disabled because it is unable to complete its run during the allocated maximum time of 30-40 minutes per repo.

**Comment by AlexanderMann** [comment]
Makes sense and sounds good. Truly, thank you so much for all your help on this. We'll update here with what we end up doing to get this running again. Pretty sure this is less than a days' worth of work in our CI setup. You lot are the best!

**Comment by rarkins** [comment]
BTW I'd be interested if you're able to work out if any particular phases of the renovate process take up the most time I'd you run it locally. Eg extract, lookup, updates, etc. For example it could be long running npm install commands. We would like to find and fix any performance hogs

**Comment by AlexanderMann** [comment]
Sure thing. Our monorepo is a known beast. Are there any performance logs or stats outputs which are of the most help to you?

**Comment by abernix** [comment]
@rarkins I understand from the self-hosted instructions that we'll create our own local Renovate Bot user to power this, but is there any documentation anywhere that outlines the best strategy for us doing that?  For example, should we bulk-close any pull-requests that are currently authored by the official renovate-bot?  (Or will it be able to understand that a new bot is coming in to take over the existing PRs?).

Also, I suspect we'll have to replicate the "Renovate approval bot" to emulate auto-merge capabilities?

**Comment by rarkins** [comment]
@abernix I discovered recently that changelog retrieval may be taking up a large proportion of a run's duration and contributing to the timeouts. Instead we could do this:
- I disable changelog fetching for your affected repos, hopefully then it will complete jobs (But PRs don't contain embedded release notes)
- We are actively working on finding the performance problem with changelogs and hope to be able to reenable them

**Comment by rarkins** [comment]
I just checked your monorepo and see that it still timed out, but it did a lot of work and also pushed a log to S3 so you can hopefully see it through the dashboard.

These numbers are pretty heavy:

```
{"level":20,"msg":"73 PRs are currently open","time":"2022-08-08T06:18:06.146Z"}
{"level":20,"msg":"PR concurrent limit remaining: 0","time":"2022-08-08T06:18:06.146Z"}
{"level":20,"prsRemaining":0,"msg":"Calculated maximum PRs remaining this run","time":"2022-08-08T06:18:06.146Z"}
{"level":20,"msg":"PullRequests limit = 0","time":"2022-08-08T06:18:06.146Z"}
{"level":20,"msg":"Calculating branchConcurrentLimit (5)","time":"2022-08-08T06:18:06.147Z"}
```

Even self-hosting you would probably want to optimize it a bit because every time you merge one of those 73 you'll need to rebase many or most of them.

**Comment by abernix** [comment]
Ah, well, nice try.  The changelog slowness was also something I observed when running it locally, but doesn't sound like that's the solution.

Since those 73 PRs have accumulated over the course of ... months, perhaps longer ... maybe we should just close the 73 PRs and start fresh.  The new rules we implemented above should limit the overall number of PRs, and that seems worth keeping around anyway to be honest.  (Though perhaps we could raise it to a number above `5` gradually.  Thoughts?
