### ISSUE TITLE
Show warnings indication in non-onboarding PR bodies

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#16924]
### What would you like Renovate to be able to do?

Show an indication in each non-onboarding PR if there were warnings encountered

### If you have any ideas on how this should be implemented, please tell us here.

I don't think we need to list all the warnings, instead we could "warn if there's warnings" and tell people to check the dependency dashboard or logs. Ideally we would say dashboard if it's enabled or logs if it's not.

### Is this a feature you are interested in implementing yourself?

No

**Comment by MaronHatoum** [comment]
do we want to minimize `Dependency Lookup Warnings` details in the PR body? 
so the user should look into the dashboard/logs to see more details about the warning.

**Comment by rarkins** [comment]
Yes, have the actual warnings minimised and deduplicated

**Comment by MaronHatoum** [comment]
I tried to create a scenario that allows us to see warnings in PR by adding a `dummyDependency` to the `package.json` file:
- in case the repository is not onboarded:
https://github.com/MaronHatoum/warnings-in-PR-bodies/pull/15
- Otherwise, in case the repository is onboarded and failure occurred in `extratct/lookup` dependency PR should not be created.
- In case project contains few dependencies and one of these dependencies failed to `extratct/lookup` PR will be created and 
`Artifact update problem` will be added in a new comment:
**PR:**
https://github.com/MaronHatoum/warnings-in-PR-bodies/pull/11

did I miss any scenario?

**Comment by rarkins** [comment]
We want a scenario where there's a PR with no artifacts errors but includes a lookup warning (or any other warning actually)

**Comment by MaronHatoum** [comment]
According to the code, I can see that `getDepWarningsPR()` and `getWarnings()` are called just one time in `onboarding/pr/index.ts` just if the repository is not [onboarded](https://github.com/MaronHatoum/warnings-in-PR-bodies/pull/15) and the lookup warnings appear in onboarding PR.
https://github.com/renovatebot/renovate/blob/301f8666d18bc84c94a258ad58a884d560a2848d/lib/workers/repository/onboarding/pr/index.ts#L116-L119

**lookup warning:**
- single library -> no update PR created
- a group of libraries: PR created with no warning messages for failed lookups

I think displaying warnings in PR (if not onboarding PR) is not supported.

So, I've added to `update/branch/index.ts` a condition to check if there are some warnings and display them in a comment in the PR.
**The result after changes:**
https://github.com/MaronHatoum/warnings-in-PR-bodies/pull/43

**Comment by MaronHatoum** [comment]
Since currently there are no warnings for non-onboarding PRs, I've tested adding a fixed warning message in a comment to the PR in `update/branch/index.ts`
(the message can be added to the PR body instead of a comment).

**The result after changes:**
https://github.com/MaronHatoum/warnings-in-PR-bodies/pull/43

WDYT?

**Comment by rarkins** [comment]
> I think displaying warnings in PR (if not onboarding PR) is not supported.

It's not supported today, but the purpose of this issue is to support it.

Do you mean that it's currently impossible to do due to other reasons?

We want it to be in the PR body, not comment.
