### ISSUE TITLE
Balance the load across baseBranches?

### ISSUE THREAD

**Issue by maxime-michel** [renovatebot/renovate#16932]
### What would you like Renovate to be able to do?

We happily use Renovate on an array of two base branches: `["master", "release/6.2"]`. The problem with our project is that it's so large that we've had to throttle the concurrent PRs to 5. This now leads us to the following problem: despite daily work on Renovate PRs since months, we're never able to catch up with `master` 100%. And so our `release/6.2` branch never gets any attention.

### If you have any ideas on how this should be implemented, please tell us here.

I would like to suggest the introduction of a parameter like `baseBranchesStrategy` that would default to `sequential` (`master` then `release/6.2`) but could also be set to `random` (balanced load).

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by rarkins** [comment]
Renovate prioritises branches by complexity of the upgrade, Eg digest first, then patch, minor, major. So it should not prioritise base branches ahead of others unless I'm forgetting something. Otherwise the best solution for this would be for renovate to support multiple rate limits, which already had a feature request here

**Comment by maxime-michel** [comment]
Thanks for the feedback, you mean this right? https://github.com/renovatebot/renovate/issues/10546

**Comment by rarkins** [comment]
Yes

**Comment by maxime-michel** [comment]
OK then let me watch that one instead.
