### ISSUE TITLE
No docker auth found - returning

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#17304]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

It used to work, and then stopped

### Describe the bug

After upgrading to 32.163.0 in the app, we've seen thousands of `No docker auth found - returning` warnings.

### Relevant debug logs

<details><summary>Logs</summary>

```
Copy/paste the relevant log(s) here, between the starting and ending backticks
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
@Churro @viceice do you think #17294 happens to fix it, or is it unrelated?

**Comment by rarkins** [comment]
This can be reproduced with `yarn start --dry-run=lookup elide-dev/v3`

Logs:

```
DEBUG: getDigest(https://us-docker.pkg.dev, elide-fw/tools/jdk17, undefined) (repository=elide-dev/v3)
DEBUG: getManifestResponse(https://us-docker.pkg.dev, elide-fw/tools/jdk17, latest) (repository=elide-dev/v3)
 WARN: No docker auth found - returning (repository=elide-dev/v3)
```

No warnings occur when testing with 32.162.0, although I haven't verified yet if they were just silent failures.

**Comment by rarkins** [comment]
Reproduction forked to https://github.com/renovate-reproductions/17304

**Comment by rarkins** [comment]
We have three locations in the codebase where this warning message is logged. Two of them say it should never happen.

**Comment by rarkins** [comment]
Perhaps relevant? https://github.com/elide-dev/v3/blob/10adee84a1ca9f7c7a47eac0707ad5a5c72bb170/images/qodana-jvm/Dockerfile#L2

**Comment by Churro** [comment]
Since renovate 32.163.0, "_No docker auth found - returning_" is logged with _warn_ instead of _debug_ (see discussion [here](https://github.com/renovatebot/renovate/pull/16554#discussion_r943111713)). I don't think that PR https://github.com/renovatebot/renovate/pull/16554 broke existing functionality but the log level change just brought this to the surface.

I can reproduce this with https://github.com/renovate-reproductions/17304. The warning doesn't occur with calls to https://index.docker.io but only with those going to https://us-docker.pkg.dev. An even more minimal example would be:
```
FROM us-docker.pkg.dev/elide-fw/tools/base:latest@sha256:060b119fb2bf0f65fe5d1927c238516562638bdd2bc581d06de4d0c5443bad72
```

Of the three locations in the codebase, where this message is logged, it always happens in `getManifestResponse()`:
https://github.com/renovatebot/renovate/blob/301f8666d18bc84c94a258ad58a884d560a2848d/lib/modules/datasource/docker/index.ts#L405

The root cause is that `getAuthHeaders()` attempts a GET request to https://us-docker.pkg.dev/v2/, which results in 
```json
{
  "statusCode": 401,
  "body": "{\"errors\":[{\"code\":\"UNAUTHORIZED\",\"message\":\"not authenticated: No credential was supplied.\"}]}\n",
  "headers": {
    "content-type": "application/json",
    "docker-distribution-api-version": "registry/2.0",
    "www-authenticate": "Bearer realm=\"https://us-docker.pkg.dev/v2/token\"",
    "x-content-type-options": "nosniff",
    "x-frame-options": "SAMEORIGIN",
    "x-xss-protection": "0",
    "date": "Sun, 21 Aug 2022 11:05:38 GMT",
    "content-length": "96",
    "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"",
    "connection": "close"
  },
  "authorization": false
}
```

The `www-authenticate` header field lacks the `service` param, leading to: _Invalid realm, testing direct auth_, which won't work as there are no credentials supplied via host rules. 

I was able to verify that PR https://github.com/renovatebot/renovate/pull/17294 fixes this because it relieves the need for a `service` param to be specified. In other words, no more warnings with https://github.com/renovate-reproductions/17304

**Comment by rarkins** [comment]
Thank you for the detailed investigation! I've merged the PR so I can deploy it to the app soon and verify if they all disappear. Perhaps this new warn was what lead to the contributor noticing and submitting the PR :)

**Comment by viceice** [comment]
@rarkins is this fixed in app?

**Comment by rarkins** [comment]
I haven't seen a case of it for 2 days, so will close it as resolved for now :)
