### ISSUE TITLE
Duplicated Dependency inside Dockerfile using ARG as image tag.

### ISSUE THREAD

**Issue by Lowaiz** [renovatebot/renovate#18022]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

32.204.5

### If you're self-hosting Renovate, select which platform you are using.

Gitlab  self-hosted

### If you're self-hosting Renovate, tell us what version of the platform you run.

CE 15.3.3

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

When using a Dockerfile with image in `FROM` including variable like this one:
```
ARG PYTHON_VERS=3.10-slim

FROM python:${PYTHON_VERS} AS builder

...

FROM python:${PYTHON_VERS}

...
```
an when `pinDigest` is activated, the resulting dependencies (see Logs) are applying twice the addition of the hash, as 2 deps are detected with the 2 FROMs, resulting in this updated Dockerfile:

```
ARG PYTHON_VERS=3.10-slim@sha256:6de22c9cf887098265b7614582b00641c0c8c6735af538d0f267d6bb457634f1@sha256:6de22c9cf887098265b7614582b00641c0c8c6735af538d0f267d6bb457634f1

FROM python:${PYTHON_VERS} AS builder

...

FROM python:${PYTHON_VERS}
```

As I explored a little bit the code, I'd say that a deduplication step of deps before the loop at `lib/modules/manager/dockerfile/extract.ts` at line 392 can make the job , or the extractor need to store which dependencies (one's detected by the FROM) are associated to the variable, in order to disable their changes when there is more than one deps associated to this variable

If there is a version update is available (3.10.1-slim to 3.10.7 with the addition of the hash), the bug doesn't occur.

here is the reproduction
https://github.com/Lowaiz/renovate-bug

### Relevant debug logs

<details><summary>Logs</summary>

```
"deps": [
               {
                 "depName": "python",
                 "currentValue": "3.10-slim",
                 "replaceString": "ARG PYTHON_VERS=3.10-slim",
                 "autoReplaceStringTemplate": "ARG PYTHON_VERS={{#if newValue}}{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "stage",
                 "depIndex": 0,
                 "updates": [
                   {
                     "isPinDigest": true,
                     "updateType": "pinDigest",
                     "newValue": "3.10-slim",
                     "newDigest": "sha256:6de22c9cf887098265b7614582b00641c0c8c6735af538d0f267d6bb457634f1",
                     "branchName": "renovate/pindigest-deps-update"
                   }
                 ],
                 "warnings": [],
                 "versioning": "docker",
                 "currentVersion": "3.10",
                 "fixedVersion": "3.10-slim"
               },
               {
                 "depName": "python",
                 "currentValue": "3.10-slim",
                 "replaceString": "ARG PYTHON_VERS=3.10-slim",
                 "autoReplaceStringTemplate": "ARG PYTHON_VERS={{#if newValue}}{{newValue}}{{/if}}{{#if newDigest}}@{{newDigest}}{{/if}}",
                 "datasource": "docker",
                 "depType": "final",
                 "depIndex": 1,
                 "updates": [
                   {
                     "isPinDigest": true,
                     "updateType": "pinDigest",
                     "newValue": "3.10-slim",
                     "newDigest": "sha256:6de22c9cf887098265b7614582b00641c0c8c6735af538d0f267d6bb457634f1",
                     "branchName": "renovate/pindigest-deps-update"
                   }
                 ],
                 "warnings": [],
                 "versioning": "docker",
                 "currentVersion": "3.10",
                 "fixedVersion": "3.10-slim"
               }
             ]
           }
         ]
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by Lowaiz** [comment]
Here is a reproduction:
https://github.com/Lowaiz/renovate-bug/pull/3

**Comment by viceice** [comment]
i don't think duplicate filtering is the right solution.

the second auto-replace isn't working as expected. it should detect the already replaced value.

**Comment by Churro** [comment]
Basically you're right, @viceice. The problem with auto-replace seems to be the following:

- There is no digest set yet, so in both cases: `"replaceString": "ARG PYTHON_VERS=3.10-slim"`
- Expectedly, auto-replace finds `replaceString` another time because with `pinDigests` the `currentValue` isn't updated: https://github.com/renovatebot/renovate/blob/e64739cea5df45b7427ae8a1c1fdedd9cbc190ed/lib/workers/repository/update/branch/auto-replace.ts#L150-L154
- The second time it again replaces `ARG PYTHON_VERS=3.10-slim` with `ARG PYTHON_VERS=3.10-slim@sha256:6de22c9cf887098265b7614582b00641c0c8c6735af538d0f267d6bb457634f1` again, ignoring the digest that is meanwhile there from the first run.
 
To make the second auto-replace work as intended, `replaceString` would need to be "updated" with a meanwhile existing `currentDigest`. I guess this would only work if `extractPackageFile` was called again after the first auto-replace, basically repeating all dep extractions once again.

Please let me know if you have a better idea but for me filtering for duplicates seems like the most reasonable option here. Also, `pinDigests` is kind of a corner case, since there is no `currentValue` to replace but only a digest that gets added.

**Comment by viceice** [comment]
auto-replace should extract again after replace and then it should fail, because the wrong replacement. maybe dockerfile manager is to loose and is ignore the second digest.
it should fail on extraction then.

**Comment by Churro** [comment]
The wrong replacement is supposed to happen but [afterwards](https://github.com/renovatebot/renovate/blob/e64739cea5df45b7427ae8a1c1fdedd9cbc190ed/lib/workers/repository/update/branch/auto-replace.ts#L198) when `doAutoReplace` calls `confirmIfDepUpdated`, extraction should reveal that the digest is now invalid?

Digest plausibility validation is indeed missing in Dockerfile manager but I'm not sure it would solve the problem because in case dependency extraction fails then, `confirmIfDepUpdated()` returns `false`, leading to a `WORKER_FILE_UPDATE_FAILED` exception (last line in `doAutoReplace`) -> As a result, no PR at all. Am I missing something?

**Comment by rarkins** [comment]
Maybe we could include the "full" rest of line in the replaceString? e.g. `"replaceString": "ARG PYTHON_VERS=3.10-slim\n"`

**Comment by rarkins** [comment]
I agree though that ideally we should detect and invalidate this replacement during our extract and detect that it's already updated

**Comment by viceice** [comment]
> Maybe we could include the "full" rest of line in the replaceString? e.g. `"replaceString": "ARG PYTHON_VERS=3.10-slim\n"`

i think that's the best option, so next auto-replace never matches again.

**Comment by rarkins** [comment]
Maybe even just one character is all we need (Eg can be space or newline)
