### ISSUE TITLE
Gradle variable ordering breaks detected dependencies

### ISSUE THREAD

**Issue by siegenthalerroger** [renovatebot/renovate#18317]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

We have a multi-project gradle build system where the versions are defined in the root level project. Apparently the detection of dependencies and their updates depends on their ordering.

For example the following excerpt out of the root-level `build.gradle` **works** and resulted in a PR and branch being created for the openApi package:
```
subprojects {

    ext {
        springBootVersion = '2.7.1' 
        openApiVersion = '1.5.13'
        apacheVersion = '3.12.0'
        redhatVersion = '00001'
        apacheCommonsLangVersion = "${apacheVersion}.redhat-${redhatVersion}"
    }
```

Merely changing the order of the last two items (to better match our internal layout) resulted in the branch being deleted and the PR closed.
```
subprojects {

    ext {
        springBootVersion = '2.7.1'
        apacheVersion = '3.12.0'
        redhatVersion = '00001'
        apacheCommonsLangVersion = "${apacheVersion}.redhat-${redhatVersion}"
        openApiVersion = '1.5.13'
    }
```

**Reproduction Repository**: https://github.com/siegenthalerroger/renovate-gradle-variable-interpolate-reproduction
**Change commit**: https://github.com/siegenthalerroger/renovate-gradle-variable-interpolate-reproduction/commit/edadcea573b7b1f4b484f27adf9348c4f009ed88

### Relevant debug logs

<details><summary>Logs</summary>

```
DEBUG: Found PR #6
DEBUG: branch.isModified(): using git to calculate
DEBUG: branch.isModified() = false
DEBUG: setCachedModifiedResult(): Branch cache not present
INFO: Autoclosing PR
{
  "branchName": "renovate/openapiversion",
  "prNo": 6,
  "prTitle": "Update dependency org.springdoc:springdoc-openapi-ui to v1.6.11"
}
DEBUG: updatePr(6, Update dependency org.springdoc:springdoc-openapi-ui to v1.6.11 - autoclosed, body)
DEBUG: PR updated
{
  "pr": 6
}
DEBUG: Deleted remote branch
{
  "branchName": "renovate/openapiversion"
}
DEBUG: No local branch to delete
{
  "branchName": "renovate/openapiversion"
}
DEBUG: Cleaning up Renovate refs: refs/renovate/*
```

</details>

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by Churro** [comment]
Looks to me like a real issue in the current Gradle parser.

The whole problem can be narrowed down to:
```groovy
apacheCommonsLangVersion = "${apacheVersion}"
openApiVersion = '1.5.13'

implementation("org.springdoc:springdoc-openapi-ui:${openApiVersion}")
```

What happens:

- First, `apacheCommonsLangVersion = "${apacheVersion}"` is matched: https://github.com/renovatebot/renovate/blob/34e0a3cb16028d7bec8afe7d321121a760a3fdbf/lib/modules/manager/gradle/parser.ts#L498-L502
- Interpolation fails (or it is no dependency string), `processDepInterpolation` returns null
- With a `result == null`, `tryMatch` doesn't return but goes through the rest of matchers. No other matcher kicks in here since the matcher itself was the correct one (just handling didn't work), so it removes the next token from the array: https://github.com/renovatebot/renovate/blob/34e0a3cb16028d7bec8afe7d321121a760a3fdbf/lib/modules/manager/gradle/parser.ts#L1121-L1126
- The removed token is `{ "type": "word", "offset": 47, "value": "openApiVersion" }`, which means in the next `tryMatch` cycle it is missing and won't be matched by the assignment matcher: https://github.com/renovatebot/renovate/blob/34e0a3cb16028d7bec8afe7d321121a760a3fdbf/lib/modules/manager/gradle/parser.ts#L464

One possible solution for this is to make `processDepInterpolation` return something other than null to express that the matcher was the correct one and no other should be tried.

**Comment by siegenthalerroger** [comment]
Thanks for the in depth analysis. I did think it would be something to this end as it only happened when a more "complex" case came first in the file. Great to see a PR so quickly for the fix
