### ISSUE TITLE
Validate peerDependencies

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#1864]
#### This is a:

* [ ] Bug report (non-security related)
* [x] Feature request
* [ ] I'm not sure which of those it is

#### Please describe the issue:

Ideally Renovate should check if an upgrade satisfies peerDependencies requirements. I'm not sure if the best behaviour should be to (a) dismiss an upgrade if it does not satisfy, or (b) raise it and warn to the user, or (c) make that configurable.

One approach to this would be to grep stdout of npm and yarn to look for such warnings. However, this is complicated by the fact that (a) a lot of repositories seem to have existing peerDependencies warnings, and (b) even yarn seems to have problems with false negative warnings about peerDependencies.

It would seem logical though that if the current base branch has passing peerDependencies, then we probably don't want to upgrade a dependency that would cause there to be warnings.

**Comment by rarkins** [comment]
@voxpelli have you had any chance to think about this one more?

I was also thinking that it's possible that some Renovate branches might *never* satisfy peer dependencies even if left forever, so "dismiss an upgrade if it does not satisfy" would not be a good solution unless there is a timeout/failsafe to warn the user eventually. I think as a first solution we want to raise the PR normally but add a `renovate/peer-dependencies` status check with value "failed".

**Comment by voxpelli** [comment]
I totally think this should be configurable.

Some modules are fairly strict with their `peerDependencies`, like eg: https://github.com/domenic/sinon-chai/pull/127/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R32 That's not because the module doesn't support the future versions, but just because they want to signal that it has not been tested.

It would also be different depending on whether it's a major or non-major difference between the required peer dependency and the included peer dependency – major upgrades can like in the mentioned Sinon case be almost fully backwards compatible, but in other cases (Hapi comes to mind) it can at times be dramatic refactorings with very major API changes (I myself sometimes long for a version number above `major` in SemVer – so that the major upgrades could be split between `very-major` and `not-very-major` – eg. `1.1.0.0` – as it is very hard to tell _how_ breaking a major change can be and whether it is possible to try ones luck with a blind upgrade or not)

So: If one could configure it on a module by module bases, eg. point out that `sinon-chai` out of date peerDependencies should be considered a warning, eg. an `eslint-config-standard` out of date peerDependencies should be considered an error.

By default I think it should error on all non-satisfied peerDepedencies, but have it be configurable on both module level and globally whether it should be an error or just a warning

A `renovate/peer-dependencies` status check sounds 👍

**Comment by rarkins** [comment]
After more time to think, I would prefer that we raise upgrades and allow the package manager to fail the branch and user to decide what to do (including ignoring the upgrade or fixing it). If someone still needs this then please create a new feature request with a very concrete proposal for how this could be handled.
