### ISSUE TITLE
GitHub Actions should refer to releases, not tags

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19033]
### How are you running Renovate?

Mend Renovate hosted app on github.com

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

It seems that Renovate should use github releases as the source of truth, not github tags.

After the discussion started in https://github.com/slsa-framework/slsa-github-generator/issues/1250 I found https://docs.github.com/en/actions/creating-actions/releasing-and-maintaining-actions which seems to talk of releases not tags.

When I tried this simple change locally:
- Correct looking PR: https://github.com/renovate-reproductions/hardening/pull/1/files
- Incorrect digest pin PR: https://github.com/renovate-reproductions/hardening/pull/5
- Correct autoclosed prerelease PR: https://github.com/renovate-reproductions/hardening/pull/3

### Relevant debug logs

None

### Have you created a minimal reproduction repository?

I have linked to a minimal reproduction repository in the bug description

**Comment by rarkins** [comment]
@zharinov could you look into this as you touched the codebase recently? We need to figure out why there's an incorrect pin PR before we make this change.

**Comment by JamieMagee** [comment]
GitHub actions uses git refs, not GitHub releases. From [the documentation][1]:

> The location and version of a reusable workflow file to run as a job. Use one of the following syntaxes:
>
> - `{owner}/{repo}/.github/workflows/{filename}@{ref}` for reusable workflows in public repositories.
> - `./.github/workflows/{filename}` for reusable workflows in the same repository.
>
> **`{ref}` can be a SHA, a release tag, or a branch name.**

GitHub releases are unrelated to GitHub Actions. GitHub releases are required to publish an action to the marketplace, but the marketplace is only for discoverability.

The issue is the `slsa-github-generator` expects there to be an equivalent GitHub release:

https://github.com/slsa-framework/slsa-github-generator/blob/800ff15cbd48bfceacd65fb8e8c5f129071b841d/.github/actions/generate-builder/builder-fetch.sh#L65

[1]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iduses

**Comment by rarkins** [comment]
OK let me close this as mistaken and we pursue an alternative solution
