### ISSUE TITLE
On-demand config migration PRs using Dashboard

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#19783]
### What would you like Renovate to be able to do?

Add a checkbox to the dependency dashboard which allows users to open a migration PR on demand

### If you have any ideas on how this should be implemented, please tell us here.

Remove the log warning display in dashboard (so that this information is not duplicated).

Display the message prominently that config migration is required (maybe with a learn more link).

Have a checkbox allowing users to open the config migration PR.

Not sure what to do if they *uncheck* the checkbox after the PR is created though. Maybe keep it? They can close it manually if they really want.

### Is this a feature you are interested in implementing yourself?

No

**Comment by HonkingGoose** [comment]
> Not sure what to do if they _uncheck_ the checkbox after the PR is created though. Maybe keep it? They can close it manually if they really want.

I think we can keep the default behavior:

1. Select PR via Dependency Dashboard
1. Don't want the PR anymore: close it yourself

If you want to do the "close PR if checkbox is unchecked" thing, there's a possible edgecase:
Renovate de-selects the checkboxes after it finishes the requested run on the repository. So wouldn't Renovate then close the config migration PR on the _next_ run?

**Comment by rarkins** [comment]
Actually, if we detect that the PR is open we should remove the message and the checkbox from the dashboard (or perhaps replace it with a message/link to the PR)

**Comment by HonkingGoose** [comment]
I vote "replace it with a message/link to the PR" then.

The Dependency Dashboard should always show all pending stuff, removing the message and checkbox goes against that idea.

**Comment by HonkingGoose** [comment]
> Actually, if we detect that the PR is open we should remove the message and the checkbox from the dashboard (or perhaps replace it with a message/link to the PR)

How about moving the checkbox item to different sections on the Dependency Dashboard? Like this:

1. Renovate detects config migration is needed,
2. Renovate creates a new checkbox for the config migration on the Dependency Dashboard in the **Pending approval** section,
3. User clicks the config migration checkbox,
4. Renovate creates the PR,
5. Once PR is open: Renovate moves the checkbox to the **Open** section.

What happens next depends on the user:

- User _merges_ config PR: Renovate drops the checkbox from the Dependency Dashboard -> done.
- User _closes_ config PR: Renovate moves the checkbox to the **Ignored or Blocked** section -> done.

If user wants new config migration PR, after ignoring one: user renames old PR to something else, and Renovate creates a new PR.

**Comment by HonkingGoose** [comment]
You're right, let's put the config migration in it own section at the top.

**Comment by HonkingGoose** [comment]
## Summary/TLDR

- Users are getting confused by having old names in their Renovate config.
- Help me help others by adding the config migration button to Dependency Dashboard.
- Warn about experimental state of config migration PRs in Dependency Dashboard, and in the config migration PR.
- Maybe include this feature in upcoming `v38`? And explain more in the developer commentary and changelog.
- Maybe bump the priority to high on this issue, and on #16359?

## Outdated Renovate config in many repositories causing confusion

I'm seeing a lot of repositories using old terms like:

| Common old terms | New term |
| --- | --- |
| `config:base` | `config:recommended` |
| `stabilityDays` | `minimumReleaseAge` | 

This causes users to get confused when they search the docs, as the old name is low in the search ranking on the docs site.

### "Get fresh config" button helps me help others

A button to get a fresh configuration file would make it easier for me to help others. As then I can say: "Select the checkbox to get the updated terms", instead of having to explain in detail _what_ changed, _why_, and link to the Renovate major release notes. :smile:

## Warn about experimental state in checkbox text and config migration PR body

We should explain that the feature is experimental, and explain the likely "bugs"/"bad behavior", like:

- Renovate may delete comments
- Renovate may re-order config items
- Renovate may not follow Prettier linter rules

This way users with a simple config can try it out, and get a good migration. User with lots of comments or special linter rules can try it too, and know what they're in for: a bit of manual fix up.

## Maybe include this feature in the upcoming `v38` release?

With a major release, we also add a developer notes/commentary. That would be a nice visible place to tell users about this feature, and warn about the limitations.

## Maybe bump the priority of this, and related issue to high?

This issue is currently at medium priority, and the related issue is at that level too:

- #16359

I think we should prioritize this work more than we do now, so bumping it to _high_ priority. 

Especially as we're going to make more changes in `v38` and in future major releases. The longer we wait, the more the names in the user's configuration will drift from the names in the Renovate docs.

**Comment by RahulGautamSingh** [comment]
I want to re-confirm the behaviour of the checkbox as outline by @HonkingGoose in [this](https://github.com/renovatebot/renovate/issues/19783#issuecomment-1512624825) comment

1. We only add the checkbox to the DD issue if migration is needed.
> say we add the checkbox when migration was needed but user changed the config manually and a migration is not needed anymore we remove the checkbox

2. We add a checkbox at the top of the DD issue

3. When user checks the checkbox:  we create a migration PR & replace the checkbox with link to the PR

4. When migration PR is merged/closed: if migration is needed add the checkbox to DD issue, else nothing

5. Add any warning/cautions regarding migration in the migration PR itself. In the DD issue only add a checkbox or a link to the PR with some information text


Some implementation related findings:

We update/create the DD issue before finalizing the repo. But we handle configMigration while finalizing the repo. So we might need to move `ensureDependencyDahboard` fn within finalize the repo oe do config migration before ensuring DD issue.

**Comment by RahulGautamSingh** [comment]
Also, we should change the `configMIgration` value from a boolean to an enum type 'auto', 'disabled', 'enabled' ... 
In auto mode we create the checkbox if necessary
In enabled mode we directly create migration prs
In disabled mode we neither create migration prs nor the checkboxes

**Comment by rarkins** [comment]
Sorry, I'm rethinking the config migration enum part and maybe we should close https://github.com/renovatebot/renovate/pull/30000. Perhaps we should leave it as boolean:

- false: show a checkbox in the Dashboard, if Dashboard is enabled
- true: create a PR immediately, do not wait for dashboard approval

I don't think I want people to be able to suppress migration completely. Having a short note in the dashboard seems reasonable.

**Comment by RahulGautamSingh** [comment]
If a closed migration pr exists we do not add the checkbox or the link to the PR right?

**Comment by RahulGautamSingh** [comment]
Should we change the message to indicate the a closed pr exists and they need to rename it so that the bot can create a new PR?

**Comment by rarkins** [comment]
I think we can create a new one instead

**Comment by RahulGautamSingh** [comment]
> I think we can create a new one instead

Okay. I want to confirm which of these 2 behaviour we want in case `configMigration:enabled`  and closed PR exists

- Should we add a comment on the closed PR like we currently do, asking them to rename the closed pr if they want a fresh one
Or,
- Should we add a checkbox

**Comment by rarkins** [comment]
Add a checkbox
