### ISSUE TITLE
Suggests to upgrade commons-io from v2.11.0 to older v20030203.000550

### ISSUE THREAD

**Issue by janhoy** [renovatebot/renovate#19934]
### How are you running Renovate?

Self-hosted

### If you're self-hosting Renovate, tell us what version of Renovate you run.

latest

### If you're self-hosting Renovate, select which platform you are using.

None

### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

See https://github.com/cominvent/solr-playground/pull/62 for the PR (ran from cmdline).

The Apache Commons-IO project released an artifact versioned with the iso-date `20030203.000550` back in 2005, see https://mvnrepository.com/artifact/commons-io/commons-io but changed to semantic versioning. However since the gradle version parser believes that everything is a semantic version, it believes that it should upgrade from v11 to v20030203.

This is obviously wrong, just by looking at the release date.

I see that there is a feature to override versioning on a per-source and per-package basis, which could perhaps be a workaround, have not tried. But can we also harden Renovate's ootb experience? Could the semver parser have a limit for how large the major-version can be, say `10000` and discard versions from maven larger than that? It would fix semver + ISO-date mix like this.

### Relevant debug logs

<details><summary>Logs</summary>

```
(No logs)
```

</details>

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by rarkins** [comment]
1. There's a workarounds preset which contains similar workarounds/fixes as this
2. Maybe we could default to comparing release dates if the major version difference is >2?

A fully flexible way would be to have an option similar to versioning, rangeStrategy, etc. It could be called something like `sortByDate` and default to `auto`, with options `enabled` and `disabled`. `auto` could mean that if the major difference was >2 then we make sure the dates are newer, otherwise we use regular versioning sorting

**Comment by janhoy** [comment]
I worked around it with this config
```json
  "packageRules": [
    {
      "matchDatasources": ["maven"],
      "matchPackageNames": ["commons-collections:commons-collections", "commons-io:commons-io"],
      "versioning": "regex:^(?<major>\\d{1,4})\\.(?<minor>\\d+)(\\.(?<patch>\\d+))?$"
    }
  ]
```
