### ISSUE TITLE
Remove string interpolations from all logger.warn and logger.error calls

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#20922]
### Describe the proposed change(s).

We want to have a finite set of warn and error messages so that they can be grouped and counted accurately by back-end systems.

Here's some quick examples I found (there may be more):

![image](https://user-images.githubusercontent.com/6311784/224948167-0c55c3f2-a7c7-4860-ab24-1b42db7a43b7.png)

If in doubt on any, go ahead and make the change in the PR but add a comment asking for feedback

**Comment by RahulGautamSingh** [comment]
IIRC this is a duplicate. Lemme check

**Comment by rarkins** [comment]
Let's do this step first, keep them separate

**Comment by JamieMagee** [comment]
For tracking events I usually define the interface to accept a union of all the events by name. So if I am building a query for something in a dashboard I can centrally see what all possible events are in a single spot instead of trawling the codebase.

For example
```ts
type Event = 
  | 'StartTime'
  | 'EndTime'
  | 'WidgetsGenerated';

interface Logger {
  trackEvent(event: Event, properties: Record<string, any>);
}

logger.trackEvent('StartTime', {value: ...});
```

Might also be applicable for logs if you want to manage them centrally?
