### ISSUE TITLE
Improve minimumReleaseAge documentation and link to from renovate/stability-days builds

### ISSUE THREAD

**Issue by setchy** [renovatebot/renovate#21013]
### What would you like Renovate to be able to do?

Create a dedicated documentation page to explain how **Stability Days** works.

Then use this new page as the hyperlink for the `renovate/stability-days` build, like those below

![image](https://user-images.githubusercontent.com/386277/225973577-2e109f04-6d7d-4736-a884-e09ac70765ca.png)

### If you have any ideas on how this should be implemented, please tell us here.

create new docs page and update builds to reference it

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by setchy** [comment]
Based off this discussion: https://github.com/renovatebot/renovate/discussions/21008

**Comment by setchy** [comment]
And this, more thoroughly documented discussion - https://github.com/renovatebot/renovate/discussions/14948

**Comment by HonkingGoose** [comment]
> create new docs page and update builds to reference it

We already have some `stabilityDays` config option docs [^docs]. We could:

- Trim the config option docs for `stabilityDays` so it only shows "basic configuration"
- Create new  "Key concepts, stability days" page
- Move the full explanation to the new page

[^docs]: [`stabilityDays` config option docs](https://docs.renovatebot.com/configuration-options/#stabilitydays)

**Comment by rarkins** [comment]
Also keep in mind we would like to rename `stabilityDays`: https://github.com/renovatebot/renovate/issues/12914

So ideally don't name the file like "stability-days.md" so that its content can change later if necessary

**Comment by setchy** [comment]
I like the sound of `minimumReleaseAge`

**Comment by HonkingGoose** [comment]
## What we have now:

- `stabilityDays` is now called `minimumReleaseAge`
- [Renovate docs for `minimumReleaseAge`](https://docs.renovatebot.com/configuration-options/#minimumreleaseage)

## The original request of this issue was to:

> Create a dedicated documentation page to explain how Stability Days works.

## Do we still want/need a separate page?

The `minimumReleaseAge` config option docs explain:

- That it was renamed from `stabilityDays`
- Which conditions need to be met for Renovate to check the set duration
- That Renovate waits for the set duration to pass for each separate version
- That you can use selective-scheduling, and links to the docs for that concept
- That Renovate adds a _pending_ status check, and replaces it with a _passing_ check when the `minimumReleaseAge` is met
- That some datasources don't have a release timestamp, which means the feature does not work. Or that Renovate does not support a release timestamp for a datasource yet
- Note for Maven users when Maven source has unreliable `last-modified` headers
- Note admonition that configuring this option means you get a new status check: `renovate/stability-days`

And it covers some uses:

- Suppress branch/PR creation for X days
- Prevent holding broken npm packages
- Await X time duration before Automerging

## Discussion

It seems like we have a good starting point with the current `minimumReleaseAge` config option docs. @setchy can you take a look at what we have now, and explain what you think is missing?

**Comment by setchy** [comment]
@HonkingGoose well summarized, great to see the progress on this.

I had a quick look at my use-cases and noticed two items

1.  Bitbucket Pipeline build (for branch status) is linked to https://docs.renovatebot.com/, not https://docs.renovatebot.com/configuration-options/#minimumreleaseage.  This is true for all platforms. Raised https://github.com/renovatebot/renovate/pull/28378 to address

2. branch name defaults to `renovate/stability-days` - but looks to be configurable via https://docs.renovatebot.com/configuration-options/#statuschecknames

**Comment by HonkingGoose** [comment]
> 2. branch name defaults to `renovate/stability-days` - but looks to be configurable via https://docs.renovatebot.com/configuration-options/#statuschecknames

We have an issue to _rename_ the status check, that seems related?

- #21442

The rename issue is blocked by this one:

- #19980
