### ISSUE TITLE
Support GitHub-hosted presets

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2102]
Allow users to also host their presets on GitHub instead of npm. 

Namespace is “github:owner/repo”. Shorthand “github:owner” means “github:owner/renovate-config”.

Config should be in `package.json` for now just like in npm modules but maybe later we’ll find a less npm-specific approach too. 

No versioning - we use default branch only.

Should use same github token as for the current repo

**Comment by destroyerofbuilds** [comment]
> Config should be in package.json for now just like in npm modules but maybe later we’ll find a less npm-specific approach too.

What's the limitation of using `renovate.json`?

**Comment by rarkins** [comment]
`renovate.json` would work ok if there is just one preset inside, but it's not structured in a way to support multiple. Maybe though it can still be supported, with the disclaimer that only one is supported.

**Comment by hbetts** [comment]
I guess `renovate-config` can't be used since it's a separate top-level property from the `renovate` property that can be used in `package.json` for specifying a project's Renovate configuration.

I was thinking you could have a `renovate-config` in `renovate.json`, but `renovate-config` isn't a valid property in a Renovate config.

**Comment by felixfbecker** [comment]
I don't think multiple presets are a concern for one file. None of ESLint, TSLint etc support multiple presets in one file. If you want to have multiple presets, they could just be in their own repos
