### ISSUE TITLE
If semantic release comments on a PR I get a 

### ISSUE THREAD

**Issue by schalkneethling** [renovatebot/renovate#2115]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
If semantic release comments on a bug(https://github.com/mdn/bob/pull/60#issuecomment-396282190) post merge, I get an email from Renovate:

```
As this PR has been edited, Renovate will stop updating it in order to not cause any conflicts or other problems. If you wish to abandon your edits and have Renovate recreate this PR then you should rename this PR and then close it.
```

**To Reproduce**
see https://github.com/mdn/bob/pull/60#issuecomment-396282190

**Expected behavior**
If a PR has already been merged and then gets a comment, Renovate should ignore it.

**Comment by rarkins** [comment]
Did you delete the Renovate comment from that linked PR? I don’t see it

**Comment by schalkneethling** [comment]
@rarkins No, I also found it weird not to see it on the PR. It came from notifications . at . github.com and there was also a CC address state_change . at . noreply.github.com

**Comment by rarkins** [comment]
GitHub has a partial outage right now so that may explain it. I also see it sometimes in this repo too

**Comment by rarkins** [comment]
It’s not meant to be caused by comments btw - it happens if it detects any extra commits in a branch it thinks is open. I think it might happen when you merge a branch after Renovate is in the process of updating it. Eg if you merge more than one PR closely together because Renovate starts running soon after it detects the first merge
