### ISSUE TITLE
Move from `gh-got` to `@octokit/rest` for GitHub interaction

### ISSUE THREAD

**Issue by Aghassi** [renovatebot/renovate#2179]
**What would you like Renovate to be able to do?**
I believe that most of the GitHub logic can be handled by `@octokit/rest` as oppose to the `gh-got` method. `@octokit` is the official package, and will make interactions way easier. It is also less error prone. Right now, if a link is bad, or some condition doesn't meet the exact url, the app will crash.

**Describe the solution you'd like**
Move to `@octokit/rest`, though that may take some doing

**Describe alternatives you've considered**
Maybe contrib back to `gh-got` to fix their link concatenation. It just seems like a roundabout way of handling GitHub interaction.

**Additional context**
If the `GITHUB_URL` passed in does not have a trailing `/` the app will crash with `401` because `gh-got` (I think) concats the endpiont with the URL. It does zero checking.

**Comment by hbetts** [comment]
@Aghassi migrating away from `gh-got` is being handled in #2105

A wrapper is being built on top of `got` for pagination support (along other features).

> Maybe contrib back to gh-got to fix their link concatenation. It just seems like a roundabout way of handling GitHub interaction.

I would love to see this happen. It seems like a pretty minor issue that could be addressed quickly in `gl-got` and `gh-got`.

**Comment by rarkins** [comment]
Actually, the bad concatenation was my fault, not `gh-got`'s. They have a simple massage for it: https://github.com/sindresorhus/gh-got/blob/master/index.js#L15 however I had code that was doing dumb JS string concatenation before passing to gh-got.

Counterintuitively, many times I *prefer* a crash or visible problem when the unexpected happens, because that's how we notice it and fix it. For example just a day or so ago the Docker registry was down for 2-3 hours and it resulted in a lot of autoclosed Docker upgrade PRs because we were too keen to "swallow" errors instead of passing them up and letting the app abort the renovation instead of apply an invalid one. So the result of that was to deliberately pass up errors instead of try/catching them at the API query level.

Also as the number of platform types we connect to increases (e.g. github, gitlab, vsts, npm, artifactory, docker, pypi, nuget, packagist, etc) it actually gets painful to adapt things like authentication, pagination and retries to each library, even though the abstractions they provide seem convenient at other times. For this reason we *will* soon remove `gh-got` and the associated `GITHUB_ENDPOINT` AND `GITHUB_TOKEN` "hacks" but replace it instead with our own API wrapper library based on `got` and attempt to stay away from platform-specific REST wrappers in future.
