### ISSUE TITLE
Renovate bot is triggering changes every 5 minutes when the configuration is set to monthly

### ISSUE THREAD

**Issue by joseSantacruz** [renovatebot/renovate#2196]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Renovate bot is triggering changes every 5 minutes when the configuration is set to monthly.

**To Reproduce**

1.  Create repository with any name
2.  Configure with the preset monthly

**Expected behavior**
Only scan the repo once in the month.

**Additional context**
This changes are causing issues on my CI.

**Comment by rarkins** [comment]
Renovate doesn’t even run every 5 minutes, so something is not right here. Need more details to be able to look into it.

**Comment by rarkins** [comment]
For example please describe what you mean by “changes”

**Comment by rarkins** [comment]
After taking a look, Renovate seems to have been checking hourly. Perhaps you get the perception of every 5 minutes due to the number of repositories.

It sounds like you probably want to set [updateNotScheduled](https://renovatebot.com/docs/configuration-options/#updatenotscheduled) to `false` in your config, so that existing branches are never updated outside of your schedule, even if they need updating. You can read more about it at the link.

**Comment by joseSantacruz** [comment]
yes I think that is the problem, I put that setting let me check if that fixes the issue
