### ISSUE TITLE
Cannot enable renovate for invoiced customers

### ISSUE THREAD

**Issue by JustinBeckwith** [renovatebot/renovate#2247]
We're trying to enable renovateapp through the GitHub marketplace for the GoogleCloudPlatform org.  Sadly, we end up with this:
![image](https://user-images.githubusercontent.com/534619/42611123-6c511b96-8549-11e8-837e-344aa6f002a7.png)

We can't seem to figure out a way to activate the service for invoiced orgs :(  Any guidance?  We're really enjoying renovate in our other open source orgs. 

Thanks!

**Comment by JustinBeckwith** [comment]
cc @theacodes @ofrobots

**Comment by rarkins** [comment]
Bad news is that this is a GitHub billing system limitation that I don't expect they will address due to the acquisition. It would require technical and human work to generate extra invoices that I don't think they want to do.

Good news is that selecting the "Open Source" plan for Renovate is actually not required anyway. If the app is already installed via https://github.com/apps/renovate then there's nothing more to do and there is no plan "enforcement" for public repositories. The Open Source plan is just there for people who browse via the Marketplace and wonder if there's a free "plan" and for anyone not already signed up it then triggers the app installation afterwards. I think in your case the "GoogleCloudPlatform" account is already installed directly via the app so nothing more to do.

If you ever have *private* repositories that you need added, then a plan is required and this does cause a problem for Invoiced organisations. In that case we support direct payment via credit card or invoice/bank transfer.

**Comment by rarkins** [comment]
@JustinBeckwith I’m curious about what led you to try enabling a plan - were you just trying to configure which repositories are enabled, or something else prompted you? GitHub’s UI can be a bit frustrating and I’ve asked them previously to provide helpful error messages for invoiced customers in particular but so far I haven’t noticed any changes.

**Comment by JustinBeckwith** [comment]
@theacodes @tswast @juliaferraioli - I am having a little trouble here :) We would very much like to get renovate enabled in the org for our node.js repositories.  Can someone take a look?

**Comment by JustinBeckwith** [comment]
cc @ofrobots

**Comment by tswast** [comment]
Looks like it is installed on the GCP org, so we should be good to go. We just need to select which repositories you want to enable it on.

**Comment by rarkins** [comment]
Go to https://github.com/apps/renovate

Click on Configure:
![image](https://user-images.githubusercontent.com/6311784/42783591-c53cbeac-894c-11e8-8c60-513bfe2f8dc1.png)

Look for the relevant org on the next page, e.g. here you see my personal account + an org account "renovate-mirrors":
![image](https://user-images.githubusercontent.com/6311784/42783636-e33787c0-894c-11e8-9074-935b2dc606d6.png)

If you *don't* see the relevant org account here, I'm pretty sure it means you don't have the permissions necessary and someone else needs to do it. That's a GitHub thing, not a Renovate thing.

You will then get to a page like `https://github.com/organizations/<your-org>/settings/installations/999999`. Scroll to the bottom.

Now you should see something like this:
![image](https://user-images.githubusercontent.com/6311784/42783746-25edea28-894d-11e8-9ce1-0fcae6f584da.png)

Click on "Select repositories" and add the ones you want. Or go nuts and click "All repositories".

**Comment by MiguelMadero** [comment]
> In that case we support direct payment via credit card or invoice/bank transfer.

By direct, do you mean, directly through renovate? How can we do that?

**Comment by rarkins** [comment]
Please email support@renovatebot.com with your details and we’ll let you know next steps
