### ISSUE TITLE
Python compatibility

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2248]
Detect (a) version of Python in use, and (b) of any updates are incompatible.

**Comment by hbetts** [comment]
@rarkins are you assuming a `pipenv`-managed project, or a `requirements.txt` project?

I ask because `pipenv` has a [field for Python compatibility](https://docs.pipenv.org/basics/#specifying-versions-of-python). I assume they use that field when [checking for outdated dependencies](https://docs.pipenv.org/basics/#example-pipenv-upgrade-workflow).

**Comment by rarkins** [comment]
I’m just thinking of requirements.txt for now but of course `pipenv` is on the radar

**Comment by rarkins** [comment]
Add a languageRestriction option which is datasource-specific. If someone configures it then it will be used in lookups
