### ISSUE TITLE
NuGet: Support versions specified as msbuild properties

### ISSUE THREAD

**Issue by jaredcnance** [renovatebot/renovate#2266]
**What would you like Renovate to be able to do?**
Evaluate version from csproj when specified as msbuild property.

Example:

```xml
<PackageReference Include="Microsoft.AspNetCore" Version="$(AspNetCoreVersion)" />
```

**Describe the solution you'd like**
I'm not sure what the best solution is however, I did take a stab at this a while back and just didn't have the time to keep it going. My approach looked something like:

- [Clone the repository](https://github.com/jaredcnance/dotnet-status/blob/722d935e156b69a5005994f5b2f9de7d8d1482b6/core/Services/RepositoryResultEvaluator.cs#L52)
- [Use NuGet to directly restore the solution](https://github.com/jaredcnance/dotnet-status/blob/722d935e156b69a5005994f5b2f9de7d8d1482b6/core/Services/NuGet/RestoreService.cs#L24);  [producing a dependency graph file](https://github.com/jaredcnance/dotnet-status/blob/722d935e156b69a5005994f5b2f9de7d8d1482b6/core/appsettings.json#L6-L10)
- [Read the dependency graph using NuGet's .Net SDK](https://github.com/jaredcnance/dotnet-status/blob/722d935e156b69a5005994f5b2f9de7d8d1482b6/core/Services/NuGet/DependencyGraphService.cs#L23)
  - [NuGet.ProjectModel](https://www.nuget.org/packages/NuGet.ProjectModel/)
  - [NuGet.LibraryModel](https://www.nuget.org/packages/NuGet.LibraryModel/)

**Describe alternatives you've considered**
I originally thought that parsing the project files would be enough, however there are too many different ways dependencies can be defined. My conclusion was that you would have to actually let msbuild do a full restore. You may also be able to perform a [design time build](https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md) but I haven't done enough research on that approach.

**Additional context**
Since nuget dependency resolution was completely rolled into msbuild and csproj files, it has become common to use [msbuild properties](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-properties) to specify versions. This allows you to mitigate some of the challenges associated with managing common dependencies across several projects in a solution. Unfortunately, this means you can't simply parse an XML file to get the version. These properties could be set using a:

- [Directory.Build.props](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build#directorybuildprops-and-directorybuildtargets) file
- *.props file plus an [`<Import>`](https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild) element in the csproj
- It is also possible to declare common dependencies using these files as well. So, a `<PackageReference>` could be defined outside the csproj file.
- [Command line parameters](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference)

Notable examples of projects doing this:

- All the ASP.Net Core Projects (SignalR, MVC, EntityFramework, etc.)
   - [dependencies.props file declares version](https://github.com/aspnet/SignalR/blob/2d4fb0af6fd2ef2e3a059a2a15a56484d8800d35/build/dependencies.props#L6)
   - [gets imported into Directory.Build.props](https://github.com/aspnet/SignalR/blob/2d4fb0af6fd2ef2e3a059a2a15a56484d8800d35/Directory.Build.props#L7)
   - [referenced in csproj](https://github.com/aspnet/SignalR/blob/2d4fb0af6fd2ef2e3a059a2a15a56484d8800d35/benchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks/Microsoft.AspNetCore.SignalR.Microbenchmarks.csproj#L25)
- [dotnet cli](https://github.com/dotnet/cli/blob/master/build/DependencyVersions.props)
- [perfview](https://github.com/Microsoft/perfview/blob/dcece4936e6c8c60073eddd2213b00bca83aab69/src/Directory.Build.props#L31)
- [Dapper](https://github.com/StackExchange/Dapper/blob/cd751c21f67348a1327d1073b716f99563d44322/Directory.build.props#L30)
- [refit](https://github.com/reactiveui/refit/blob/ee7a8f0797f53be9f797b1d34a0e15ed208f2f35/Directory.build.props#L24)
- [JsonApiDotNetCore](https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/Directory.Build.props)
- And many more. In fact this feature tends to make the **most** sense for monolithic repos and application projects which have not been included in this list.

**Comment by rarkins** [comment]
Hi @jaredcnance, thanks for the very detailed feature request. 

On one hand, I agree with you that reproducing the algorithm for determining versions seems to be difficult. On the other hand, I hope we don't need to fully *build* a project just to check its dependencies?

I'm aware that there is some .NET support for Linux, but not of the details. Can you verify if the steps you describe above would be compatible with running on a Linux server such as Renovate normally uses?

Once we have "Read the dependency graph using NuGet's .Net SDK", what would that give us? Would that just allow us to know a list of dependencies and versions currently in use, or would it be a list of upgrades too? For determining upgrades, can we do it simply using our own nuget lookup, or is there more complexity to the lookup algorithm?

Cc: @samneirinck @tomkerkhove

**Comment by jaredcnance** [comment]
@rarkins no problem! I think this is a much needed tool for the dotnet community. You shouldn't _have_ to fully build the project, but run:
```
dotnet msbuild /t:GenerateRestoreGraphFile /p:RestoreGraphOutputPath=out.dg
``` 

command which will run the target that builds the dependency graph but doesn't download the packages (think `npm install` without the downloading part). As I side note I believe this is possible without executing and external process and using the nuget api directly, but I'm not familiar with the details.

This is cross-platform for projects that target .Net Core and .Net Standard but not projects that target Full-Framework (Windows only) — as far as I'm aware.  It _may_ still be possible to generate the dependency graph even for Windows only projects since resolution _should_ be platform agnostic for the new SDK-style (Visual Studio 2017) projects.

Regarding your second question it will provide you a map of dependencies that are resolved for each framework target. For example, I could have a multi-targeted projects that has different dependencies for linux than windows. One example that comes to mind is [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/) (the predominant JSON parsing lib — see image below).

It will not include a list of upgrades (although at one time there was talk of supporting this). Once you have the list of packages you can use the nuget REST api to lookup the versions.
 
Another thing that makes this a bit more complicated is you can target multiple feeds. I could target NuGet.org, MyGet, a local feed, or any other nuget feed. You do get references to these feed as source URLs that [you can iterate over](https://github.com/jaredcnance/dotnet-status/blob/722d935e156b69a5005994f5b2f9de7d8d1482b6/core/Services/NuGet/PackageStatusRepository.cs#L24-L31).

![image](https://user-images.githubusercontent.com/13851721/42744752-89994fd8-8883-11e8-8762-da1b5285d663.png)

**Comment by tomkerkhove** [comment]
This is an interesting case but I think this is certainly something that needs to be turned on and not supported OOTB - What do you think @rarkins @samneirinck?

With regards to:
> Another thing that makes this a bit more complicated is you can target multiple feeds. I could target NuGet.org, MyGet, a local feed, or any other nuget feed. You do get references to these feed as source URLs that you can iterate over.

I think this should be tracked as a seperate issue and has a fair point. I'm not sure if NuGet.config is still a thing but we could do that based on that.

**Comment by samneirinck** [comment]
Great write-up @jaredcnance, thank you very much. The inital version was implemented to support the most easy scenarios, without support for the full msbuild syntax possibilities. 

Probably now is a good time to start that discussion. I fear the only way would be to fork out to `dotnet` and see if we can get the desired results, perhaps via the `RestoreGraphOutputPath` as you mention.

I'm not 100% familiar on how Renovate actually works, but that will probably be much more expensive than the current approach of just getting csproj files (via github api) and matching a regular expression. It would involve a full clone of the repository, and run `dotnet`, parse the restore graph, before we can start renovating it.

Perhaps not a 100% solid solution, but could we identify the most common patterns, and try to support those, instead of the whole msbuild syntax which would force us to fork out to `dotnet`? You mentioned the following possibilities already:
- Variable defined anywhere
- Directory.Build.props file
- *.props file plus an `<Import>` element in the csproj
    It is also possible to declare common dependencies using these files as well. So, a <PackageReference> could be defined outside the csproj file.
- Command line parameters

I'm just throwing out ideas, but could we try to resolve those variable substitutions ourselves (e.g. when we find a variable, search for a `<VariableName>value</VariableName>` and use that), or will this lead to a path with even more edge cases? I know this wouldn't cover all cases, but perhaps it's worth the trade-off? 


@tomkerkhove For custom feed support, I believe this would indeed fit best in a seperate issue.

**Comment by jaredcnance** [comment]
> could we try to resolve those variable substitutions ourselves (e.g. when we find a variable, search for a <VariableName>value</VariableName> and use that), or will this lead to a path with even more edge cases?

I think this will handle most cases pretty well, it just won’t support some scenarios. The other challenge is that I could have something like:

PackageAA -> $(PackageAVersion)
PackageAB -> $(PackageAVersion)

And those packages might eventually diverge.

Another thing to consider is that perhaps this pattern just doesn’t make sense if you’re using Renovate. The reason you would do this is to minimize the number of manual version substitutions and ensure that you keep versions in sync across all projects in a solution. With a tool like Renovate this becomes less of an issue. Just something to consider...

**Comment by rarkins** [comment]
Quick question: is there any solution possible that would allow us to avoid doing a *full clone* of the repo? e.g. where we have known file names/patterns/extensions and can just selectively download the ones we need via the API?

**Comment by jaredcnance** [comment]
Downloading *.props files (files that can define the variable values) is a good start and would handle all situations I’ve actually seen. I can think of several ways that would break, but I haven’t seen those in practice.

**Comment by rarkins** [comment]
@jaredcnance I like the way you're thinking. i.e. if we can cover 80-90% of the use cases with a simpler solution, and meanwhile the other 10-20% *can* migrate their config to an approach compatible with Renovate, then that sounds like a reasonable compromise.

**Comment by benmccallum** [comment]
Thanks @jaredcnance for starting this discussion and going in to detail about how things work in the dotnet space atm. 

Files we considered when doing restores in our Docker build:
* *.props - for vars that can be used in <PackageReference>s as mentioned.
* NuGet.Config/nuget.config - for additional package sources.
* *.csproj - where <PackageReference>s are setup these days (rather than packages.config)
* *.targets - we also copy over before a restore, and technically I think they could add MSBuild vars, but I wouldn't consider them crucial for an MVP on this.

Just wondering what's the latest on this? We're investigating Renovate, but would need these scenarios supported to get the most out of the tool.

**Comment by viceice** [comment]
I think this should be easily doable with the regex manager. You can replace any version in any text file with it. So can somebody please build a simple sample repo, so I can provide some regex samples.

We only need the relevant config files, no code.

**Comment by benmccallum** [comment]
No worries. I'll create one now

**Comment by benmccallum** [comment]
@viceice, see https://github.com/benmccallum/renovate-dotnet

**Comment by benmccallum** [comment]
Also just added a custom package source, which probably wouldn't be relevant for a regex solution to this problem, but would be relevant if full resolution of the dependencies was considered needed.

**Comment by viceice** [comment]
@benmccallum Can you give me write access and enable renovate app please?

**Comment by benmccallum** [comment]
@viceice, renovate added and there should be an invite in your inbox for the repo :)

**Comment by viceice** [comment]
regex sample will com later

**Comment by benmccallum** [comment]
No worries. I think the challenge you're going to find is that in .props files you can identify a `<PackageReference` with some version easily enough, but you'll struggle to identify a random variable declaration AND resolve it to the package to look up. You may be able to find it, e.g. an XML element around a inner text of a version string, but you'd have no way to resolve <SomeVariableName>1.0.0</SomeVariableName> to the nuget package to lookup latest info on.

I was thinking about this over the w/e, and since we can't put `.` in an XML element name, we could provide this through some kind of attribute hint that's documented and supported, eg:

Directory.Build.props:
```xml
<NewtonsoftJsonVersion PackageNameHint="Newtonsoft.Json">10.0.0</NewtonsoftJsonVersion>
```

Some.csproj
```xml
<PackageReference Include="Newtonsoft.Json" Version="$(NewtonsoftJsonVersion)" />
```

Then the regex could look for `<(.*) PackageNameHint="(.*)">(.*)</(.*)>`  (rough regex, but you get the idea) and pull out the right matched groups to get current versions and package name.

Appreciate your help on this!

**Comment by viceice** [comment]
I think this can be closed, as this is more easily doable with `PackageVersion` which is supported by renovate since [v23.67.0](https://github.com/renovatebot/renovate/releases/tag/23.67.0) and .NET Core SDK 3.1.300

see https://stu.dev/managing-package-versions-centrally/ for sample usage

So this feature request is considered obsolete and can be worked around by using a renovate regex manager.

**Comment by benmccallum** [comment]
Didn't realise it was out already, we'd been thinking we'd just wait for that, thanks for the prompt. cc: @anthony.keller
