### ISSUE TITLE
Warn if multiple lock files are found

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#23241]
### Describe the proposed change(s).

Renovate should log a warning if more than one of package-lock.json, yarn.lock or pnpm-lock.yaml are found. The message should be `Updating multiple npm lock files is deprecated and support will be removed in future versions`.

### Describe why we need/want these change(s).

This complicates our npm manager handling. Pre-requisite for #5607

**Comment by karfau** [comment]
I just spotted this warning in the dependency dashboard.

When will this support end?

I have multiple projects that make use of this support, since there are multiple folders that contain "independent" lock files.

Is the drop of support regarding lock files for different package managers in the same directory or also regarding multiple independent lock files in different directories?

If it is for independent ones, is there some configuration to explicitly opt in to that in the future? (something like package rules but for different lock files?)

**Comment by rarkins** [comment]
We are dropping support - soon - for having two different lock files for the same package.json
