### ISSUE TITLE
Handling GitHub vulnerability alerts with no fixedIn

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2331]
There are instances where a vulnerability alerts exists for a package but there is no `fixedIn` field, i.e. the vulnerability is not patched and may never be patched. Example:

```json
    "alert": {
        "externalIdentifier": "CVE-2018-6594",
        "externalReference": "https://nvd.nist.gov/vuln/detail/CVE-2018-6594",
        "packageName": "pycrypto",
        "affectedRange": "<=2.6.1",
        "fixedIn": ""
    },
```

As a result, these will not result in any alerts or changes in behaviour right now, because there is no PR to prioritise.

Should we raise these as a GitHub Issue instead, or trust that people are already alerted via GitHub's other channels?

**Comment by hbetts** [comment]
> trust that people are already alerted via GitHub's other channels

Trust that people are aware of the vulnerabilities of their project as a result of the in-project alerts and e-mail notifications.

Filing an issue for alerting maintainers is unnecessary.

> Should we raise these as a GitHub Issue

However... maintainers may wonder why Renovate is not submitting a PR to address the security issue. For that reason I would raise an issue informing the maintainers that the security issue cannot be addressed by an upgrade because no upgrade is available. Furthermore, they should be encouraged to reach out to the maintainer of their dependency for a patch (or encouraged to seek another package).

Except, this should _really_ be done as a _confidential_ issue on the project. While I believe malicious parties are actively scanning for unpatched vulnerabilities, making a _confidential_ report or issue pointless, many developers feel nervous about any public display of vulnerability. Therefore, posting any notice of an unpatched vulnerability, without explicit consent of each project, would be unwarranted.

**Comment by rarkins** [comment]
The risk is that maintainers assume there always is or will be a fix and Renovate will upgrade them when it’s available. Ie “nothing more I can do” false sense of security. On the other hand I’m also hesitant to raise “public” issues in repos even though they’re all based off public CVEs so for now I’m going to leave this open and do nothing. 

Also, there’s probably a big overlap between dependencies with unfixed exploits and ones we’d pick up as “unmaintained”. Exception being those using automated dependency updates with automerge :-/
