### ISSUE TITLE
Docker release notes

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2395]
1) datasource returns GitHub source repo
2) unify docker Pr body template with default

**Comment by rarkins** [comment]
Because docker registries have no metadata for source repo, I can’t think of any solution except hardcoding mappings within Renovate from docker image to GitHub repo. Also in many cases the user probably prefers release notes from the true source (eg node.js repo) than the image source/wrapper.

**Comment by mxey** [comment]
What would be better than nothing is checking if there's a matching GitHub repository (or a Gitlab repository on a configurable list of Gitlab instances?) and using that, because often the names line up. 

For example:
* the Docker image `quay.io/coreos/prometheus-operator`comes from GitHub repository https://github.com/coreos/prometheus-operator. 
* When using Gitlab's included Docker Registry, the paths will match, just the domain will be different. Image `docker-registry.example.com/foo/bar` will come from repository `gitlab.example.com/foo/bar`. 

I also wouldn't mind configuring a list of patterns and mappings once, and then not have to go hunt for release notes anymore. For example, a list of regular expressions that turns the image names into repository URLs. That would cover more unusual registries like `k8s.gcr.io` 

[In addition, the Label Schema for Docker images has a label `vcs-url` to reference the Git repository that the image is built from. ](http://label-schema.org/rc1/)

**Comment by rarkins** [comment]
First step we should support that vcs-url schema in case anyone's using it.

Next step is we can code in some known mappings (guesses).

Final step would be to allow manual overrides like we have for [npm](https://github.com/renovatebot/renovate/blob/bf1be750777bcc4a63539ddaaf7c53a8cf4fba95/lib/datasource/npm.js#L40-L46) and [pypi](https://github.com/renovatebot/renovate/blob/bf1be750777bcc4a63539ddaaf7c53a8cf4fba95/lib/datasource/pypi.js#L14-L20).

Note: I'm considering to move this manual mapping into lib/datasource/index.js to avoid reimplementing it in each individual datasoure.
