### ISSUE TITLE
What is renovate, with regards to its behavior, capable of doing via API calls?

### ISSUE THREAD

**Issue by NearAutomata** [renovatebot/renovate#2396]
#### This is a:

- [ ] Bug report (non-security related)
- [ ] Feature request
- [X] I'm not sure which of those it is

#### I'm using:

- [ ] The Renovate GitHub App
- [ ] Self-hosted GitHub
- [X] Self-hosted GitLab
- [ ] Self-hosted VSTS

#### Please describe the issue:
The title might be slightly misleading which I have to apologize for.

It happened to me that Renovate created a merge request for a dependency which got another update in the meantime. Renovate closed the corresponding MR, updated it, and reopened it. The "issue" is that I am running my custom triage bot which got a bit confused:

![](https://i.imgur.com/NilbeFU.png)

Therefore I just have to add certain renovate behavior as an exception to my triage bot. In this particular case for example I might add an exception to not automatically label close/reopen events on MRs with "Status: Abandoned" and "Status: Accepted" once I notice it's from renovate.

So I'd like to know what renovate is capable of to figure out which exceptions to add as well:

- Once there is a new update, renovate will create a new MR.
- If there is an update for a package that has already an open MR, it will be closed, updated and reopened.

Will renovate ever close an MR without updating or merging it at all (aka. abandoning it)? Is there anything else that renovate does?

**Comment by rarkins** [comment]
All of Renovate's interactions with GitLab are captured in this file: https://github.com/renovatebot/renovate/blob/master/lib/platform/gitlab/index.js

To get the full list of API interactions you need to search that file for cases of `get()`, `get.post()`, etc.

In short:

- Renovate will open an MR whenever it detects an update is necessary
- If a Renovate MR needs updating (e.g. newer version released, or a conflict with base branch), then this happens:
    * Renovate deletes the existing Branch
    * GitLab automatically closes the corresponding MR
    * Renovate pushes a new branch
    * Renovate reopens the existing MR to relink it with the new branch
- If Renovate detects that any existing MRs are no longer necessary (which could include because the dependency has been removed from the base branch), then it will delete the branch, which triggers GitLab to close the MR
- Renovate may also create issues in cases such as an invalid configuration detected, and comment on PRs at times too

Hence there are two cases where Renovate will close a MR - in one case it will reopen it shortly after, but in the other case it's closed for good. This will hopefully change soon once GitLab supports the equivalent of a git "force push" via the API so that we can update existing branches without closing them first.

**Comment by NearAutomata** [comment]
Thank you for this thorough explanation. This leads me to the conclusion that I will retain the current behavior of my triage bto and just adjust my labels slightly when the bot recognizes renovate reopening a MR. Once the "force push" via API is available on Gitlab this issue will be resolved automatically which is quite nice.
