### ISSUE TITLE
Dependency update PR broken after yarn connectivity issue

### ISSUE THREAD

**Issue by edmorley** [renovatebot/renovate#2475]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
A PR updating a JS dependency (mozilla/treeherder#3969) is no longer receiving lockfile updates after a transient Yarn connectivity issue - even though it would likely succeed after retrying.

**To Reproduce**

See mozilla/treeherder#3969.

**Expected behavior**
That if the lockfile cannot be updated for a transient network issue, it doesn't prevent Renovate from trying again later (having to delete/rename means more PR/notification churn).

Many thanks :-)

**Comment by rarkins** [comment]
When we think it’s a transient problem then we don’t open/update the PR. So it’s a matter of detecting this (unanticipated) failure case as a transient one rather than changing how/when we retry. Renaming/closing PRs is not really any extra load for Renovate though although does add a little extra noise (eg additional PR number) for you.

**Comment by edmorley** [comment]
Yeah it's more the manual steps/email noise for my colleagues/time delay for me, rather than effect on Renovate. Renaming/deleting are manual steps, then there's a delay before the new PR will be opened, then I have to wait for CI to complete - whereas if Renovate automatically retried, all of that would be complete by the time I come to look at my PR notifications in the morning :-)
