### ISSUE TITLE
Include PR body note when Go implicitly increases the go mod directive

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#25047]
### Describe the proposed change(s).

As discussed in #24994, Go 1.21 can now implicitly increase the go mod directive in `go.mod` files if it detects that the current directive is wrong (too low), or if the upgrades in the PR require a newer Go version. In such cases the Go version change is not mentioned in the PR, but ideally it should be.

I propose that the updateArtifacts() function can return a `prBodyNotes` value for such cases as a quick way to warn that the Go version was bumped as part of this PR.

**Comment by secustor** [comment]
Counter proposal: 

If `updateArtifacts` signals that updates have happened extract again and compare the result with the initial one. 
That way we get all information we display currently on PRs.

**Comment by rarkins** [comment]
Agreed! I also created #25049

But even if #25049 is done, I think that a warning in the PR body notes would be beneficial because increasing the minimum Go version is _very_ significant and not to be "lost" somewhere in the PR body table

**Comment by secustor** [comment]
No disagreement there, my comment has been solely about the implementation method. 

> I propose that the updateArtifacts() function can return a prBodyNotes value for such cases as a quick way to warn that the Go version was bumped as part of this PR.

**Comment by rarkins** [comment]
I think only the manager knows if a particular change is worth a warning/note. So it should be able to return both indicators

**Comment by rarkins** [comment]
Reproduction repo: https://github.com/renovate-reproductions/25047

**Comment by mtardy** [comment]
This is an issue we hit as well, it's annoying when maintaining stable branches with old Go versions like 1.18 for example, or even 1.20. We have PRs that are trying to upgrade just one dependency but the Go version constraint is ^directive (for example ^1.20), thus installing latest Go 1.21.x, thus updating the Go directive in the `go.mod` with one of the latest Go version and bumping a tons of others dependencies. It's a big mess. 

Would it be possible that the Go constraint to install the Go binaries would stick to the newest minor version instead of major?

**Comment by rarkins** [comment]
Create a reproduction to demonstrate/prove what you're claiming. Go is updating the go.mod directive, not Renovate.

**Comment by mtardy** [comment]
> Create a reproduction to demonstrate/prove what you're claiming. Go is updating the go.mod directive, not Renovate.

Interestingly it was caused by https://github.com/renovatebot/renovate/issues/26057, because we have a replace directive in some `go.mod` that was using a local module in a submodule.
