### ISSUE TITLE
Link preset docs to source

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#25236]
### Describe the proposed change(s).

Example preset docs page: https://docs.renovatebot.com/presets-group/

Currently links to https://github.com/renovatebot/renovate/edit/main/docs/usage/presets-group.md

Should link to https://github.com/renovatebot/renovate/edit/main/lib/config/presets/internal/group.ts

**Comment by viceice** [comment]
Solution:
- https://github.com/renovatebot/renovate/discussions/25548

**Comment by RahulGautamSingh** [comment]
We can change this by adding a `edit_url` to the page's metadata to the page we want it redirected to.
In the above case it will be: https://github.com/renovatebot/renovate/edit/main/lib/config/presets/internal/default.ts

Example:

```md
---
edit_url: '<edit-url>'
---
page content ...
```

Since these pages aren't present in `docs/` folder by default as they are generated in the `tools/docs/presets.ts` file we need to modify the generateFrontMatter function in the file.
Before:
https://github.com/renovatebot/renovate/blob/0db0bf03df36c1bfcf41c41b02bd40a60fd74983/tools/docs/presets.ts#L13-L21

After:
```ts
function generateFrontMatter(name: string, order: number): string {
  return `---
date: 2017-12-07
title: ${name} Presets
categories:
    - config-presets
type: Document
order: ${order}
edit_url: https://github.com/renovatebot/renovate/edit/main/lib/config/presets/internal/${name.toLowerCase()}.ts
---
```
