### ISSUE TITLE
Merge conflict alert false positive

### ISSUE THREAD

**Issue by Arcanemagus** [renovatebot/renovate#2524]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
"Configure Renovate" PR claims there is a merge conflict when there isn't.

**To Reproduce**

1.  Unknown, possibly due to moving the config into package.json in the initial PR?

**Expected behavior**
No false positive alert on a merge conflict.

**Screenshots**
N/A

**Additional context**
Seen in https://github.com/AtomLinter/atom-minimap-linter/pull/40.

It seems that Renovate is properly picking up the new configuration as the "What to Expect" section has updated appropriately. However it is still listing a test `package.json` that I tried to list in the `ignorePaths`, that may just be a mistake in the configuration on my part.

**Comment by rarkins** [comment]
I started a manual run on the repo and the merge conflict has cleared. I think GitHub probably returned a temporary "unstable" response for mergeability and it got misclassified as conflicted. I will leave this issue open until I've worked out why that was.

For ignoring one of the files, it needs to be a glob so please try `spec/**` instead of `spec/*`.

**Comment by Arcanemagus** [comment]
If it was a temporary thing I'll go ahead and continue working on it then, didn't want to touch the state if it was something that depended on that 😉.

**Comment by Arcanemagus** [comment]
Hmmm, the new commit I added seems to have caused this warning again, is there any information/testing you need from me or should I merge the PR?

I'm in no rush to get this merged FYI, so we can test on there if you need it.

**Comment by rarkins** [comment]
I'll push a fix in a few minutes, which then should be live in the app maybe 10-15 minutes later once I see and approve and internal PR to update it. What's happening right now is that:

- Changes to the onboarding PR trigger a webhook, which triggers Renovate
- PR is still in an "unknown" mergeable state at that point (GitHub is yet to recalculate mergeability), so `pr.canMerge=false`
- Onboarding PR has a logic error where it's checking "can merge" rather than "is unmergeable". The latter is what we should be checking - it means "PR is conflicted", which is what we should be looking for instead.

**Comment by rarkins** [comment]
Fix is now live in the app, so you shouldn't see it again. Thanks for reporting!
