### ISSUE TITLE
Unexpectedly closing PR

### ISSUE THREAD

**Issue by ajafff** [renovatebot/renovate#2561]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
PR https://github.com/fimbullinter/wotan/pull/424 was autoclosed even though the dependency still needs to be updated.
Renovate is configured to follow `typescript@next`. As of writing this `typescript@next` is `3.1.0-dev.20180925`

There were no changes on `master` that could have updated the dependency.
Note that CI for this PR is failing. I left the PR open to get notified when an upstream bug in that dependency is fixed.

**Did you see anything helpful in debug logs?**
https://renovatebot.com/dashboard#fimbullinter/wotan/21563709

I don't see anything helpful. There are a few `DEBUG: Dependency is disabled (typescript)` logs, but that should only be related to the `peerDependency` in `packages/*/package.json` and should not apply to `./package.json` where `typescript` is in `devDependencies`

**To Reproduce**

**Expected behavior**
PR stays open and is updated when necessary.

**Screenshots**

**Additional context**
The PR was closed outside of its schedule. Though I don't know if that's related somehow.

**Comment by rarkins** [comment]
@ajafff when I check the registry for `typescript` right now I see it's jumped to `3.2.0`:

![image](https://user-images.githubusercontent.com/6311784/46071789-1a3dcd80-c181-11e8-8993-a76cd2fc407c.png)

That version was released `3.2.0-dev.20180926 | "2018-09-26T06:14:40.274Z"`

The autoclosing happened very soon after:
![image](https://user-images.githubusercontent.com/6311784/46072040-a819b880-c181-11e8-8453-8f92d9205158.png)

Here's the log for the run immediately before:
```
{
  "depType": "devDependencies",
  "depName": "typescript",
  "versionScheme": "semver",
  "currentValue": "3.1.0-dev.20180915",
  "purl": "pkg:npm\/typescript",
  "prettyDepType": "devDependency",
  "lockedVersion": "3.1.0-dev.20180915",
  "updates": [
    {
      "fromVersion": "3.1.0-dev.20180915",
      "toVersion": "3.1.0-dev.20180925",
      "newValue": "3.1.0-dev.20180925",
      "newMajor": 3,
      "newMinor": 1,
      "updateType": "minor",
      "isSingleVersion": true,
      "releaseTimestamp": "2018-09-25T06:14:38.482Z",
      "canBeUnpublished": true
    }
  ],
  "repositoryUrl": "https:\/\/github.com\/Microsoft\/TypeScript",
  "homepage": "http:\/\/typescriptlang.org\/",
  "releases": [
    "3.1.0-dev.20180915",
    "3.1.0-dev.20180925"
  ]
}
```

Here's the lookup log for that particular run:
```
{
  "depType": "devDependencies",
  "depName": "typescript",
  "versionScheme": "semver",
  "currentValue": "3.1.0-dev.20180915",
  "purl": "pkg:npm\/typescript",
  "prettyDepType": "devDependency",
  "lockedVersion": "3.1.0-dev.20180915",
  "repositoryUrl": "https:\/\/github.com\/Microsoft\/TypeScript",
  "homepage": "http:\/\/typescriptlang.org\/",
  "releases": []
}
```

And ones after that seem to have the same lack of updates. So for some reason they seem to be failing to be picking up the new one. I suspect we are mistakenly doing a filter to prevent jumping unstable minor versions and either need to skip that filter OR implicitly set `ignoreUnstable=false` so that the 3.1.0->3.2.0 unstable jump survives the filter. Maybe an edge case we missed.
