### ISSUE TITLE
Same PR being opened repeatedly

### ISSUE THREAD

**Issue by vikr01** [renovatebot/renovate#2600]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
When closing a pull request by `renovate` to update `yarn`, it immediately opens a new pull request to do the exact same thing.

`yarn` is both in `devDependencies` and in `engines`, and `renovate` is trying to update them together.

**To Reproduce**

1.  Create repository with `yarn@^1.9.4` as a dependency
2. Set `yarn` to be `>=1` in engines
3. Set `rangeStrategy` to `bump`

**Expected behavior**
Exact same PR not to be raised again after being closed.

**Additional context**
vikr01/tbd-project-name#74
vikr01/tbd-project-name#75
vikr01/tbd-project-name#76
vikr01/tbd-project-name#77

**Comment by rarkins** [comment]
@vikr01 I have tweaked the logic so that Renovate can detect the common version in this PR "group". Now you can see that https://github.com/vikr01/tbd-project-name/pull/78 has been renamed to have the version in the title, which means it can be closed and will stay closed until there is a newer version of Yarn available.

**Comment by vikr01** [comment]
Thank you, @rarkins!
