### ISSUE TITLE
unable to read symlinked renovated.json file

### ISSUE THREAD

**Issue by ahmadnassri** [renovatebot/renovate#2641]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
when `renovate.json` is a symlink, the system fails to parse it, and an issue is opened on then repository:

```
Action Required: Fix Renovate Configuration

There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

File: renovate.json
Error type: Invalid JSON (parsing failed)
Message: Syntax error near files/reno
```

**Did you see anything helpful in debug logs?**
N/A

**To Reproduce**

`renovate.json` is a symlink to elsewhere in the repo ...

**Expected behavior**
`renovate.json` symlink should be followed and read form source

**Comment by rarkins** [comment]
Renovate ignores symlinks in the filesystem for all use cases so symlinking the config file is not something we will probably be able to support. What is the reason for doing so?

**Comment by ahmadnassri** [comment]
I'm trying to put `renovate.json` in an npm package and symlink to the root on dependants... purpose to force centralization of config beyond `extend` and use versioning (and renovate itself) to keep projects in sync 😊

**Comment by rarkins** [comment]
Wouldn't that mean not only following symlinks but also it would only work if Renovate did a full "npm install" first as well? I assume you mean it's in the `package.json` devDependencies and would be symlinked from inside `node_modules/`?

**Comment by ahmadnassri** [comment]
@rarkins yes, correct.

**Comment by rarkins** [comment]
In that case sorry, this is a definite "wontfix". I can't see a scenario where we want to clone and install npm modules before even reading the `renovate.json`. 

However, please take a look at https://github.com/renovatebot/renovate/issues/686 and comment there if you think it would satisfy some or more of your requirements. The idea of that one is that you can use versioned presets as dependencies, but the implementation isn't nailed down yet. Probably:

- For each preset file referenced, we peek into the root `package.json` so see if they've been added as a devDependency along with a version. 
- If so then look up that specific version rather than `latest`

**Comment by ahmadnassri** [comment]
that's alright, had to ask :)

**Comment by stevefan1999-personal** [comment]
> Renovate ignores symlinks in the filesystem for all use cases so symlinking the config file is not something we will probably be able to support. What is the reason for doing so?

I know it is odd but I put all my dotfiles into a folder and then softlink them all to root; that's why renovate didn't read my config🙄

**Comment by rarkins** [comment]
@stevefan1999-personal but are you talking about your admin bot config (e.g. `config.js`), or a `renovate.json` config within repositories?

**Comment by stevefan1999-personal** [comment]
@rarkins Yeah, I did this IANS:
```bash
cd repo/
touch .config/renovate.json
ln -s .config/renovate.json renovate.json
```
