### ISSUE TITLE
Automerge label/tag

### ISSUE THREAD

**Issue by UberMouse** [renovatebot/renovate#2645]
**What would you like Renovate to be able to do?**
I would like to be able to instruct Renovate to auto-merge a specific PR

**Describe the solution you'd like**
Something simple like giving the PR a label or similar to the `rebase!` title change something like `merge!`

**Comment by rarkins** [comment]
I think this can be done, but I want to make sure I understand the use case fully. Why not just click "Merge" yourself instead of adding a label? Is it because you would add this label before tests are completed running?

**Comment by UberMouse** [comment]
Just another use case I thought of. Since I recently set up Renovate and we had a lot of out of date dependencies (66 PRs to churn through) it was quite common for PRs to get merge conflicts requiring Renovate to rebase them. Ideally, I would be able to trigger a rebase and the auto merge tag so that the branch can get rebased, the build passes and then it gets automerged.

Thanks, love the product :)

**Comment by UberMouse** [comment]
Was just looking through the configuration options again and noticed automergeComment, I had missed this before. That looked like it would work just fine for me, except it looks you can't have that functioning for packages that don't have automerge set? Or at least I have to set automergeType to pr-comment which means the packages I want to get merged automatically currently would then require the comment?

**Comment by rarkins** [comment]
Actually that one is not what you need, it's almost like the opposite. When automergeComment is set, and automerge *is configured*, then instead of actually merging Renovate will instead just add the specified comment. It's for systems that use a third party merge tool and don't want Renovate to do its own merges.

Instead you're after a solution where a label or comment will trigger Renovate's own automerge.

**Comment by UberMouse** [comment]
Ah yes, that makes sense. Thanks for the quick explanation :)

**Comment by rarkins** [comment]
Problem: to be fully strict, we should only allow someone to merge by label/comment if they have write access to master. 

Should we be fully strict by default? Can we even reliably detect for each platform about who has wrote access to the base branch?

One option is to allow any collaborator to merge by label or comment but allow admins to disallow this by config. Eg default value of `mergeLabel` could be “merge” but if set to null then it disables it. 

@hutson do you think we should lean on careful side (disable by default) or easy side (enable by default)?

**Comment by hutson** [comment]
> Should we be fully strict by default? Can we even reliably detect for each platform about who has wrote access to the base branch?

If _possible_ I believe checking write access on the base branch of a PR/Merge would be preferred. Checking against a repository's _default_ branch, when the base branch is different, and blocking the merge because a user has write access to the base branch but not the _default_ branch, may be _surprising_ to users.

> One option is to allow any collaborator to merge by label or comment but allow admins to disallow this by config.

Oh, I would definitely not prefer this approach. One core tenant of Renovate that I like is that, by default, Renovate doesn't do things. Instead, I _opt-in_ to behaviors.

Requiring me to _disallow_ merging when a user doesn't have permissions to the target branch would be quite surprising, and effectively bypass the growing number of authorization checks being implemented by GitHub/GitLab to restrict who, and what, can be merged into a project's _default_ branch.

> Why not just click "Merge" yourself instead of adding a label? Is it because you would add this label before tests are completed running?

I **really** like GitLab's "merge when build passes" field in merge requests.

Though, @UberMouse and @rarkins, could this use case be met with [`prCreation`](https://renovatebot.com/docs/configuration-options/#prcreation)? I use that option to have Renovate create the branch, and only raise the merge request on GitLab after tests have completed. Therefore, when I arrive at the merge request I should be able to accept it immediately.

For my projects I have `automerge` and `rebaseStalePrs` enabled. So Renovate should be re-basing merge requests on GitLab until all mergable (tests pass) Renovate merge requests are merged. (Sorry @rarkins for the Renovate load, but this particular feature is just so useful in ensuring I actually get dependency updates into my project.)

However, it might not be ideal for all projects. So I can imagine a `merge` command that, effectively, enabled `automerge` and `rebaseStalePrs` for that specific pull/merge request.

**Comment by grit96** [comment]
My use case for this is because I run renovate on a schedule so that CI resources aren't clogged up during the day, and want to queue merges to happen during the schedule.

I use `:automergePatch` and manually review major and minor updates, so it would be great to be able to approve update MRs and queue them to merge during the schedule.

**Comment by rarkins** [comment]
Yes, so I think we need to do it like this:

- [ ] A new option to enable this feature, disabled by default for security/access control reasons
- [ ] For GitHub and GitLab, add a new checkbox if enabled. Also support label-based automerge for all, but especially for Bitbucket and Azure DevOps. Do not make the label name configurable - it should always be `automerge` or `merge`
- [ ] If the box is checked or a label is added, then Renovate will automerge the branch at the next available opportunity (branch up to date, tests passed)

I'm not sure of the option name. If it were just github and gitlab then I'd call it `enableAutomergeCheckbox`, because it's perfectly descriptive. Maybe `userAutomerge` or `allowContributorAutomerge` instead?

**Comment by rarkins** [comment]
Closed in favour of #3172
