### ISSUE TITLE
Go updates fail with "permission denied" error

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#2649]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Go updates started failing with "permission denied" errors.
See https://github.com/sourcegraph/sourcegraph/pull/285#issuecomment-429476935

**Comment by rarkins** [comment]
@felixfbecker thanks for the heads-up. It looks like some Go cache folders have root permissions while `go get` is running non-privileged and failing to write/update them. I'll reset all caches now to hopefully fix it.

**Comment by rarkins** [comment]
Root cause: I switched from using the default Golang Docker image, which runs privileged, to Renovate's own Golang image which runs unprivileged. However there remained existing Go cache files on backend workers owned by `root` that then couldn't be overwritten by the new image.

Resolution: I have killed/recreated all backend workers to start over without privileged caches. Manually triggered a rebase for all sourcegraph/sourcegraph Go PRs to confirm the fix.

Further action: Any other repositories affected can request immediate rebases manually by either:
(a) Adding the label 'rebase' to each PR, or
(a) Renaming each PR to have the prefix "rebase!"
