### ISSUE TITLE
Refactor: config option parent -> parents

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#26599]
### Describe the proposed change(s).

Change this to be an array of strings: https://github.com/renovatebot/renovate/blob/8cf2d21082a8fe40590ec3f48b073891cb1c1a30/lib/config/types.ts#L397-L402

+ associated downstream code changes

**Comment by RahulGautamSingh** [comment]
This might not be the best place to discuss this but I think we need a new option. Inorder to address the duplicate naming, in children names and parent names.

For eg. `username` is a valid option by itself, and it can also be a children of the `hostRules` config option.

All other children (properties) of the `hostRules` config option are documented in the [`lib/config/option/index.ts`](https://github.com/renovatebot/renovate/blob/main/lib/config/options/index.ts), file but `username`, `token` and `password` are not. I guess they aren't because the names will clash.
