### ISSUE TITLE
[composer]: supports lock file maintenance

### ISSUE THREAD

**Issue by evilebottnawi** [renovatebot/renovate#2677]
**What would you like Renovate to be able to do?**

Supports lock file maintenance as for `npm/yarn/etc`

**Describe the solution you'd like**

Not require.

**Describe alternatives you've considered**

Not require.

**Additional context**

Not require.

Thanks for great project.

**Comment by rarkins** [comment]
@evilebottnawi 	no blockers, but the logic for lockFileMaintenance needs a little refactoring as it has some unintentional hardcodings for npm/yarn right now as that's the only package manager type supported until now.

**Comment by rarkins** [comment]
Actually v14 didn't touch the lockFileMaintenance part, but still there should be no blocker.

**Comment by leomoty** [comment]
Hey @rarkins, anyone working on this? If not, can you give some code pointers, I am also interested in this feature.

**Comment by rarkins** [comment]
@leomoty it would be great if you could get started on this feature. I would like to work with you on it though, as there might be the need for a little refactoring of npm's code too in order to make this feature generic and not npm-specific. If you'd like, I have a developer-only Slack channel we can use to discuss. If you'd like to join, please send me your email to support@renovatebot.com so that I can generate the invite

**Comment by evilebottnawi** [comment]
@rarkins hi, can you provide link on file(s)/description where i should start this?

**Comment by rarkins** [comment]
@evilebottnawi 	I'm working on it:

![image](https://user-images.githubusercontent.com/6311784/59118534-b3e48e00-8950-11e9-8e51-bf0d425ba4c0.png)

**Comment by evilebottnawi** [comment]
Very big thanks!
