### ISSUE TITLE
Support python setup.py

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2681]
https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires

**Comment by rarkins** [comment]
Examples:
- [setup.py with no versions](https://github.com/canonical-webteam/yaml-responses/blob/master/setup.py)
- [setup.py with versions](https://github.com/canonical-ols/talisker/blob/master/setup.py)

**Comment by rarkins** [comment]
I don't know if we can parse it easily enough ourselves or if parsing using python would be more reliable and reasonably efficient: https://stackoverflow.com/a/24237067/3005034

If the child process is too intensive then we can also hash the file content and cache the result aggressively to save continuously parsing the same files over and over.

Another gotcha: can the setup.py ever refer to external files to get dependency versions?

**Comment by hbetts** [comment]
> Another gotcha: can the setup.py ever refer to external files to get dependency versions?

Our particular setup - https://github.com/factset/quart-openapi/blob/6ed409b6de43392fe68e828b5ca3c41ea6ef4461/setup.py#L33

Though I think the `pip_requirements` option will allow us to keep the pip requirements files up-to-date.

**Comment by keimlink** [comment]
Since release 30.3.0 (from 2016-12-08) setuptools supports not only declaring dependencies in [`setup.py`](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies) but also in [`setup.cfg`](https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files). In fact it allows you to move all meta data to `setup.cfg` and just have an basic `setup.py` file.

Here's a minimal example for a Django project:

`setup.py`
```python
from setuptools import setup

setup()
```

`setup.cfg`
```ini
[metadata]
name = myproject
version = 1.2.0
description = Lorem ipsum
long_description = file: README.rst
author = My Company
author_email = development@example.com
license = Other/Proprietary License
classifiers =
    Development Status :: 5 - Production/Stable
    Environment :: Web Environment
    Framework :: Django
    Programming Language :: Python

[options]
zip_safe = False
include_package_data = True
packages = myproject
install_requires =
    arrow==0.12.1
    bleach==2.1.3
    Django==2.0.5
    django-allauth==0.36.0
    gunicorn==19.8.1
    psycopg2==2.7.4
    pytz==2018.4
    wagtail==2.0.1
python_requires = >=3.6,<3.7

[bdist_wheel]
universal = 1
```

Is parsing the dependencies in `setup.cfg` easier than in `setup.py`?

If so you could just define that Renovate does only support Python projects with dependencies defined in `setup.cfg`, but not in `setup.py`.

This would mean these projects (and the users installing it) would at least have to use setuptools 30.3.0. But this version has been released nearly two years ago. So most users will have it.

And this would only affect Renovate users that define their dependencies using setuptools. Projects using a `requirements.txt` file would still be able to use Renovate as before.

**Comment by rarkins** [comment]
@keimlink that would definitely be much easier. Thanks for the tip

**Comment by keimlink** [comment]
@hbetts Why are you reading your requirements from additional files?

**Comment by rarkins** [comment]
I've split `setup.cfg` support into new feature request #2734
