### ISSUE TITLE
Update custom homebrew taps

### ISSUE THREAD

**Issue by achew22** [renovatebot/renovate#2738]
**What would you like Renovate to be able to do?**

It would be really nice if Renovate Bot could update a homebrew tap automatically so that the latest release is always what is available from homebrew.

**Describe the solution you'd like**

For binaries that are live as a github archive and are compiled ([example](https://github.com/bazelbuild/homebrew-tap/blob/master/Formula/ibazel.rb)) it would be really nice if you could detect those, find the latest version and send a PR to update it and the sha256 of the latest tag.

**Describe alternatives you've considered**

Doing it manually :frowning: 

**Additional context**

Thanks so much!

**Comment by rarkins** [comment]
fileMatch: `^Formula/[^/]+\.rb$`

Initially let's support github-hosted ones only, e.g.

```
class Ibazel < Formula
  desc 'IBazel is a tool for building Bazel targets when source files change.'
  homepage 'https://github.com/bazelbuild/bazel-watcher'
  url "https://github.com/bazelbuild/bazel-watcher/archive/v0.6.0.tar.gz"
  sha256 '819ae4ff201f62e769e627335b122c84a472671b80d6fa0407b157c0c982b219'
```

Note the inconsistent use of `"` vs `'` above

Generating the sha256 seems similar to how we actually do it for bazel updates too.

Anecdote: the homebrew core project has nearly 3500 projects in in its Formula folder: https://github.com/Homebrew/homebrew-core/tree/master/Formula

**Comment by rarkins** [comment]
This will be a new manager named "homebrew" in lib/managers/homebrew

fileMatch: `^Formula/[^/]+\.rb$`

Parse it line-by-line, look for any `class X < Formula`

If URL matches `https://github.com/*/*/archive/<valid semver>.tar.gz` then add it as a valid dep, otherwise skip it.

Use existing github datasource, filtering for releases.

The update will need to download the calculate the sha256 whenever the file has changed (don't recalculate if the file was already updated)
