### ISSUE TITLE
Gradle missing some upgrades?

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#2740]
@corecanarias can you help me look into this? This question is from my fork of telegram-images.

Here's the gradle log:

```
       The following dependencies have later release versions:
        - com.github.rubenlagus:TelegramBots [v2.3.5 -> 2.4.4.5]
        - cglib:cglib-nodep [3.1 -> 3.2.9]
        - com.github.ben-manes:gradle-versions-plugin [0.17.0 -> 0.20.0]
        - org.codehaus.groovy:groovy [2.4.7 -> 3.0.0-alpha-3]
        - org.objenesis:objenesis [2.1 -> 3.0.1]
        - org.spockframework:spock-core [1.0-groovy-2.4 -> 1.2-RC3-groovy-2.5]
        - org.springframework.boot:spring-boot-gradle-plugin [1.4.0.RELEASE -> 2.1.0.RELEASE]
        - org.springframework.boot:spring-boot-starter-jersey [1.4.0.RELEASE -> 2.1.0.RELEASE]
```

But we only create these:
![image](https://user-images.githubusercontent.com/6311784/47965246-fa81ab00-e044-11e8-8135-fefe56ce959c.png)

These are missing:
```
com.github.ben-manes:gradle-versions-plugin [0.17.0 -> 0.20.0]
org.codehaus.groovy:groovy [2.4.7 -> 3.0.0-alpha-3]
org.springframework.boot:spring-boot-starter-jersey [1.4.0.RELEASE -> 2.1.0.RELEASE]
```

The first one is the one we inject, right? Should we be using the latest version of it?

groovy looks to be an "unstable" version so maybe that's why it's skipped? But then why are we upgrading spock-core to a stable version instead of `1.2-RC3-groovy-2.5`?

Also I can see no reason for skipping `spring-boot-starter-jersey`'s upgrade as we alreaduy upgrade `spring-boot-starter-plugin`.

**Comment by corecanarias** [comment]
@rarkins Yep, that's weird. Let me take a look

**Comment by corecanarias** [comment]
Ok, there are two things:
* gradle-versions-plugin It's because we are using the recommended version for gradle-use-latest-versions-plugin 0.2.3 Last week they release a new version: 0.2.5 and now in the docs says using 0.20.0 Probably we would need a way to maintain this dependencies up to date as well. But not sure how, since this is an internal configuration of renovate. Maybe externalize it to the dockerfile? But that would introduce more complexity for someone that wants to run it without docker

* For the other two dependencies, it's not updated because they are defined without versioning:
```
        compile('org.springframework.boot:spring-boot-starter-jersey')
        compile('org.codehaus.groovy:groovy')
```
This dependencies are selected based on spring-boot-gradle-plugin version. So they will automatically pick the latest version when this version changes.
