### ISSUE TITLE
Renovate not updating docker images

### ISSUE THREAD

**Issue by nicksnyder** [renovatebot/renovate#2762]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I pushed a new docker tag (2.13.1) but renovate is not opening a PR.

**Did you see anything helpful in debug logs?**
I don't anything obviously wrong other than I don't see references to the new tag 2.13.1 (just the old tag 2.13.0):
https://renovatebot.com/dashboard#github/sourcegraph/deploy-sourcegraph/27409804

**To Reproduce**
1.  Verify that 2.13.1 tag exists on Docker hub (e.g. https://hub.docker.com/r/sourcegraph/gitserver/tags/).
2. Go to https://renovatebot.com/dashboard#github/sourcegraph/deploy-sourcegraph to verify that Renovate bot ran after the image tags were pushed to Docker hub.
2. Go to https://github.com/sourcegraph/deploy-sourcegraph/pulls?utf8=%E2%9C%93&q=is%3Apr+2.13.1 and see no Renovate PRs for 2.13.1

**Expected behavior**
I expect Renovate to open a PR to update image tags from 2.13.0 to 2.13.1.

This has worked recently in the past (e.g. https://github.com/sourcegraph/deploy-sourcegraph/pull/136)

**Comment by nicksnyder** [comment]
Looks like it picked it up this time around: https://github.com/sourcegraph/deploy-sourcegraph/pull/137

I am still confused why it didn't pick it up the first time.

**Comment by rarkins** [comment]
When exactly was it published? Right now I see it saying "an hour ago" for the tag so that's around 6:40pm UTC +/- perhaps 15 minutes.

It looks like it was detected by Renovate at 2018-11-06T18:22:29.974Z in job 27411351, which is 1h20m+ hours ago, which seems pretty good. 

BTW Renovate caches Docker tags for 30 minutes: https://github.com/renovatebot/renovate/blob/680d5c17ace753d245933f01504bd0239d9188a6/lib/datasource/docker.js#L222-L223

Also, unlike npmjs, there is no notifications/webhooks for new publishes that I'm aware of that would allow Renovate to react instantly or cache-bust whenever a new tag is published.

**Comment by rarkins** [comment]
```
"msg":"Created Pull Request #137","time":"2018-11-06T18:22:42.225Z"
```

**Comment by rarkins** [comment]
I got confused adjusting to UTC earlier, I see that the PR was raised maybe 30 minutes or so after the Docker image was published. So as noted earlier:

- Caching for Docker tags is 30 minutes, but maybe we can reduce that
- By default repositories are only "background checked" hourly anyway, so unless you are lucky with timing or you trigger a run manually then there's nothing from Docker to alert us to recently published packages and you're likely to wait up until 60 minutes anyway. Checking any more regularly would risk exhausting GitHub's API allowance for your account

**Comment by nicksnyder** [comment]
Docker tag caching explains the lag, so that answers my question. Thanks!
