### ISSUE TITLE
Replace hardcoded github.com/gitlab.com checks with detectPlatform()

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#28102]
### Describe the proposed change(s).

We have some inconsistency in our code where sometimes we check if a host is e.g. github.com or includes the string "github" in its hostname, and other times we have a more sophisticated check using detectPlatform(). We should do a code review for remaining hardcoded checks and see which can be replaced with detectPlatform().

**Comment by RahulGautamSingh** [comment]
I could only find this one instance where we can directly use `detectPlatform` 
https://github.com/renovatebot/renovate/blob/632e8a594a17ac74af6cd1ac339ecbd4e5e64e65/lib/workers/repository/update/pr/changelog/github/source.ts#L40

Apart from this I found the following 4 instances where it seems we can use the `detectPlatform` function but cannot/shoulndn't:

1. https://github.com/renovatebot/renovate/blob/632e8a594a17ac74af6cd1ac339ecbd4e5e64e65/lib/modules/manager/bazel/rules/http.ts#L102
2. https://github.com/renovatebot/renovate/blob/632e8a594a17ac74af6cd1ac339ecbd4e5e64e65/lib/modules/manager/homebrew/extract.ts#L59
3. https://github.com/renovatebot/renovate/blob/632e8a594a17ac74af6cd1ac339ecbd4e5e64e65/lib/modules/manager/swift/extract.ts#L121

(In the above 3 cases, we should not use `detectPlatform` because `parseUrl` is already called within the fns and the other fields returned from the `parseUrl` fn are necessary too. If we use `detectPlatform` just for the url matching then we will be repeating similar logic as `detectPlatform` calls `parseUrl` as well.)


---

4. https://github.com/renovatebot/renovate/blob/632e8a594a17ac74af6cd1ac339ecbd4e5e64e65/lib/modules/manager/pre-commit/extract.ts#L31-L37

 (We cannot as its only the `hostname` which is being compared and not the full url )
