### ISSUE TITLE
package.json dependencies not being pinned?

### ISSUE THREAD

**Issue by ekristen** [renovatebot/renovate#2823]
**Note:** this could be a config problem? I looked through the docs but didn't see anything. 

**Edit:** Perhaps it's just not enabled in the config:base or maybe only `devDeps` in `config:base`? Attempting to follow the presets.

**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
It seems that only `devDependencies` are getting pinned on onboarding and subsequent runs of Renovate.

**Did you see anything helpful in debug logs?**
No

**To Reproduce**
Have a node.js project with package.json and package-lock.json, configure renovate to extend config:base only.

**Expected behavior**
Both dependencies and devDependencies should get a PR for pinning?

**Comment by rarkins** [comment]
Renovate only autodetects pinning if you tell it to. Config:base includes one such rule though. Next, it only pins dependencies “automatically” if it detects it’s a private package OR missing a `main`. Otherwise if it’s declared as non-private and also has a `main` entry then we to detect it as a library. You can fix the package.json if so or add config to override it to pin. 

If that doesn’t solve it for you then please create a public repo to reproduce it with a s post to the renovatebot/config-help repo.

**Comment by ekristen** [comment]
Sorry for the static, I knew I was missing something

**Comment by rarkins** [comment]
That’s ok, it’s not really documented that I can recall
