### ISSUE TITLE
Save repoCache extract cache when in dryRun mode

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#28385]
### Describe the proposed change(s).

We should write/update the extract part of our repo cache even when in dryRun mode to improve performance for repeat runs.

Exclude branch/update cache for now - it should be kept as-is.

**Comment by RahulGautamSingh** [comment]
We do rewrite the extract cache during dryRuns, we just don't save it. 

For dryRun = lookup/extract, we don't save because `finalizeRepo` within which repoCache.save() is executed, doesn't get called. Because of this condition.
https://github.com/renovatebot/renovate/blob/20a2659dbd8291f76d17b5ba77a26f24422d4738/lib/workers/repository/index.ts#L79-L82

For this, we can call repoCache.save() before exiting in this case. Probably, add an else to the if mentioned above here and save the cache within it.


For dryRun = full, we don't save the cache, even when `finalizeRepo` is invoked because of this:
https://github.com/renovatebot/renovate/blob/20a2659dbd8291f76d17b5ba77a26f24422d4738/lib/util/cache/repository/index.ts#L22-L28
Simply removing the condition to always save, should do the job.

**Comment by rarkins** [comment]
This is maybe not so important once I have mode=silent instead, because the Renovate app will switch to it. Will close this for now
