### ISSUE TITLE
PR's updated as "autoclosed" don't get closed by Bitbucket

### ISSUE THREAD

**Issue by carlosfunk** [renovatebot/renovate#2856]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Marking PRs in Bitbucket as autoclosed doesn't close them

**Did you see anything helpful in debug logs?**
Unfortunately not, what I see in Bitbucket is a bunch of PR's with title like this....

"Update dependency boto3 to v1.9.47 - autoclosed"

**Expected behavior**
PR's should updated in a way that lets them be closed automatically by Bitbucket

<img width="528" alt="autoclosed prs" src="https://user-images.githubusercontent.com/907689/48866489-e1943a80-ee37-11e8-9ac3-5f80687faac3.png">

**Comment by rarkins** [comment]
@carlosfunk thanks for the bug report. Can you help me understand better?

1. Is this running against Bitbucket Cloud?
2. Are you manually making them as autoclosed yourself, or is the Renovate script renaming them while using your login?
3. Do these PRs look like they *should* be autoclosed? Normally it only happens if you have updated dependencies manually (so they are no longer relevant) or you have changed config such as to group them together, so the old ones need closing.

**Comment by carlosfunk** [comment]
1. Yeah bitbucket cloud
2. Renovate is renaming them autoclosed
3. They were updated with autoclosed after a configuration change (so not unexpected I just assumed Renovate knew what it was doing!)

My config is pretty simple for this repo, it started with `config:js-app` and  I've just added the extra config.

```
{
  "extends": ["config:js-app", "monorepo:angular1", "monorepo:babel", "packages:postcss"]
}
```

**Comment by carlosfunk** [comment]
Sure it looks like the branches have been removed.

**Comment by rarkins** [comment]
In that case it's like GitLab where PRs don't be closed by the platform even when you delete the branch out from under it. In GitHub, deleting the branch results in the PR being closed without further action. Action: adapt it like the GitLab equivalent.

**Comment by rarkins** [comment]
This will now be fixed in the next patch, however it doesn't know to go clean up those ones it left open before, so you'll need to decline those yourself now.
