### ISSUE TITLE
Automate datasource docs for sourceUrl, releaseTimestamp

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#28948]
### Describe the proposed change(s).

Blocked by #28947

Once it is completed, we should automatically populate this information into datasource docs pages like https://docs.renovatebot.com/modules/datasource/cdnjs/

**Comment by RahulGautamSingh** [comment]
![image](https://github.com/renovatebot/renovate/assets/76607510/3933eee2-8e6d-475c-a12e-a02a960d472f)

Is this close to the expected design for the new fields? I feel like the notes should be highlighted in some manner but can decide how? I am thiking of putting them inside `blockquote`.

Any suggestions @HonkingGoose ?

**Comment by HonkingGoose** [comment]
## Review of first draft

Thank you for the first draft of the design! Unfortunately it feels too much like a wall of text to me.

### Layout problem not your fault

This is not your fault, as we have the _same_ design problem in the _current_ datasource docs. Because we have less fields in the current datasource docs, I did not see the problem before. :see_no_evil: 

### Example of current layout style

For example, here's the "code" for the AWS Machine Image Datasource, in Markdown:

```markdown
# AWS Machine Image Datasource

**Identifier:** `aws-machine-image`

**Default versioning:** `aws-machine-image`

**Custom registry support:**

:heavy_check_mark: Custom registries are supported.

**Description:**

Rest of docs goes here.
```

We're using **bold text** as "headings". When there are four items, that works okay-ish. But now that you're adding more information in the `sourceUrl` and `releaseTimestamp` datasource docs, this strategy falls apart. With more information you really need a proper structure.

### Directions to try

Try both of these, and see which we like best:

- Use proper headings in a logical order
- Use proper headings, _and_ put basic information into _table_ format

In any case, we should use real proper headings instead of **bold text**.

#### Example of proper headings

```markdown
# AWS Machine Image Datasource

## Identifier

`aws-machine-image`

## Default versioning

`aws-machine-image`

## Custom registry support

Yes, custom registries are supported. // Note: I replaced the checkbox emoji with plain text

## Description

Rest of docs goes here.
```

#### Example of table layout

```markdown

# AWS Machine Image Datasource

## Table of values

| Name                    | Value               | Notes |
| ----------------------- | ------------------- | ----- |
| Identifier              | `aws-machine-image` |       |
| Default versioning      | `aws-machine-image` |       |
| Custom registry support | Yes                 |       | // Note: I replaced the checkbox emoji with plain text

## Description

Rest of docs goes here.
```

##### Alternative table-layout with separate notes headings

If we are likely to need more than a single sentence as a note, we could try this layout:

```markdown
# AWS Machine Image Datasource

## Table of values

| Name                    | Value               |
| ----------------------- | ------------------- |
| Identifier              | `aws-machine-image` |
| Default versioning      | `aws-machine-image` |
| Custom registry support | Yes                 | // Note: I replaced the checkbox emoji with plain text

### Notes about table items

#### Note about table item 1

Note for table item 1.
Another sentence about table item 1.
Final sentence about table item 1.

#### Note about table item 2

Note for table item 2.
Another sentence about table item 2.
Final sentence about table item 2.

#### Note about table item 3

Note for table item 3.
Another sentence about table item 3.
Final sentence about table item 3.

## Description

Rest of docs goes here.
```


### Personal preference

I'm leaning towards the "proper headings and _table_ layout, if we have short notes.

**Comment by RahulGautamSingh** [comment]
Here's the drafts:

**Table only**
![image](https://github.com/renovatebot/renovate/assets/76607510/6f8e548c-1d7c-4ed5-8c42-2a66df108d9a)

**Table followed by notes** 
![image](https://github.com/renovatebot/renovate/assets/76607510/b6596907-0495-4ac9-b3a9-5abb4af667a4)

**Comment by HonkingGoose** [comment]
I like the table with the notes in the table best.

The table with notes separate works also, but it takes up more space. And having a table with two columns feels a bit weird.

**Comment by RahulGautamSingh** [comment]
While I am at it, I should also change the versioing docs to use proper heading.
