### ISSUE TITLE
Renovate attempted to automerge immediately after branch was created

### ISSUE THREAD

**Issue by stevenzeck** [renovatebot/renovate#2948]
**What Renovate type are you using?**
Renovate CLI, Renovate GitHub App, or Renovate Pro?

Renovate GitHub App

**Describe the bug**

I'm finding inconsistencies for when Renovate attempts to automerge.  In the example I have (logs below), it found a dependency to update, updated the package.json files, created a branch, then immediately did the checks.  At that point, what was returned is below, so it attempted to merge.

When I curl to see what is returned by check-runs now, it has 5 checks, some of which are in_progress/null and others completed/success for the state and conclusion respectively.  So it seems like it is doing the checks before the checks even exist.  This conflicts when a repo has GitHub branch protections for one of those checks, as merging will be rejected .

**Did you see anything helpful in debug logs?**
If you are using the Renovate App, log into https://renovatebot.com/dashboard and locate the correct job log for when the problem occurred (e.g. when the PR was created).

https://github.com/Unibeautify/beautifier-sqlformat/pull/33
https://gist.github.com/stevenzeck/061338eda06fad4cb21b725eb3b5b602

```
DEBUG: branch status check result(dependencies=["@types/node"], branch="renovate/node-10.x")
{
  "state": "pending",
  "statuses": []              <<<------ length = 0
}
DEBUG: check runs result(dependencies=["@types/node"], branch="renovate/node-10.x")
{
  "checkRuns": [
    {
      "name": "Unibeautify - Branch",
      "status": "completed",
      "conclusion": "neutral"
    }
  ]
}
```

**To Reproduce**

1.  Create repository with Travis CI integration, and branch protect master with Travis CI - Branch.
2.  Configure Renovate to `"automerge": true` and `"automergeType": "branch",`
3. Wait for a dependency to be updated

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rarkins** [comment]
If Renovate attempts to merge and it is rejected because of branch protection, then that's showing the system *working*, not failing.

We can probably skip automerge attempts immediately after PR creation (I thought I had already made that change actually, just for efficiency reasons), but that doesn't solve the race condition you describe.

The race condition is that checks may be delayed an unknown amount of time, and any solution needs to account for that. It's quite possible that at times the checks (e.g. from Travis CI) might not start showing up for minutes or longer, and it's quite possible that Renovate could run again in that time, e.g. if triggered by a webhook. So even if you skip automerge attempts on the initial Renovate run when the PR is created, the race condition could still be in effect on the very next run.

Ultimately, the solution is branch protection and it sounds like that's what you have. We could and probably will get smarter about understanding the branch protection, but it's less API hits for us just to attempt to merge and be rejected than to iterate through the API.

So to summarise my view:
> So it seems like it is doing the checks before the checks even exist.

This can happen too even after many seconds or minutes after the PR is created - not all check runs show up as "in progress" immediately, that's just part of the decoupled GitHub/CI architecture.

> This conflicts when a repo has GitHub branch protections for one of those checks, as merging will be rejected .

I don't think of this as conflicting, I think of it as working. The next time Renovate runs, either:
- Check runs will have showed up, Renovate will see they are in progress, and not attempt to merge yet, or
- Check runs will have completed, be green, and Renovate will merge

Either way the above seems to achieve the desired result.

But is there any further *problem* this is causing or risk that I'm perhaps not understanding?

**Comment by stevenzeck** [comment]
> The race condition is that checks may be delayed an unknown amount of time, and any solution needs to account for that. It's quite possible that at times the checks (e.g. from Travis CI) might not start showing up for minutes or longer, and it's quite possible that Renovate could run again in that time, e.g. if triggered by a webhook. So even if you skip automerge attempts on the initial Renovate run when the PR is created, the race condition could still be in effect on the very next run.

> Ultimately, the solution is branch protection and it sounds like that's what you have. We could and probably will get smarter about understanding the branch protection, but it's less API hits for us just to attempt to merge and be rejected than to iterate through the API.

I think that summarizes this issue.  Ultimately I want `master` to always pass CI builds, so I protect it by saying **Travis CI - Branch** is required to pass before a branch can be merged into master.

So I almost need a way to tell Renovate that hey, master is protected by so and so, please wait until that succeeds before attempting to automerge.  However if it fails, go ahead and create a PR.  Maybe that's where [requiredStatusChecks](https://renovatebot.com/docs/configuration-options/#requiredstatuschecks) could be used?  Right now it's creating the PR because not all of the checks are present in the API response from GitHub, but the merge is rejected due to branch protection (one or more of which are the checks themselves protecting it).

**Comment by rarkins** [comment]
OK, I think I understand better! The problem for you is that you want branch automerge, but Renovate is failing branch automerge and creating a PR instead? I missed that part first time around.

I completely agree that should be how it works. In fact, I previously added some code to try to detect when the failure was due to status checks and *not* create PR, so maybe we need to extend that check a bit.

Here is the relevant line in your log: https://gist.github.com/stevenzeck/061338eda06fad4cb21b725eb3b5b602#file-renovate-log-12122018-log-L565

And here's where we should have been detecting that: https://github.com/renovatebot/renovate/blob/079afe1820eb14cd728bb023328de192c52f8fae/lib/workers/branch/automerge.js#L26-L28

**Comment by rarkins** [comment]
It looks like our string match needed to be extended, or maybe GitHub changed their error message since the first time it was implemented. Either way, thanks for the heads-up, logs, discussion, etc - should be rolled out into the app within the hour and hopefully by the next time you have a branch automerge attempted.

**Comment by stevenzeck** [comment]
Ah, yeah sorry I should have been clearer there, it is for branch automerge.  I found a gist from an earlier discussion where the message was:  [3 of 3 required status checks are expected. (422)](https://gist.github.com/stevenzeck/f1185da90a8f9c0a49f5e6ae77926f87#file-unibeautify-cli-119-log-L616-L656).  And as you mentioned for this one, the message is:  [Required status check \"Travis CI - Branch\" is expected. (422)](https://gist.github.com/stevenzeck/061338eda06fad4cb21b725eb3b5b602#file-renovate-log-12122018-log-L528-L567).  So maybe it's a different message depending on how many protections you have?

Thanks for the quick response!
