### ISSUE TITLE
Question: What happens when vulnerabilities are reported

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/renovate#2951]
**What would you like Renovate to be able to do?**
I was curious what renovate actually does when a vulnerability is submitted to NPM? The [`event-stream`](https://arstechnica.com/information-technology/2018/11/hacker-backdoors-widely-used-open-source-software-to-steal-bitcoin/) issue from this month made me think about this issue in particular. 

One option is to attempt to get the system in a clean audit state which would require possibly downgrading a dependency to the last known clean state.

Another option is to wait for the next update which would hopefully have a a clean audit state.

**Describe the solution you'd like**
I'm unsure which solution I would personally prefer, more just a general question of how renovate listens to audit issues.

**Describe alternatives you've considered**
N/A - This is just a question

**Additional context**
We already have a full CI/CD solution with automatic deployments which checks the npm audit status. Developers are still allowed to manually deploy an audit failing build but automatic deployments will fail. It was more a question of how Renovate would handle an existing package version having a vulnerability reported on it. If renovate does backtrack the version to before the latest vulnerability then our deployment should always have a clean audit (barring deployment time). If renovate does not, then we possibly have to manually deploy a previous version to avoid the vulnerability.

**Comment by rarkins** [comment]
Generally, Renovate's vulnerability functionality piggybacks on GitHub's vulnerability alerting and DB (for GitHub repositories only, naturally). We are not currently leveraging npm's own DB, but that's in planning.

Each time Renovate runs, it queries GitHub to see if the repo has vulnerability alerts. If found, it adds some internal package rules to flag that package/version as vulnerable. Doing so then means some [vulnerability defaults](https://github.com/renovatebot/renovate/blob/0dd52209b91559fa4ad955d762e5aea1fb728135/lib/config/definitions.js#L796-L807) are applied, such as breaking it out of any grouping and ignoring any schedules that might restrict the PR from being opened.

In the `event-stream` case, I think one of npm's earliest actions was to remove the offending version from the registry. Also it was a bit different from usual because it was an "insider" attack - there wasn't actually a "new" non-major version to update to. But in this case if you are using version X and version X disappears off the registry, Renovate creates a "roll back" PR.

**Comment by k2snowman69** [comment]
Thanks for the information! This will help me convince my team to onboard renovate :-)
