### ISSUE TITLE
Correctly name PR titles based on dependency types

### ISSUE THREAD

**Issue by manniL** [renovatebot/renovate#3013]
**What would you like Renovate to be able to do?**

Correctly name PRs titles based on the type of dependency (dependency, peerDependency or devDependency)

**Example**: https://github.com/nuxt/eslint-config/pull/21
Title: `chore(deps): update dependency eslint to v5.11.1`
Ideal title: ` chore(deps): update peerDependency eslint to v5.11.1`

Related issues:
#979
#1194

**Comment by rarkins** [comment]
Add this config:

```
"commitMessageTopic": "{{prettyDepType}} {{depName}}”
```

**Comment by manniL** [comment]
@rarkins Sorry to bug you again but somehow this doesn't work :thinking:  (https://github.com/nuxt/renovate-config-nuxt/blob/master/package.json#L25)

**Comment by rarkins** [comment]
Do you have an example PR I can look at?

**Comment by manniL** [comment]
@rarkins Sure, for example [this one](https://github.com/Developmint/nuxt-purgecss/pull/27). It only contains dev dependencies :relaxed:

**Comment by rarkins** [comment]
So just to be clear one thing up, the term "dependency" was meant to mean generically dependency and not specifically package.json>dependencies. 

Anyway the PR you point to has its PR title generated entirely differently without using commitMessageTopic. It's because of [this](https://github.com/nuxt/renovate-config-nuxt/blob/312687ad8d8d6c7a91c66ed4f637c6fd2dd2d222/package.json#L30) rule which pulls from [this definition](https://github.com/renovatebot/presets/blob/f0cbdbcf230879423ec71bf73c3300298ad41911/packages/renovate-config-group/package.json#L56).

If you wanted to write your own rule that separated devDependencies and dependencies into separate PRs then you could name them as such, but for now with the rule you have, the are (potentially) grouped together while the PR title remains static. It's not something feasible to somehow detect they are all devDependencies and switch the PR title - it's beyond the capabilities of Renovate's templating capabilities. As such, this specific case is a can't fix,  unless you change config and potentially have separate PRs for dependencies and devDependencies - in which case they can be named appropriately.

One last disclaimer: sometimes the flexibility of Renovate's config/templating can achieve results I hadn't anticipated, but right now I can't think of a way to do what you want. Although you could define the prTitle in that rule as "all non-major {{depType}}" you'd run the risk of it saying "devDependencies" sometimes when you have a mix of both.

**Comment by manniL** [comment]
@rarkins I understand! Many thanks for the valuable insights :relaxed:
