### ISSUE TITLE
Support Artifactory docker authentication

### ISSUE THREAD

**Issue by Aghassi** [renovatebot/renovate#3059]
**What would you like Renovate to be able to do?**
Currently, we host Renovate internally and run it on a slew of projects. Some point to the external docker registry, and others can point to our internal mirror/enterprise registry. Our expectation would be that in all cases, the bot knows how to pin and upgrade SHAs as well as different containers. Right now, I get `406` errors when trying to update CircleCI configs that contain an internal registry endpoint. To my understanding, it is an all or nothing process. Either everyone uses the registry or no one does.

**Describe the solution you'd like**
I'd like to be able to provide recognition for our internal registry url (something like `docker.enterprise.com`) as well as the necessary credentials (username and password) to be able to look up containers. I'd also like the current ability of pinning containers in CI configs to transfer over when using an internal mirror. However, if I switch to a repo using a public mirror, the functionality should remain the same as it is today.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rarkins** [comment]
Hi @Aghassi the best first step is to first make sure our Docker auth is compatible with your docker registry. Can you test a basic `Dockerfile` with the CLI and the simple Docker auth approach (e.g. `DOCKER_USERNAME`, `DOCKER_PASSWORD`) so we have a baseline to base off? I don't think this is related to CircleCI files at all, so that can be the last thing we eventually confirm.

**Comment by Aghassi** [comment]
Yes the package I'm using is https://hub.docker.com/r/circleci/node/

--
~David Aghassi
