### ISSUE TITLE
renovate-cli just deleted all my branches and just closed all my MR on gitlab

### ISSUE THREAD

**Issue by xuchaoying** [renovatebot/renovate#3129]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**

After running removate, it just deleted all branches except those start with `renovate/`, and just closed all 
MRs except those opened by renovate itself.

**Did you see anything helpful in debug logs?**

Here is the log info:

```
$ ./node_modules/renovate/lib/renovate.js --platform gitlab --endpoint xxx --token xxx repoName

...
...
INFO: Deleting orphan branch (repository=repoName, branch=111-modal-chrome)
INFO: Deleting orphan branch (repository=repoName, branch=138-tabpane-renderonchosed)
INFO: PR autoclosed (repository=repoName)
       "prNo": 486,
       "prTitle": "Resolve \"mr title\""
...
```

The bug version is 14.3.24, and it works fine in 14.3.15.

**Comment by rarkins** [comment]
I'm so sorry! I think it must have been caused by this change: https://github.com/renovatebot/renovate/commit/5aa73a16c90951986e3dad909814954cfcdb6547

I've pushed some extra code to master just now to do an additional filter on branchPrefix like we had before, but unfortunately it can't undelete your branches, so I'm really sorry.

What version of GitLab are you running? CE/EE and which version?

Cc @leipert

**Comment by xuchaoying** [comment]
It's GitLab Community Edition 10.5.8.

I've restored those branches luckily @rarkins

**Comment by rarkins** [comment]
@xuchaoying I'm glad to hear you could restore.

@leipert I guess maybe the `search` parameter was ignored in earlier versions?

**Comment by leipert** [comment]
@rarkins That could be true... Sorry for that happening @xuchaoying! 

I haven't checked it with 10.5, as the version is quite old. GitLab [officially recommends](https://docs.gitlab.com/ee/policy/maintenance.html#upgrade-recommendations) running the latest stable. Security updates are generally backported 2 releases, but other than that typically not.

No excuse for that slipping, the next time I'll do GitLab specific updates, I'll have a look into older versions as well.

@rarkins What versions of GitLab do you want to officially support with renovate?

**Comment by rarkins** [comment]
@leipert I haven't needed to think about GitLab releases since the transition to the new API version, which was a little painful. So right now it's kind of "as many as possible until the point there's a new feature we really want to start using exclusively".

**Comment by leipert** [comment]
@rarkins I did some more research and it seems "like an accident" that the feature was exposed, because the branch finder was adjusted rather recently (3 months ago)...

Anyway, the guard you wrote is a good one. 🙇 

- https://gitlab.com/gitlab-org/gitlab-ce/commit/ab5e8dc8800886ca206ee9e6ffe80026b319063c
