### ISSUE TITLE
Refactor: rewrite lib/datasource/github to use regular "got"

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3142]
Rather than [using the gh-got-wrapper](https://github.com/renovatebot/renovate/blob/d8335bbad7484f880885c8d77f405556dd121466/lib/datasource/github/index.js#L1), instead use the `got` package directly. Will need to specify `json: true`, etc. Most of the other datasources do it this way.

**Comment by Dmitry9** [comment]
Please clarify. Do you want:
1) replace `gh-got` package with `got` (https://github.com/sindresorhus/got). At the same time you want to have all the checks left in place from the line:
/home/dmitry/WebProjects/forks/renovate/lib/platform/github/gh-got-wrapper.js
to a line:
/home/dmitry/WebProjects/forks/renovate/lib/platform/github/gh-got-wrapper.js
So the task is just replacing one third-party library to another (of course API is a little bit different). So that wrapper stays but internally uses another package.
2) Additionally, to point 1 you want to rearrange the logic inside above lines in some manner. Maybe extract this logic into a separate file or any other action.

Because today is the first time I set up a local environment for this project I don't have an exclusive understanding of every piece of logic in the project, any clarification will help.

**Comment by rarkins** [comment]
Remove this line: https://github.com/renovatebot/renovate/blob/d8335bbad7484f880885c8d77f405556dd121466/lib/datasource/github/index.js#L1

Replace it with `const got = require('got');`

And then update the code below to work. You can kind of "copy" how most of the other datasource files do it directly with `got`, e.g. https://github.com/renovatebot/renovate/blob/master/lib/datasource/cargo/index.js

**Comment by Dmitry9** [comment]
This PR is not intented to be merged right-away.
Please see the [PR ](https://github.com/renovatebot/renovate/pull/3151);
From https://github.com/renovatebot/renovate/blob/master/docs/local-development.md
`Do not let coverage put you off submitting a PR! Maybe we can help, or at least guide. Also, it can be good to submit your PR as a work in progress (WIP) without tests first so that you can get a thumbs up from others about the changes, and write tests after.`

Dmitry9test/renovate-test - is a real GitHub account which I created for testing purporses. 
I fixed all erroros that arives when I run
```shell
yarn start Dmitry9test/renovate-test
```
and 
```shell
yarn debug Dmitry9test/renovate-test
```
But I have a lot of failed tests due to snapshot missmatch. So please tell me from where should I start to fix tests errors.

**Comment by rarkins** [comment]
Check out master branch, make sure you’re on the latest master 
Run “yarn”
Run “yarn test”

You do not need and should not use any repository just for that. 


You should get tests passing and 100% coverage. If not, raise an issue.
