### ISSUE TITLE
"automerge": true does not work on gitlab? (I think it used to)

### ISSUE THREAD

**Issue by NullVoxPopuli** [renovatebot/renovate#3149]
**What Renovate type are you using?**
Renovate CLI, Renovate GitHub App, or Renovate Pro?

GitLab

**Describe the bug**

automerge used to work, now it does not.my repo is here: https://gitlab.com/NullVoxPopuli/emberclear (open source)

**Did you see anything helpful in debug logs?**
I am overwhelmed by the debug logs and don't know what to search for :-\
https://renovatebot.com/dashboard#gitlab/NullVoxPopuli/emberclear

**To Reproduce**
unknown

**Expected behavior**
When C.I. passes, the PR should be merged

**Comment by rarkins** [comment]
Re: the logs. First filter by branch, and then look for any line mentioning "automerge"

**Comment by rarkins** [comment]
I checked the logs and both your branches on the last run printed this message: https://github.com/renovatebot/renovate/blob/0355b7558e86a2f8bf834f69e5d8ed4806e1e488/lib/platform/gitlab/index.js#L693

This means that the GitLab API is returning `pr.merge_status === 'cannot_be_merged'`

It's not possible to troubleshoot deeper now because the MRs are merged, but naturally Renovate won't merge if it thinks the API is returning that they can't be merged. It may not be a Renovate problem at all, but next time you have a PR open that you think should be merged then please query the GitLab API to check what metadata is returned. Comment here if you think it's Renovate's mistake and I'll reopen.

**Comment by NullVoxPopuli** [comment]
Here is one with an unmerged PR: https://renovatebot.com/dashboard#gitlab/NullVoxPopuli/emberclear/43148426

babel-eslint


The CI passed :/

**Comment by rarkins** [comment]
I've added a debug of the `err` that GitLab returns, in case it has any fields in it that give us a hint as to why. It should be live in the hosted app within 1-2 hours.

**Comment by NullVoxPopuli** [comment]
this is what I see: 
![image](https://user-images.githubusercontent.com/199018/52166027-383eb000-26d6-11e9-9da7-1309223e3bbe.png)

**Comment by NullVoxPopuli** [comment]
so, according to GitLab's permissions table:
![image](https://user-images.githubusercontent.com/199018/52166042-59070580-26d6-11e9-9ca1-d0f7d676c142.png)

(see at the bottom)
I wonder if this is an issue with them? I'll ask their twitter

**Comment by leipert** [comment]
@NullVoxPopuli / @rarkins I am having a look 👀

**Comment by leipert** [comment]
I have found this issue, but it references an older version:
https://gitlab.com/gitlab-org/gitlab-ce/issues/56981

**Comment by leipert** [comment]
So the button in an MR uses another API, and not the publicly documented one (`/v4/`). I am trying to reproduce and file an issue accordingly.

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/52167383-72ca3c00-271a-11e9-9bc5-7bbb5b8a3dab.png)

**Comment by leipert** [comment]
@NullVoxPopuli Could it be that your `master` branch is protected? https://docs.gitlab.com/ee/user/project/protected_branches.html

Because then only maintainers are able to merge! Could you check your settings and set "Allowed to merge" to "Maintainers and Developers"?
![screenshot 2019-02-02 at 19 05 20](https://user-images.githubusercontent.com/2906107/52167580-85924000-271d-11e9-8159-fe7e96f252cf.png)

**Comment by NullVoxPopuli** [comment]
that seemed to do it. :+1: thanks!
