### ISSUE TITLE
new PR uses branch created from old default branch

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3205]
**What Renovate type are you using?**
Renovate Pro

**Describe the bug**
- I merge a renovate PR (which contains some my manual fixes)
- renovate opens a new PR with upgraded dependencies which new versions became available after opening the previous PR
- unfortunately the renovate branch (e.g. `renovate/all`) is out of date so I have to merge the default branch to it
- sometimes there are even some conflicts
- `* If you want to rebase/retry this PR, check this box` checkbox seems to work but there is a huge delay

<img width="616" alt="screen shot 2019-02-12 at 22 35 15" src="https://user-images.githubusercontent.com/20856232/52669523-86de1c80-2f16-11e9-89a4-a542b102acd6.png">

**Comment by rarkins** [comment]
Most foolproof solution is to delete branches after you merge PRs. But I can look at the logs too if you can tell me the repo and ideally log id found via dashboard

**Comment by piotr-s-brainhub** [comment]
@rarkins 

I deleted `renovate/all` there
<img width="1028" alt="screen shot 2019-02-12 at 23 26 00" src="https://user-images.githubusercontent.com/20856232/52672284-b3e1fd80-2f1d-11e9-9d3d-c30dda7cf8bf.png">

it's `dmx-io/dmx-reports` repo;
the old PR - https://github.com/dmx-io/dmx-reports/pull/15
the new PR - https://github.com/dmx-io/dmx-reports/pull/16

**Comment by rarkins** [comment]
> * unfortunately the renovate branch (e.g. `renovate/all`) is out of date so I have to merge the default branch to it

If you want Renovate to rebase out of date PRs automatically then configure `"rebaseStalePrs": true` in your config and Renovate will make sure PRs never remain behind `master` for long.

If you want to trigger any rebase manually, click the checkbox instead of updating the branch manually

> * sometimes there are even some conflicts

If there are conflicts, and you have updated a branch manually, then Renovate will not be able to fix the conflicts automatically. This is why you should use the checkbox.

> * `* If you want to rebase/retry this PR, check this box` checkbox seems to work but there is a huge delay

This should always happen quickly. This last point is the only thing I can help you with in this list, so please provide more details if you experience it happening again. It's important that either (a) you give me the exact time that things happened, or (b) you log into https://renovatebot.com/dashboard and locate the exact Job ID to look at.

**Comment by rarkins** [comment]
Please add `rebaseStalePrs=true` to your config, this will tell Renovate to always keep them up to date with the base branch. If a problem happens again, please raise a new issue referencing this one and do not manually update the branch until after there is a chance to debug.

**Comment by piotr-s-brainhub** [comment]
@rarkins 

- renovate opened https://github.com/dmx-io/dmx-reports/pull/22
- I clicked `* If you want to rebase/retry this PR, check this box` about 16 hours ago
- it's still not rebased

Recently usually rebasing takes between a few seconds and a few minutes but this one PR is still not rebased.

**Comment by rarkins** [comment]
If you do a refresh of the PR page, is the box checked or unchecked now?

**Comment by piotr-s-brainhub** [comment]
@rarkins 

after refresh it's still checked

**Comment by rarkins** [comment]
Hi, this was fixed by https://github.com/renovatebot/renovate/issues/3221

I confirmed that your PR 22 was rebased on the next run after this fix was applied.
