### ISSUE TITLE
Add "hex" manager (Elixir/Erlang)

### ISSUE THREAD

**Issue by KonstantinKurganov** [renovatebot/renovate#3212]
Add support of parsing/ extract hax packages.
Implement hex manages.

**Comment by rarkins** [comment]
@KonstantinKurganov thanks for getting this started. Can you start filling in a manager readme ([link](https://raw.githubusercontent.com/renovatebot/renovate/feat/newmanager/lib/manager/newmanager/readme.md)) so that we can work out requirements?

**Comment by KonstantinKurganov** [comment]
@rarkins Ok, I'll do it!

**Comment by KonstantinKurganov** [comment]
@rarkins there are deps like 
 `{:cowboy, github: "ninenines/cowboy"},`
where is specified repo to fetch dep from .
so what king of fields dep object should have in this case?

**Comment by rarkins** [comment]
@KonstantinKurganov you can check out the npm manager (lib/manager/npm) extract function for examples like that. In npm there can be both packages from npmjs (default) but also ones from github and the fields should be the same.

In the above example you give though I don't think we'll "renovate" it because there is no version specified, but you can extract it anyway.

**Comment by KonstantinKurganov** [comment]
@rarkins thank you, Ill take a look!

**Comment by KonstantinKurganov** [comment]
@rarkins should we include symbols like `^ ~>` in dep.currentValue?

**Comment by rarkins** [comment]
Yes. Take a look at the composer package manager or terraform one for the best examples of something to copy, as npm is the most complex and so harder to understand.

**Comment by sobolevn** [comment]
This is a blocker for me to migrate from dependabot to renovate.
