### ISSUE TITLE
Only a section of the workspace is updated

### ISSUE THREAD

**Issue by samouss** [renovatebot/renovate#3235]
**What Renovate type are you using?**

Renovate GitHub App

**Describe the bug**

We use Renovate to keep our dependencies up to date on [our project](https://github.com/algolia/react-instantsearch). We use Lerna & Yarn workspace features. Recently we update the value of the workspace to change one of the path. Since then only the older path is taken into account in the update. It means that when we install the project locally the `yarn.lock` is outdated.

You can take a look at this [PR](https://github.com/algolia/react-instantsearch/pull/2028). The dependencies `react` & `react-dom` are present at the top level but also under `website/example/*`. The PR only updates the top level package. It seems that the issue started with this [PR](https://github.com/algolia/react-instantsearch/pull/2027). It removes dependencies from the `yarn.lock` that are only listed inside the `website/examples/*`.

**Did you see anything helpful in debug logs?**

I looked at the logs it seems that Renovate detect that it's a monorepo but ignore a part of the tree.

**Expected behavior**

All the workspace should be taken into account to avoid `yarn.lock` issues.

**Comment by rarkins** [comment]
I think this might be because we're ignoring `examples` as a pattern. I'll get back to you on the best way to work around this.

**Comment by rarkins** [comment]
Please do the following:

#### Update renovate.json

Add the following:
```
  "ignorePresets": [
    ":ignoreModulesAndTests"
  ],
```

#### Add back any ignorePaths you wish (optional)

Renovate will now check in both `examples/*` as well as `website/examples/*`. When I tested this on a fork of your repo I noticed 30+ new PRs raised. If you don't want all of these files processed then you need to add them to your own `ignorePaths` config.

#### Remove nested Renovate config

Renovate doesn't support `renovate` config inside nested `package.json` files. You need to remove it like in this commit: https://github.com/renovate-tests/react-instantsearch/commit/36824c7074f0047228a878560fa93a951bc099a1
Otherwise you'll get a config error and Renovate won't run.

**Comment by rarkins** [comment]
You can see the React examples all updated here: https://github.com/renovate-tests/react-instantsearch/pull/4/files

**Comment by samouss** [comment]
Awesome!!! Thanks for the explanation and the fix.
