### ISSUE TITLE
no PR opened on schedule

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3242]
**What Renovate type are you using?**
Renovate App

**Describe the bug**
my `renovate.json`:
```json
{
  "commitMessage": "[renovate] update all dependencies",
  "groupName": "All",
  "labels": ["renovate"],
  "npmToken": "<redacted>",
  "rangeStrategy": "bump",
  "schedule": "before 10pm on the 19th day of the month"
}
```
- I set the `schedule` value as `before 10pm on the 19th day of the month` on 9:19 PM UTC, February 19, 2019.
- a moment before updating `renovate.json`, I published new `@dmx/npm-fca` version
- there's still no renovate PR

**Did you see anything helpful in debug logs?**
I see this in logs:
```
DEBUG: 1 result(s): 1.10.120 (dmx_base)(dependency="dmx_base")
DEBUG: 1 result(s): ^1.8.13 /npm-fca)(dependency="@dmx/npm-fca")
DEBUG: 1 result(s): ^5.4.14 (mongoose)(dependency="mongoose")
DEBUG: 1 result(s): ^2.0.0 (joi-us-zipcode)(dependency="joi-us-zipcode")
DEBUG: 1 result(s): >=v11.10.0 (node)(dependency="node")

...

DEBUG: Compiling branchName: renovate/all(branch="renovate/all")
DEBUG: commitMessage: "[renovate] update all dependencies"(branch="renovate/all")
DEBUG: prTitle: "[renovate] update all dependencies"(branch="renovate/all")
DEBUG: generateBranchConfig(1)(branch="renovate/major-all")
DEBUG: hasGroupName: true(branch="renovate/major-all")
DEBUG: groupEligible: false(branch="renovate/major-all")
DEBUG: useGroupSettings: false(branch="renovate/major-all")
DEBUG: Compiling branchName: renovate/major-all(branch="renovate/major-all")
DEBUG: commitMessage: "[renovate] update all dependencies"(branch="renovate/major-all")
DEBUG: prTitle: "[renovate] update all dependencies"(branch="renovate/major-all")
DEBUG: config.repoIsOnboarded=true
INFO: Processing 3 branches: renovate/all, renovate/docker-all, renovate/major-all
DEBUG: Retrieving PR list
DEBUG: Retrieved 410 Pull Requests
DEBUG: PR hourly limit remaining: 5
DEBUG: processBranch with 2 upgrades(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: Retrieving branchList(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: branchExists(renovate/all)=false(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: getBranchPr(renovate/all)(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: findPr(renovate/all, null, open)(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: branchExists=false(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: Branch has 2 upgrade(s)(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: recreateClosed is true(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: Checking schedule(before 10pm on the 19th day of the month, null)(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: Checking 1 schedule(s)(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: Checking schedule "before 10pm on the 19th day of the month"(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
{
  "parsedSchedule": {
    "schedules": [
      {
        "t_b": [
          79200
        ],
        "D": [
          19
        ]
      }
    ],
    "exceptions": [],
    "error": -1
  }
}
DEBUG: schedule.D(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
{
  "schedule_D": [
    19
  ]
}
DEBUG: Does not match schedule because 82127 is later than 79200(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: Package not scheduled(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
INFO: Skipping branch creation as not within schedule(dependencies=["@dmx/npm-fca","mongoose"], branch="renovate/all")
DEBUG: processBranch with 1 upgrades(dependencies=["dmx_base"], branch="renovate/docker-all")
DEBUG: branchExists(renovate/docker-all)=false(dependencies=["dmx_base"], branch="renovate/docker-all")
DEBUG: getBranchPr(renovate/docker-all)(dependencies=["dmx_base"], branch="renovate/docker-all")
DEBUG: findPr(renovate/docker-all, null, open)(dependencies=["dmx_base"], branch="renovate/docker-all")
DEBUG: branchExists=false(dependencies=["dmx_base"], branch="renovate/docker-all")
DEBUG: Branch has 1 upgrade(s)(dependencies=["dmx_base"], branch="renovate/docker-all")
DEBUG: recreateClosed is false(dependencies=["dmx_base"], branch="renovate/docker-all")
DEBUG: findPr(renovate/docker-all, [renovate] update all dependencies, !open)(dependencies=["dmx_base"], branch="renovate/docker-all")
DEBUG: Found PR #404(dependencies=["dmx_base"], branch="renovate/docker-all")
DEBUG: Found closed PR with current title(dependencies=["dmx_base"], branch="renovate/docker-all")
```
but I cannot clearly see what I should do

So I have the following questions:
- Is `before 10pm on the 19th day of the month` a valid value? (I wrote it according to https://renovatebot.com/docs/presets-schedule/#schedulemonthly but I found only one example of a monthly schedule `first day of the month`)
- If I use an invalid `schedule` value, will renovate open an issue in my repo, informing about that?
- If I configure correctly `schedule` value, will renovate open a PR updating all the dependencies to the newest version on this schedule?
- If I type `before` inside `schedule` value, what's the probability the PR will be opened after the specified time?
- If I type `before` inside `schedule` value, what's the average time between the PR opening and the specified time?
- If I closed a PR updating a specific dependency, will renovate never update this dependency (I hope that's not true because if I don't want to update a given dependency, I add it to `ignoreDeps` in `renovate.json`)?

**Comment by rarkins** [comment]
If you don't configure a time zone then it defaults to GMT. This might explain why you got `Does not match schedule because 82127 is later than 79200`. These values are seconds since midnight.

> * Is `before 10pm on the 19th day of the month` a valid value? (I wrote it according to [renovatebot.com/docs/presets-schedule/#schedulemonthly](https://renovatebot.com/docs/presets-schedule/#schedulemonthly) but I found only one example of a monthly schedule `first day of the month`)

It appears to be

* If I use an invalid `schedule` value, will renovate open an issue in my repo, informing about that?

yes

* If I configure correctly `schedule` value, will renovate open a PR updating all the dependencies to the newest version on this schedule?

The schedule determines when Renovate creates the *branch*. Sometimes PRs can come after (e.g. if you configure Renovate to only open once the tests are non-pending).

* If I type `before` inside `schedule` value, what's the probability the PR will be opened after the specified time?

You should leave a minimum of one hour in a schedule, because Renovate is configured to process every repository on an hourly schedule (+ whenever webhooks trigger it)

* If I type `before` inside `schedule` value, what's the average time between the PR opening and the specified time?

It's an hourly schedule, so you it can be anywhere from 1-60 minutes typically, with an average of 30. Your schedule doesn't "trigger" Renovate especially.

* If I closed a PR updating a specific dependency, will renovate never update this dependency (I hope that's not true because if I don't want to update a given dependency, I add it to `ignoreDeps` in `renovate.json`)?

If you close a PR, you will ignore that dependency's *version* forever (e.g. v1.2.1 is ignored, or v3 is ignored if it was a major update you closed). It does not ignore the *dependency* forever. Note that if you group dependencies together it is not always possible to close them to ignore. You will see a PR described as "immortal" in its description if so.
