### ISSUE TITLE
feat(bitbucket-server): caching

### ISSUE THREAD

**Issue by ViceIce** [renovatebot/renovate#3257]
We should optimize the caching behavior.

See #3252 #3256  for discussions.

- [x] after each commitFilesToBranch call getBranchPr with a cache bust option
- [ ] add tests

**Comment by ViceIce** [comment]
I've verified, that bbs increments the pr version, when you push new commits to the from branch

**Comment by ViceIce** [comment]
The same happens with updated to branch.

**Comment by rarkins** [comment]
Does it only increment when we make *file* updates rather than simply updating the PR description? Or both? Also if you’ve verified it then that must mean it also includes when you force push to a branch, like gitFs does. 

In our existing GitHub wrapper we have the option to ignore the cache, ie to cache bust any existing entry. Once we have the same thing here, we can call getBranchPr() with cache busting after any branch update so that the cached PR now has the correct version.

**Comment by ViceIce** [comment]
Both. I'm currently implement the cache busting. It works against BBS 5.2.6.

I'll add tests too, so it will need some time. 😁
