### ISSUE TITLE
go get: no install location for directory X outside GOPATH

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3285]
I'm seeing the occasional `go get: no install location for directory /mnt/renovate/gh/abc/def outside GOPATH` error in the app.

[`GOPATH` in Wiki](https://github.com/golang/go/wiki/GOPATH)

I'm not sure if we should be setting some env inside the `renovatbot/go` container or not.

@paultyng do you happen to know?

**Comment by paultyng** [comment]
I wonder if this is caused by using `GOPATH` at all, my understanding is that with modules [you no longer need to use this](https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support) and since it is being detected it is possibly causing problems?

You could force modules to be on with an environment variable or just move the working dir outside the `GOPATH` entirely.

Do you have an example project where this is happening?

**Comment by rarkins** [comment]
@paultyng unfortunately the repository I noticed this in is private, and I don't have contact details for this org. I'm wondering how this repo's configuration is somehow introducing `GOPATH` when our Docker container doesn't have it.

**Comment by paultyng** [comment]
I think you are inside the [GOPATH in the container though](https://github.com/renovatebot/docker-go/blob/a7f86f72e38477fa5e44070f9386707b2a2eaed0/Dockerfile#L18)? I agree its weird that this is an intermittent thing and not on all repos, not sure why that is. It may be worth explicitly setting `GO111MODULE=on`?

**Comment by rarkins** [comment]
Thanks, I'm going to try that
