### ISSUE TITLE
Bundler: incompatible marshal file format

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3286]
One repo in the app is failing with this error:

```
While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
    format version 4.8 required; 60.33 given
```

**Comment by rarkins** [comment]
@sleekybadger @bjeanes	do you have any idea why this might be happening?

**Comment by rarkins** [comment]
Searching this term gets lots of hits dating back until 2011. Solutions include removing `~/.gemrc` which is not applicable here.

**Comment by rarkins** [comment]
I'm wondering if there's a project `.gemrc` that we're not reading. But then in this comment it indicates that Bundler doesn't read it: https://github.com/bundler/bundler/issues/6633#issuecomment-406713977

**Comment by bjeanes** [comment]
Hmm... That's an odd one. Nothing comes to mind though 😔

**Comment by bjeanes** [comment]
Can you share the Gemfile.lock? To me it seems to imply that file is either corrupt or that some other artefact is.

For e.g., maybe they accidentally committed a merge conflict?

**Comment by Noxstahl** [comment]
Found that & worked for me !
from https://github.com/rubygems/rubygems/issues/1589

It seems bundler can't find sources for your gem.
It's probably because the remote sources are outdated. You can check your remote sources with gem env. I think the last of these old sources has now become unavailable:

  - REMOTE SOURCES:
     - http://gems.rubyforge.org/
     - http://gems.github.com
Since these are outdated, you should add https://rubygems.org as a source now to the gem env config. You can update the config with the following commands:

gem sources -r http://gems.rubyforge.org/
gem sources -r http://gems.github.com
gem sources -a https://rubygems.org/
When updated, gem sources -lshould return:

*** CURRENT SOURCES ***

https://rubygems.org/
Credits go to https://qiita.com/hidehiro98/items/bb6ed9bc109021034af0

**Comment by rarkins** [comment]
Thanks, I think you're right that the repo must have some corruption or outdated source. I may add debugging to Renovate's code to try to verify that.

**Comment by rarkins** [comment]
@bjeanes now found in covidence's main repo! I suspect it may not be because of any of the above ideas, but hopefully we can now at least debug it.

**Comment by rarkins** [comment]
@bjeanes were you able to notice the same problem in your repo?

**Comment by bjeanes** [comment]
Renovate has never successfully opened a Ruby PR against our app since the
first week or so, so i hadn't been pushing any attention, to be honest.

**Comment by rarkins** [comment]
I finally fixed this. I had some outdated sources in `~/.gemrc` in the ruby Docker images.

**Comment by SoundBoySelecta** [comment]
I had the same error even after adding the https://rubygems.org, then I commented out the old sources and it worked. 
:sources:
#- http://gems.rubyforge.org/
#- http://gems.github.com
- https://rubygems.org
