### ISSUE TITLE
Grouping of commits to upgrade Node has broken

### ISSUE THREAD

**Issue by denkristoffer** [renovatebot/renovate#3331]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Renovate's pull requests with Node upgrades have broken, as the changes seem to have been split into several PRs:

- Renovate job log #50613373 is a PR that upgrades the `node` engines field in our `package.json` files. 
- #50685060 is a PR that updates our Docker image digests.

Renovate is merging these "half-baked" PRs which leads to a broken build.

**Expected behavior**
These changes used to be bunched together into a single PR, which is what I expect.

**Comment by rarkins** [comment]
The engines version is looked up based on the github.com/nodejs/node releases, so it will always see PRs first. It usually takes time for Node.js updates to be published to Docker Hub, so you will see these after. I suggest you do not automerge Node.js because of this.

If the branch name was the same for both PRs, then the problem is your automerging rather than the grouping. Renovate can do nothing about the fact that the version available to engines is available faster than Docker Hub images.

So either:
- Do not automerge Node.js PRs. Instead merge them manually after you have checked all references are updated, or
- Add a test to your repo that makes sure that Node.js versions are in sync. That way automerge would be thwarted, and this might be more foolproof than the first way anyway

**Comment by rarkins** [comment]
So the question is: Were these put into separate branches, or the same? If separate branches then yes it seems like the grouping is not as expected - in which case I need a way to reproduce. If it's the same branch name, this is just a race condition as described above and you need to add a test or remove the automerge.

**Comment by denkristoffer** [comment]
Thanks @rarkins you're right, the branch names are the same so this must've simply been the first time that some of the changes were delayed. I'll disable automerging node.js for now 👍

**Comment by rarkins** [comment]
Thanks for letting me know!
