### ISSUE TITLE
renovate dismisses renovate-approve approval

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3381]
**What Renovate type are you using?**
Renovate GitHub App?

**Describe the bug**
- `renovate` opened https://github.com/dmx-io/dmx-auctions/pull/427
- a few seconds later `renovate-approve` approved this PR
- a few seconds later `renovate` force-pushed, dismissing the review

**Did you see anything helpful in debug logs?**
No.

**Expected behavior**
- IMO this force-push was redundant
- even if `renovate` force-pushes, `renovate-approve` should give another approval

**Screenshots**
<img width="703" alt="Screen Shot 2019-03-14 at 04 09 34" src="https://user-images.githubusercontent.com/20856232/54328691-27575780-460f-11e9-9643-cb03d6d3d2d9.png">

**Additional context**
This PR was opened after closing the previous PR and not deleting `renovate/all-dependencies` branch.

**Comment by rarkins** [comment]
Renovate is not actually dismissing the review - that's done automatically by GitHub only if you have chosen to enable this setting:

![image](https://user-images.githubusercontent.com/6311784/54337663-d86dea00-462f-11e9-90b1-d8974078b6c1.png)

It looks like Renovate Approve does not support this feature yet - it approves when the PR is created only.

I can't tell from the screenshot but any force push is because of a "rebase" being necessary. If you've configured rebasing when stale then Renovate must force push every time master is updated, for example.

Closing this because the title is "Renovate dismisses renovate-approve approval" and it's not actually Renovate doing it - it's GitHub, and it's doing what you've configured it to. I added this feature request to Renovate Approve: https://github.com/renovatebot/renovate-approve-bot/issues/10

**Comment by piotr-s-brainhub** [comment]
I know GitHub does it but I need this settings because when a human approves and there are some new commits, it should be approved again.

It would be fine if `renovate-approve` handled that.
