### ISSUE TITLE
I expect automerge only for dependencies with a given prefix

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#3387]
**What Renovate type are you using?**
Renovate GitHub App?

**Describe the bug**
Renovate shows `Automerge: Enabled.`.

My `renovate.json`:
```
{
  "automerge": false,
  "commitMessagePrefix": "[renovate] ",
  "labels": [
    "renovate"
  ],
  "npmToken": "<redacted>",
  "packageRules": [
    {
      "automerge": true,
      "packagePatterns": [
        "^@dmx/"
      ],
      "schedule": "at any time"
    },
    {
      "automerge": true,
      "managers": [
        "circleci"
      ],
      "schedule": "at any time"
    },
    {
      "groupName": "all minor/patch dependencies",
      "languages": [
        "js",
        "docker"
      ],
      "updateTypes": [
        "minor",
        "patch"
      ]
    }
  ],
  "rangeStrategy": "bump",
  "schedule": "before 3am on the first day of the month"
}
```

**Did you see anything helpful in debug logs?**
No.

**Expected behavior**
I would like a PR to be auto-mergeable only when it contains only `^@dmx/` packages and docker dependencies but when it updates also any other dependency (like here `@​octokit/rest`), it should be either non-auto-mergeable or a separate PR (with a different schedule) should be opened.

**Screenshots**
<img width="963" alt="Screen Shot 2019-03-15 at 01 11 57" src="https://user-images.githubusercontent.com/20856232/54399590-61803200-46bf-11e9-94c6-6b1780169e8c.png">

**Comment by rarkins** [comment]
A PR's automerge should only be enabled if automerge is enabled for every update within it: https://github.com/renovatebot/renovate/blob/940d3c472198edf361354ba2e15dc21cd48dc3f0/lib/workers/repository/updates/generate.js#L199

Let's solve your config in config-help first and then reopen this is it's still a problem. I think the problem is with the ordering of package rules I suggested to you previously.
