### ISSUE TITLE
Renovate commits are not signed anymore

### ISSUE THREAD

**Issue by KnisterPeter** [renovatebot/renovate#3447]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
The commits created by the renovate bot are not gpg signed anymore.
This prevents merging these requests if a repository requires signed commits.

**Did you see anything helpful in debug logs?**
No

**Comment by rarkins** [comment]
The app has partially migrated to using "gitFs" where it does a shallow clone of repos instead of picking individual files. This allows for a lot of advanced functionality now such vendored modules, go mod tidy, etc. Unfortunately for now we don't have signed commits supported! Coming soon.

Depends on #3053

**Comment by rarkins** [comment]
Commits from the app should be Verified from now on. Example from this repo:

![image](https://user-images.githubusercontent.com/6311784/55687346-1ed31200-596c-11e9-8db9-60f72d2e974b.png)

**Comment by KnisterPeter** [comment]
@rarkins Seems to be broken again.

You can take this as an example: https://github.com/KnisterPeter/tsdi/pull/519

**Comment by rarkins** [comment]
Ugh, sorry.

**Comment by rarkins** [comment]
Should be back for good now for any future commits/rebases/etc

![image](https://user-images.githubusercontent.com/6311784/55951761-4b32ab00-5c58-11e9-9e95-6fb78d9c9c16.png)
