### ISSUE TITLE
feat: Use official yarn install script for docker

### ISSUE THREAD

**Issue by ViceIce** [renovatebot/renovate#3451]
**What would you like Renovate to be able to do?**
Currently the docker image is using npm to install yarn, which is not a supported way.

**Describe the solution you'd like**
We should use the official yarn [install script](https://yarnpkg.com/en/docs/install#alternatives-stable) to install yarn in the docker image.

We should change
https://github.com/renovatebot/renovate/blob/002db29e585d3a51292594a0350f3b1d6e4be5bc/Dockerfile#L133

to 
```Dockerfile
RUN curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version ${YARN_VERSION}
```

@rarkins What do you think about this?

**Comment by ViceIce** [comment]
Another way would be the [debian](https://yarnpkg.com/en/docs/install#debian-stable) way

**Comment by rarkins** [comment]
I'm happy to change if you like the curl way and it works

**Comment by ViceIce** [comment]
Ok, I'm already testing 😁 

Looks like we need #839 for automating #3450

**Comment by rarkins** [comment]
Yep! I'm always a day or two of free time away from getting generic version extraction and updating working. It will support more than just Dockerfiles..

**Comment by ViceIce** [comment]
If we ommit the version number, we will always install the latest stable version. Would that be a better way until we can renovate the `ENV` variables?

**Comment by rarkins** [comment]
There could be a time where a Yarn update breaks things, which is why I prefer to have it deterministic. However I don't directly use this built docker image myself, so if you think it's better for users to be on the (stable) cutting edge, then I guess it's ok

**Comment by ViceIce** [comment]
Hm, ok. Some delay would be nice. I'm using the docker image for every day usage, but I'm thinking of switching to another method, because the image is very huge.

Is `binarySource=docker` still working?

**Comment by ViceIce** [comment]
Why renovate is not updating yarn dependency?

https://github.com/renovatebot/renovate/blob/b7776b5edc705f5247bf9f65642315a12238872f/package.json#L144

**Comment by rarkins** [comment]
> Is `binarySource=docker` still working?

Yes, but it's never been fully tested with docker as the base image. You would need to map in the docker sock as a volume so that the Docker container has the ability to generate sibling containers. Also the working directory within the Renovate container would need to be the same as on the host, so that Renovate knows how to map from host to sibling container. e.g. you can't run like `-v /abc:/def`, it needs to be like `-v /abc:/abc`.

I'll try to work on instructions for this soon.

> Why renovate is not updating yarn dependency?

I have `masterIssueApproval` set to true for this repo. It means I need to approve PRs in https://togithub.com/renovatebot/renovate/issues/2958 first before they're created.
