### ISSUE TITLE
Config validator fails with `devDependencies` option

### ISSUE THREAD

**Issue by LukasHechenberger** [renovatebot/renovate#3536]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
`renovate-config-validator` fails when I add `"devDependencies" { "automerge": true }` as described in the docs.
The error message 

**Did you see anything helpful in debug logs?**
The error message is:

```
package.json > renovate-config contains errors:

[
  {
    "depName": "Configuration Error",
    "message": "Invalid configuration option: devDependencies"
  }
]
Validating config.js
```

**To Reproduce**

1. Add `"devDependencies" { "automerge": true }` to renovate config
2. Run `renovate-config-validator` (via npm test script in my case)

**Expected behavior**
I expect the config to be valid, as I'm already using it without any issues. 

**Screenshots**
<img width="665" alt="image" src="https://user-images.githubusercontent.com/5802656/56034067-7b487f80-5d26-11e9-8f6e-2a5aace67471.png">

**Additional context**
[Failing test on CircleCI](https://circleci.com/gh/ls-age/renovate-config/182)
[Failing config on GitHub](https://github.com/ls-age/renovate-config/blob/automerge-dev/package.json)
[Config using `devDependencies` that works without any issues](https://github.com/atSCM/server-scripts/blob/master/package.json)

**Comment by LukasHechenberger** [comment]
Found a solution myself, the automerge config has to be added as a package rule: 

```
"packageRules": [
      {
        "automerge": true,
        "depTypeList": [
          "devDependencies"
        ]
      }
    ]
```

I suppose the documentation at [https://renovatebot.com/docs/configuration-options/](https://renovatebot.com/docs/configuration-options/) should be updated...

**Comment by rarkins** [comment]
@LukasHechenberger thanks for following up with your own answer, and you are exactly right. Originally `devDependencies` was a top level config object because Renovate was npm-only and it made a lot of sense. Now we've grown, we couldn't possibly include every possible dependency type for each language so we moved it to packageRules. However there still remains a config migration logic within Renovate that detects and migrates such a config to a valid packageRule, which is done before validation. The validator on its own is a little more strict.

I will rewrite the doc example so that nobody else hopefully falls for it.

**Comment by LukasHechenberger** [comment]
Thanks!
