### ISSUE TITLE
[feature request]Auto merge after ? days’ no-version bumping.

### ISSUE THREAD

**Issue by HaveF** [renovatebot/renovate#3564]
Thanks for your tools! Love it!

**What would you like Renovate to be able to do?**
Here is my workflow:

2019/4/10:
Lib author bump version from 1.29.8–1.30.0

Auto merge daily happens.
But I find sth wrong about this(not catch by CI) , go to issues to find the answer, find others are also suffered this. Author find a solution to fix.

4/11: 
Bump version to 1.30.1

Auto merged. Problem is solved.

**Describe the solution you'd like**
Could it possible to set a hook before auto merge? Like, auto merge only happens when the PR did not update(no lib version bump) in some days.

Then I can escape from the problem I said before!

Auto merge after ? days’ no PR update.

**Describe alternatives you've considered**
NO

**Additional context**

**Comment by rarkins** [comment]
I propose to implement this using a similar approach to the existing "unpublishSafe" feature (which applies to npm only). It uses a status check to help hold back PR creation or automerge, depending on your preference. I'm thinking this could be called something like "stabilizationTime" e.g. to allow you to set it to 3 days and it would only turn green once 3 days have elapsed since publish.

**Comment by HaveF** [comment]
oh, nice!
I didn't notice `unpublishSafe` before. I can use this first :-)

**Comment by rarkins** [comment]
Plan: 
- define a new config option named something like “stabilityThreshold” which is default disables/inactive
- it will apply to any updates where the datasource includes a publish date/time
- if the upgraded-to version is younger than the threshold then the update is considered unstable, which should translate to a “pending” status check
- if any updates within a PR are unstable then the whole PR is considered unstable 
- is there any standard for duration strings we can use? Eg “48 hours” or “5 days”?

Related:
- set prCreation to “not-pending” will mean PRs aren’t created until they are stable 
- PR not pending hours defaults to 24 now, most people will probably want a stability threshold higher than that so need to configure it higher 
- check which datasources provide publish dates and if there’s any we should add publish dates for

**Comment by psyb0t** [comment]
https://github.com/renovatebot/renovate/blob/master/lib/workers/pr/index.js#L14

I'd loop through all of the upgrades after that line checking if any `Date.parse(upgrade.releaseTimestamp) - Date.now()` is lower than `parseToMilliseconds(config.stabilityThreshold)`. If any of the upgrades have a lower release timestamp than the stability threshold allows, then the pr is not pushed.

To parse user friendly time intervals, simple regex can be used: `^(\d+)\s*(hour|day|month)(?:|s)$` where `$1` is is the interval and `$2` is the interval type. would support smth like `20 hours`/`1day`/`2months`

**Comment by rarkins** [comment]
First of all, let's formalize that a null/undefined date means that we don't have one, and that this type of logic won't apply.

I would add logic instead here: https://github.com/renovatebot/renovate/blob/3f4e464e2ba92f444b540015a0026bbcc1a91e66/lib/workers/repository/updates/generate.js#L257-L265

This logic should check if any of the upgrades contain a release timestamp, and if so then we find the most recent timestamp and store it as `config.latestTimeStamp`.

After that, I would look for where we include "canBeUnpublished" and see if this new logic can fit in there. Examples include:
- https://github.com/renovatebot/renovate/blob/b4cc7f4d0be30ccf3d59631ace6201422ea8a5ab/lib/workers/branch/status-checks.js
- https://github.com/renovatebot/renovate/blob/dab7b1c314a2249d3fe7420f5c15e5c50ddb14c4/lib/workers/branch/index.js#L181

Ideally I'd prefer to find a "duration" library that's already written and use that instead of our own, but I'm open to writing our own if no other good ones exist.

**Comment by psyb0t** [comment]
@rarkins 
in the comment before you said 

> if the upgraded-to version is younger than the threshold then the update is considered unstable,

so that would mean that it should not find the most recent timstamp of an upgrade release time but the oldest one which could cancel the creation of a branch, right?

**Comment by rarkins** [comment]
I think it's most recent timestamp that's important? e.g. if there's one upgrade that's 2 months old and another that's 3 days old, then it's the 3 days old one that's important and not the 2 months one. I believe users want to be able to say "Do not unless all are over X duration" instead of "Wait until at least one is over Y duration"

**Comment by psyb0t** [comment]
Oh yeah, I was thinking backwards for some reason haha.
Also as a library `moment.js` looks promising for durations too: https://momentjs.com/docs/#/durations/

**Comment by rarkins** [comment]
I think Luxon is kind of the newer/better library to use if it suits our purpose: https://moment.github.io/luxon/docs/class/src/duration.js~Duration.html

I don't see them supporting "human readable" durations but maybe ISO 8601 is at least clearly specified.

**Comment by rarkins** [comment]
I can't find any good "human readable duration parsing" libraries so let's start with ISO8601 support only.

**Comment by rarkins** [comment]
- [x] New option `stabilityThreshold` (ISO 8601 Duration)
- [ ] Applies only to datasources that include a publish date, otherwise it's essentially ignored for that update
- [ ] If any update in a branch includes a `stabilityThreshold` then a status check will be added - either pending (at least one release date does not meet its threshold) or passed (all other cases)

**Comment by rarkins** [comment]
https://renovatebot.com/docs/configuration-options/#stabilitydays
