### ISSUE TITLE
Go modules: renovate does not remove old versions of an updated package from go.sum

### ISSUE THREAD

**Issue by moorara** [renovatebot/renovate#3607]
**What Renovate type are you using?**
Renovate GitHub App (paid plan)

**Describe the bug**
When using **go modules** and `go.mod` and `go.sum` files,
renovate does not remove entries for old versions of a package from `go.sum`

Example:

<img width="892" alt="Screen Shot 2019-04-26 at 4 36 38 PM" src="https://user-images.githubusercontent.com/6438729/56835168-7f55c080-6841-11e9-89b6-a0467baa1b13.png">

New entries for `groc v1.20.1` are added, but entries for old versions (`grpc v1.19.0`, `grpc v1.20.0`) are not removed!

**Did you see anything helpful in debug logs?**

**To Reproduce**
Any update PR for a project with **go modules**.

**Expected behavior**
I expect to see the entries for old versions of an updated package are removed and entries for the new/updated version are added.

**Screenshots**
Posted above.

**Additional context**

**Comment by rarkins** [comment]
You can add `"postUpdateOptions": ["gomodTidy"]` to your config to achieve this. It's not enabled by default because it has the potential to make changes to your modules files that are completely unrelated to the PR that Renovate raises, e.g. if your master branch contains out of date values.

Be aware though that there's actually nothing wrong with the `go.sum` having "old" entries in it. `go.sum` is not a lock file, and those older versions won't be installed. The creator of Go Modules even mentioned it can be a good thing to keep old versions, for example if you upgrade a module and then need to roll back, you are guaranteed of getting the same "old" version you were previously running if your `go.sum` still contains it.

**Comment by moorara** [comment]
@rarkins Thanks for clarification.
