### ISSUE TITLE
Bundler: how to resolve incompatibilities

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#3697]
Example `bundle lock` failure when updating `rails`:

```
Fetching https://github.com/codahale/bcrypt-ruby.git
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem \"actionpack\":
  In snapshot (Gemfile.lock):
    actionpack (= 6.0.0.beta3)

  In Gemfile:
    rails (= 6.0.0.rc1) was resolved to 6.0.0.rc1, which depends on
      actionpack (= 6.0.0.rc1)

    dotenv-rails (= 2.7.1) was resolved to 2.7.1, which depends on
      railties (>= 3.2, < 6.1) was resolved to 6.0.0.beta3, which depends on
        actionpack (= 6.0.0.beta3)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Questions:
- Should `rails`, `railties`, and `actionpack` all be grouped together by Renovate, solving this issue? Or do we need to massage the lockfile somehow before running `bundle lock`?
- Should we raise PRs like this, or suppress them? If we suppress, then the user may never become aware

Cc @bjeanes

**Comment by bjeanes** [comment]
These kinds of conflicts happen a lot in Ruby land because, unlike in Node, there can only be one version of any library used by any dependency or sub-dependency.

There isn't a clear one-shot solution that I see without trying different combinations of upgrades.

Yes, the `rails` gems generally should be grouped (they are all released from the same monorepo, with a few exceptions) but it's atypical that they would ever be directly required if all of `rails` is in use (instead just Rails would be required and the rest would be brought in as sub-dependencies, as `rails` is just a meta-package).

`6.0.0.rc1` should satisfy `dotenv-rails`'s dependency of `railties (>= 3.2, < 6.1)` but Bundler is very conservative about update changes unless you explicitly tell it you're OK with it updating other dependencies (e.g. with `bundle update [<gem1> [<gem2>]]`).

Is the above message the result of essentially an edit of a `Gemfile` (via regex or whatever) followed by a `bundle lock`? I don't think there's a way passed that error that just modifies the `Gemfile`. Instead, you'd probably need to try—at minimum—`gem update the-gem-being-updated` (i.e. `gem update rails` in this case) but I'm not even sure that would be wholly reliable.

**Comment by rarkins** [comment]
Thanks for the info. I found that `gem update x` did tend to resolve the majority of cases *but* it did a full install which could cause other failures (e.g. platform-specific building). It seems `bundle lock --update x` is what we're after.

**Comment by bjeanes** [comment]
> It seems `bundle lock --update x` is what we're after.

TIL!

**Comment by rarkins** [comment]
This did not solve all the incompatibility problems! :o)

**Comment by bjeanes** [comment]
Have you got an example of an outstanding one? It is possible if not likely that during new releases (esp Rails) there are actually cases that don't yet have an upgrade path.

But yeah, this is what I feared and alluded to above. Every time I've upgraded Rails I usually have to cycle through combos of gems and grant Bundler permission to bump their version (e.g. `bundle update rails discard rack paperclip`). It's not as it bad as it used to be in the Rails 3->4 days, where there were many gems without a bridging version.

**Comment by joho** [comment]
Yeah, I've also had some nasty bundle updates in my time that involves jiggering half my dependencies just to get things going again.

Have sent you my Gemfile on that separate email thread.

Also :wave: bo.

**Comment by bjeanes** [comment]
> Also 👋 bo.

😄 👋

**Comment by rarkins** [comment]
It turns out that the next problem I found wasn't Bundler's fault at all, and is now resolved. I think I'll close this now. It sounds like there may be times when we still get failures, but it could be the right time to start exposing those in Renovate PRs (like we do with npm) instead of suppressing them (like we do now for Bundler only). Thanks for everyone's help!
