### ISSUE TITLE
Renovate throws ERRORs on Gitlab projects with merge request feature disabled

### ISSUE THREAD

**Issue by chgarling** [renovatebot/renovate#3891]
**What Renovate type are you using?**
Renovate CLI

**Describe the bug**
Renovate reports ERRORs if it runs over a Gitlab project without merge requests enabled and returns with an exit code unlike 0. This results in a crash of the docker container Renovate runs in,when its called with sh -e in a while loop.

**Did you see anything helpful in debug logs?**
ERROR: Repository has unknown error (repository=project/subproject)

**To Reproduce**

1.  Create Gitlab project with merge requests feature disabled
2.  Run Renovate over this project / repository

**Expected behavior**
It should WARN about this and otherwise ignore such repositories. Maybe it would also be a good idea to make its behavior configurable how to handle this case.

**Screenshots**
None

**Additional context**
None

**Comment by rarkins** [comment]
Renovate exits with a non-zero code whenever it has encountered something worthy of a `log.error()` in any repo. I think this behaviour should remain.

The question is whether a repo without merge requests should justify a warn or an error? Although we haven't deliberately coded for this scenario (the error "just happens"), I kind of think it's serious enough to be an error. We can do without issues (they are "nice to have") but Renovate simply can't operate without Merge Requests so error seems appropriate (ideally we'd error out as early as possible though).

Given that you run it on a while loop, I'm guessing you'd *never* want Renovate to exit on a non-zero code unless it's truly fatal? Because that sounds like something more reasonable to me - i.e. still consider it an error and log as such, but still exit with code 0.

**Comment by rarkins** [comment]
I guess we can try to actively catch this and log it as a warn before exiting

**Comment by ViceIce** [comment]
I think this is fixed by #4913
