### ISSUE TITLE
documentation: Commit message variables

### ISSUE THREAD

**Issue by matoous** [renovatebot/renovate#3971]
**What would you like Renovate to be able to do?**
I couldn't find anywhere which variables are available in the commit message template.

**Describe the solution you'd like**
I think it would be nice to have them all mentioned somewhere in README/Configuration guide.

**Describe alternatives you've considered**
I don't really see any alternative. Maybe add all the variables to the description of the configuration of the commit message body.

**Comment by rarkins** [comment]
This is a good idea. Perhaps we can even explicitly define the list in code and then sync that list to documentation.

**Comment by matoous** [comment]
I am not sure I can help with that but if you decide to just add it to the documentation just point me to where can I find the variables and I can submit PR.

**Comment by rarkins** [comment]
Part of the problem is that there's no simple list of the variables so it would be asking too much for you to work it out on your own!

For now the simplest thing you can do to learn some of them is to look for examples of `{{` variables in https://github.com/renovatebot/renovate/blob/master/lib/config/definitions.js

**Comment by rarkins** [comment]
Now available in https://docs.renovatebot.com/templates/
