### ISSUE TITLE
Allow multiple automerge comments per run

### ISSUE THREAD

**Issue by aaronjensen** [renovatebot/renovate#4052]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
We're using Renovate with the `pr-comment` `automergeType` and bors. I'd ideally like for renovate to leave its comment on all of the pending PRs, but for some reason it's only leaving the comment on one at a time. Furthermore, it doesn't leave the comment immediately upon opening the PR, it waits for some time afterwards, it seems.

**Did you see anything helpful in debug logs?**
No

**To Reproduce**
Trigger multiple updates using:

```
  "automergeType": "pr-comment",
  "automergeComment": "bors r+",
```

**Expected behavior**
Automerge doesn't happen right away and then only happens one at a time

**Screenshots**
n/a

**Additional context**
n/a

**Comment by aaronjensen** [comment]
This appears to affect repos with regular automerge behavior as well. I'm getting like 1 merge an hour or so, is this to be expected?

**Comment by rarkins** [comment]
To avoid state inconsistency Renovate exits its run immediately after a successful automerge, and this behaviour hasn't been adjusted for PR commenting. In theory there's no reason we need to abort if we're just leaving a comment. A code change to Renovate would be required to change this behaviour though.

Renovate also waits for tests passing before automerging (i.e. leaving a comment) but you may be able to get it to comment earlier if you set `"requiredStatusChecks": null` in config.

**Comment by aaronjensen** [comment]
How often does renovate run? Is it only running once per hour? Is that why repos without the `pr-comment` feature automerge so slowly? Ideally it'd detect the first merged then merge the second immediately--not sure if that's possible. I think that's how dependabot worked (what I'm coming from)

**Comment by rarkins** [comment]
Renovate runs hourly plus then on-demand based on webhooks received. An *actual* automerge commit/webhook triggers a new job for the repo to be put as high priority in the queue and run pretty soon after the first one finishes. But a PR comment does not (something I hadn't thought about until this issue).

> Ideally it'd detect the first merged then merge the second immediately--not sure if that's possible.

GitHub can take a while to determine the mergeability status of all other branches once you make a commit to master, so it's not easily possible to keep merging PRs one after another unless you add some arbitrary sleep commands and hope for the best. Also, we prefer to have branches up-to-date before automerging (you never know when a merge from PR 1 to master would actually break PR 2 even though on its own it's passing).

In the case of automerge commenting (bors), it should be possible to automerge every qualifying PR within the same run, because we're not doing any commits. But as I mentioned, it requires a logic change.

**Comment by aaronjensen** [comment]
> An _actual_ automerge commit/webhook triggers a new job for the repo to be put as high priority in the queue and run pretty soon after the first one finishes

I still only see 1 merge/hour or thereabouts in this case.

> GitHub can take a while to determine the mergeability status of all other branches once you make a commit to master, so it's not easily possible to keep merging PRs one after another unless you add some arbitrary sleep commands and hope for the best.

The build on this particular repo takes a bit over 1 minute. Do you not get webhooks when commit status change happen?




> Also, we prefer to have branches up-to-date before automerging (you never know when a merge from PR 1 to master would actually break PR 2 even though on its own it's passing).

This makes sense, does renovate automatically rebase after a successful merge? This is exactly why I use bors, but I'm not using it on some of my repos, so for those it'd be great if renovate automatically rebased the "next" PR, then after its status checks pass, merged. 



> In the case of automerge commenting (bors), it should be possible to automerge every qualifying PR within the same run, because we're not doing any commits. But as I mentioned, it requires a logic change.

That'd be great. Maybe I'll take a crack at this--mind pointing me in the right direction?

**Comment by rarkins** [comment]
> Do you not get webhooks when commit status change happen?

We do, but GitHub's webhook metadata for commit statuses have a limitation. Essentially, each webhook just says "a test passed" and does not include aggregate data about whether the entire branch is green or not. There may be 10+ separate status checks passing per-PR and we don't want to run each time any of them passes, as we'd probably use up the repo's hourly API allowance. It's possible to code around this, but we haven't yet.

> This makes sense, does renovate automatically rebase after a successful merge?

It depends on configuration. For PR automerging we rebase if `rebaseStalePrs` is set to `true` in config or if the GitHub repo is configured such that all PRs are required to be up to date with the base branch.

> That'd be great. Maybe I'll take a crack at this--mind pointing me in the right direction?

Here's where we abort a run due to automerging: https://github.com/renovatebot/renovate/blob/c48129abfbbf24d52845e546ede685ba417d8945/lib/workers/repository/process/write.js#L33-L36

It might be possible to simply add an extra qualifier there that `automergeType !== 'pr-comment'` and not abort if so. BTW it sounds like you wish to have `requiredStatusChecks` set to `null` in config too, i.e. don't wait for tests to pass before automerging.

**Comment by aaronjensen** [comment]
> BTW it sounds like you wish to have `requiredStatusChecks` set to `null` in config too, i.e. don't wait for tests to pass before automerging.

Right, on my bors repo I do have this, but I have it set to `[]` on the others. I wonder if it would be easier for you to track the statuses if I had to set them explicitly (I only have one): `['build']`. Then, when you got the 1 passing status that matched you'd know you could kick off a merge.

**Comment by aaronjensen** [comment]
One other question, why is it that it won't trigger an automerge when it first opens the PR but instead waits for the next run? I see this: `INFO: PR is ready for automerge but has been modified`

**Comment by aaronjensen** [comment]
This is great, thank you @rarkins. Should I open a separate issue for the time between when a PR is opened and when the automerge happens? I see this in the log: `INFO: PR is ready for automerge but has been modified` but it waits for the next run to actually merge.

**Comment by rarkins** [comment]
Yes, let's treat that as a separate issue

**Comment by aaronjensen** [comment]
Sounds good: https://github.com/renovatebot/renovate/issues/4113
