### ISSUE TITLE
renovate is not updating nodejs dependency correctly in .travis.yml

### ISSUE THREAD

**Issue by nihalwasheretoo** [renovatebot/renovate#4194]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
1) If there's just one nodejs version specified then renovate fails to update the dependency. 
2) If there were more nodejs versions specified, for example : 
```
language: node_js
node_js:
  - '8'
  - '6'
  - '4'
``` 

then renovate updates the .travis.yml to 

```
language: node_js
node_js:
  - '10'
  - '4'
``` 

**Did you see anything helpful in debug logs?**

**To Reproduce**
For 1) Try against this repo : https://github.com/nihal9ns/travis-ci-test 
For 2) Try running renovate with the above mentioned example

**Expected behavior**
For 1) Renovate should update the nodejs version in .travis.yml even if there was just a single nodejs version specified in .travis.yml.

**Screenshots**

**Additional context**

**Comment by rarkins** [comment]
Travis is a special case and we may need to reconsider how we handle it. 

The complexity is:
- because users often want a matrix of releases, because an existing one is out of date (major) does not mean we want to upgrade it!
- as part of support policy, not only might we completely change the major versions in the list but we might even change the number of items in the list

Decisions:
- treat the list as one dep and “current value”, or multiple  deps/values (and make sure we group them into same PR)?
- where to perform support policy logic - extract, update, or datasource? We can do it in datasource only if we treat the list as one value. If we split them into multiple values then we’d need to implement support logic in extract

**Comment by rarkins** [comment]
Idea: extract current values as a comma-separated list. Then create a new custom datasource just for this purpose. The datasource will use supportPolicy to decide if the list needs changing, and then defer to the existing datasource for updating them. Flag as “major” update of any majors changed. Customise commit message to make sure it makes sense.
