### ISSUE TITLE
Support bower 

### ISSUE THREAD

**Issue by maxcbc** [renovatebot/renovate#4225]
**What would you like Renovate to be able to do?**
Some users are stuck using bower, which although deprecated is still present in some projects for organisational reasons.

**Describe the solution you'd like**
Renovate to update outdated bower dependencies.

**Describe alternatives you've considered**
Writing a thing called bowenovate to use alongside renovate for this purpose.

**Comment by HonkingGoose** [comment]
I'm not sure if it is worth our time/effort to create a `bower` package manager for use with Renovate when the creators of Bower say this on their [homepage](https://bower.io/):

> ...psst! While Bower is maintained, we recommend using Yarn and Webpack or Parcel for front-end projects read how to migrate!

The Bower team also made a short guide on [how to migrate away from bower](https://bower.io/blog/2017/how-to-migrate-away-from-bower/).

Also it's been a long time since this issue was opened and nobody else chimed in: "Hey this is great, can you please build this?", I'm also not seeing any 👍 for the top post. Maybe the demand just isn't there?

I'll let @rarkins and co decide what they want to do here. 😉

**Comment by rarkins** [comment]
My general principal of whether to keep feature requests open is "would I accept a well written PR to implement this?". And that would still be true. 

Let's do this: we'll close this issue due to lack of demand, but anyone welcome to submit a PR if they really need it.

**Comment by viceice** [comment]
I think we can close this. Bower isn't widely used anymore
