### ISSUE TITLE
Allow user-defined version schemes

### ISSUE THREAD

**Issue by TheKevJames** [renovatebot/renovate#4264]
Note: I am already working on a solution to this feature request. ~Will convert this to a PR Soon™ after getting some comments and cleaning up my branch~ PR is available at #4273. I would mostly hope to use this issue as a place to RFC my proposed solution, in case the maintainers would be interested in an alternate approach or there's anything I'm unaware of.

**What would you like Renovate to be able to do?**
I've been recently working through [this issue](https://github.com/renovatebot/config-help/issues/319), which amounts to "the [Python docker image tags versions somewhat uniquely](https://hub.docker.com/_/python?tab=tags), and Renovate can't quite support that". [Other similar issues](https://github.com/renovatebot/renovate/issues/2438) have been raised before. Support for these slightly weird/unique version schemes would be fantastic.

**Describe the solution you'd like**
I propose the addition of a configurable `versionScheme`, which allows users to specify the format of any given dependency in order to plug these gaps, perhaps with an optional `versionConfig`

**Describe alternatives you've considered**
There aren't many other options here; most of these repos have some sort of almost-right fallback, for example:
- the python docker images can use the `docker` versioner, but then `ignoreUnstable` will break
- the python docker images can use the `pep440` versioner, but then versioning will break entirely if you use the various `-alpine` / `-slim` flags

**Additional context**
- [WIP branch](https://github.com/renovatebot/renovate/compare/master...TheKevJames:add-regex-versioner) (still has a few TODOs that I need to finish up or ask some questions about)
- [successfully works for the docker:python test case](https://github.com/TheKevJames/renovate-test/pull/34)

**Comment by rarkins** [comment]
@TheKevJames this is an exciting idea and seems like a great fit for Renovate. As a first step, can you describe how you think this could be *configured*?

e.g. would it be like `"versionScheme": "regex:aaaaaaaaaaaaaaaaaaaaaaaa"`? Or would there be more than one field required?

**Comment by rarkins** [comment]
Is this a use case that currently *fails* with existing docker versioning: `FROM python:3.6.2-alpine`? e.g. Does it update to a beta version?

**Comment by TheKevJames** [comment]
### Configuration
My plan was to add a new possible value for `versionScheme`. I've listed it as "regex" for now, but naming can be changed. Anywhere `versionSchema` can be set, there would be a new optional field named `versionConfig` -- we can come up with a default for the regex versioner when this is unset, or we could make `versionConfig` required when `versionScheme=regex`. `versionConfig` would be a noop for any versioners which do not make use of it -- perhaps we should raise an error if it is set in that case?

The expected value of the `versionConfig` value would be, for the regex versioner, the regex to apply. I've been leaning towards using named capture groups as being the most reasonable and flexible option -- the regex versioner would support some set of potential fields (eg. {major, minor, patch, architecture, prerelease, ...}. Users can make use of any of those fields.

For example, to emulate the current docker versioner, you could do:
```
{
  "versionScheme": "regex",
  "versionConfig": "^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)(-(?<architecture>.*))?$"
}
```

I've been able to describe most version schemes with some subset of `major, minor, patch, architecture, prerelease`, but we could always include support for more control groups. Copying from my WIP branch:
```
interface Version {
  // major, minor, and patch act in the standard semver fashion, but without
  // correctness requirements: if any one or two is omitted, they are treated
  // as zero. At least one must be present
  major: number;
  minor: number;
  patch: number;
  // prereleases are treated in the standard semver manner, if present
  prerelease: string[];
  // architectures, if present, are treated as a compatibility layer: we will
  // never try to update to a version with a different architecture. Other than
  // for juding compatibility (exact string match), the architecture is ignored
  architecture: string[];
}
```

I'd be happy to give some sample config values which could follow sample version schemes.

**Comment by TheKevJames** [comment]
### Existing docker versioning
`FROM python:3.6.2-alpine` is currently being parsed by the `docker` versioner as needing to be updated to `FROM python:3.8.0b1-alpine` _regardless of ignoreUnstable setting_.

Using the `docker` versioner (which has no concept of unstable):
* `python:3.6.6` -> `python:3.8.0b1`
* `python:3.6.6-alpine` -> `python:3.8.0b1-alpine`

Using the `pep440` versioner (which has no concept of constant suffixes [which I've marked as "architecture" in my proposed config]):
* `python:3.6.6` -> `python:3.7.4` (or `python:3.8.0b1`, if `ignoreUnstable=false`)
* `python:3.6.6-alpine` -> unsupported-version

The above versioning scheme can be solved with the following `versionConfig`:
```
^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)(?<prerelease>[^.-]+)?(-(?<architecture>.*))?$
```
Which results in:
* `python:3.6.6` -> `python:3.7.4` (or `python:3.8.0b1`, if `ignoreUnstable=false`)
* `python:3.6.6-alpine` -> `python:3.7.4-alpine` (or `python:3.8.0b1-alpine`, if `ignoreUnstable=false`)

**Comment by TheKevJames** [comment]
PR (WIP): #4273

**Comment by rarkins** [comment]
Hi @TheKevJames,

I love this feature the more I think about it. Congratulations and thanks for such a great idea. This will fit in nicely with our (future) functionality of making an entire *manager* based on named capture groups.

Some thoughts/ideas:

As this will be "exact" versions only and not ranges, we already have a thankfully simpler functionality set to implement.

We may want to borrow a lot from our existing "loose" ver implementation. It does a great job of sorting "anything" while maintaining backwards compatibility with semver. What do you think about loosening the requirements of major/minor/patch to being a number? That may cause problems for versions like `18.04.01` while also excluding someone who decides to name releases like `20190610.A` where A is part of the version and not meaning prerelease or architecture.

Let's make it so that only major is mandatory.

Let's extend this to support at least a fourth precision group, e.g. to enable versions like `v3.2.0.0`. If we were to support unlimited precision we probably would want abandon major/minor/patch terminology and instead just use something like section0/section1/section2/section3, but then that's also unintuitive for the 99% of uses which would need at most 3. For a compromise, perhaps we support up to 4 sections and call the fourth one "extra"?

Supporting a pre-release section right away is essential to your own use case, so I support that. I think initially though we just need to have a "dumb" sorting of pre-releases based on alphabetical order. i.e. like semver does it and not like how maven or python do it with meaningful names of pre-releases. Fortunately alpha/beta/pre/rc all sort in the intended order, which is why semver has got away with it until now.

I'm unsure whether to use "architecture" or call it a more generic "compatibility".

Thumbs-up also for `versionConfig`. I had been leaning towards embedding it inside the `versionScheme` but now I'm thinking it's instead preferable to keep a 1:1 mapping between values in `versionScheme` and `lib/versioning/*` subfolders.

Also thumbs up for name `regex` and using named capture groups.

Now, a question or two: can you explain the reasoning behind having prerelease and architecture both as *arrays* of strings, instead of just a string?

**Comment by TheKevJames** [comment]
> As this will be "exact" versions only and not ranges, we already have a thankfully simpler functionality set to implement.

:+1:

> We may want to borrow a lot from our existing "loose" ver implementation. It does a great job of sorting "anything" while maintaining backwards compatibility with semver. What do you think about loosening the requirements of major/minor/patch to being a number? That may cause problems for versions like 18.04.01 while also excluding someone who decides to name releases like 20190610.A where A is part of the version and not meaning prerelease or architecture.

I think capturing `18.04.01` as `major.minor.patch` should work out of the box (so long as we use the right regex: in this case, we'd want to strip leading zeros `/0*(?<major>\d+)\.0*(?<minor>\d+)\.0*(?<patch>\d+)/`). There are a couple ways users could capture `20190610.A` depending on the behavior folks want: `/(?<major>\d+)\.\w+/` would do the trick since ISO dates are strictly incrementing, but you could get more fancy and do something like `/(?<major>\d{4})(?<minor>\d{2})(?<patch>\d{2})\.\w+/`.

> Let's make it so that only major is mandatory.

I've currently made it so _at least one_ of major, minor, and patch is necessary. Do we want to require `major` in particular?

> Let's extend this to support at least a fourth precision group, e.g. to enable versions like v3.2.0.0. If we were to support unlimited precision we probably would want abandon major/minor/patch terminology and instead just use something like section0/section1/section2/section3, but then that's also unintuitive for the 99% of uses which would need at most 3. For a compromise, perhaps we support up to 4 sections and call the fourth one "extra"?

I'm currently using the `semver` js package to offload a lot of the comparison work, which would unfortunately not support >3 precision groups (as far as I know!). Moving to four groups is probably about the same amount of work as moving to >4 -- perhaps we want to start talking about drafting this as an enhancement protocol for how we want users to make use of "infinitely many capture groups"?

> Supporting a pre-release section right away is essential to your own use case, so I support that. I think initially though we just need to have a "dumb" sorting of pre-releases based on alphabetical order. i.e. like semver does it and not like how maven or python do it with meaningful names of pre-releases. Fortunately alpha/beta/pre/rc all sort in the intended order, which is why semver has got away with it until now.

Currently, I've configured the repo to use `semver`-js for sorting versions, so it should be correctly applying that alphabetical sorting order already!

> I'm unsure whether to use "architecture" or call it a more generic "compatibility".

I'm content on either of these. If you'd prefer `compatibility` (or any other description), let me know and I can update the PR.

> Now, a question or two: can you explain the reasoning behind having prerelease and architecture both as arrays of strings, instead of just a string?

Completely my bad -- those should have been `strings` in the first place (and see the attached PR, where that type hint has been fixed), but this was the first TypeScript I've written so I didn't realize my error at first; thought it might have been C-like where strings are `char[]`s and didn't think too much of where I'd copied it from.

**Comment by rarkins** [comment]
I think it makes sense to leverage semver as much as possible to get this released. For now we can also skip support for >3 precision groups or alphanumeric versions because both of these could be added at a future date in a backwards-compatible way.

I think it makes sense to make major mandatory rather than allowing any of major/minor/patch, unless you have a use case in mind that I haven't thought of. I was thinking then it makes it a lot easier to then use `semver.coerce` on the result to get a comparable sort.
