### ISSUE TITLE
skip-reason: "unsupported-value" with Rust (cargo)

### ISSUE THREAD

**Issue by leo-lb** [renovatebot/renovate#4276]
**What Renovate type are you using?**
Renovate Gitlab App

**Describe the bug**
Renovate Gitlab App does not create merge requests

**Did you see anything helpful in debug logs?**
https://renovatebot.com/dashboard#gitlab/schmilblick/violetear/web-client/86538280

**Expected behavior**
Merge requests created with dependency updates

**Comment by rarkins** [comment]
Please provide details of the dependency/value that is being skipped. It’s common for this to happen and usually not a big.

**Comment by leo-lb** [comment]
@rarkins Please see the debug logs.

**Comment by rarkins** [comment]
Please delete that comment and replace it with one that includes just the line or lines relevant to this issue.

**Comment by leo-lb** [comment]
@rarkins The whole log is relevant to the issue because it happens everywhere.

**Comment by rarkins** [comment]
I’ll leave this open in case anyone has the time to look into it and triage if it’s a fault, find something applicable in the cargo specs, etc.

**Comment by ikesyo** [comment]
https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field

> Use version numbers with three numeric parts such as 1.0.0 rather than 1.0.

This should be the point.

**Comment by leo-lb** [comment]
@ikesyo Cargo.lock file is in charge of freezing versions until I run `cargo update`, but the Cargo.lock file does not update unless you run that, and that file is committed on the repo as well. So what I expected renovate to do is to run `cargo update` automatically and then offer updates for that file with merge requests.

**Comment by ikesyo** [comment]
`unsupported-value` skip reason comes from https://github.com/renovatebot/renovate/blob/d97737914ee5c05c533f7f40619e2346d7d08c3d/lib/workers/repository/process/lookup/index.js#L228-L235.

**Comment by ikesyo** [comment]
Maybe we should call `semver`s `coerce` function here before passing to `npm.isValid`: https://github.com/renovatebot/renovate/blob/4a81c20c9a65acda68ce8335e5b354747fc7b5ec/lib/versioning/cargo/index.ts#L44

**Comment by rarkins** [comment]
If you use traditional semver syntax (e.g ^1.0.0 instead of 1) then you’ll be half way to a solution. I’m wondering though if there’s a definitive reference for cargo range syntax so we can add the missing ones (as a feature request).

Also all Rust *applications* should use exact versions and avoid this problem (only *libraries* need use ranges).

Additionally, rangeStrategy=update-lockfile support for Cargo will be required (another feature request) to support use cases of updating lockfiles only (ie for libraries).

FYI we do not run “cargo update” to *determine* available updates, but we may run it or other cargo commands after patching the Cargo.toml directly.

**Comment by djcsdy** [comment]
The [Cargo book](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html) states that a version requirement without any operator is treated as if the version requirement were preceded by `^`. So, `1`, `1.0`, `1.0.0` and `^1.0.0` are all equivalent. This has the same meaning as `^1.0.0` in npm.

The exact algorithm is implemented in the [semver](https://github.com/steveklabnik/semver/blob/master/src/version_req.rs) crate. It is mostly the same but unfortunately not exactly the same as the npm algorithm.

It’s quite common to specify versions in this way in Rust projects. The Cargo book uses `uuid = "1.0"` as an example dependency. So I think almost everyone using Renovate with Rust will experience this problem and get no updates for their dependencies.

See https://app.renovatebot.com/dashboard#github/djcsdy/wildflower-codec/101479940 for another example of this problem in practice.

**Comment by djcsdy** [comment]
Correction to the above: in Cargo, `1.0` is equivalent to `1.0.*`, which is *not* the same as `^1.0.0`.

Anyway, I took a quick look at `versioning/cargo` and it looks like Cargo version ranges are handled correctly. It works by converting Cargo version ranges into the equivalent npm version range, and then comparing using npm.

This suggests that Renovate can’t handle version ranges like `1.0.x` or `1.0` in npm either. Is that correct @rarkins?

Cargo seems to actively encourage use of version ranges like `1.0` in the same way that npm encourages `^1.0.0`. This is perhaps due to a tendency towards conservatism in systems programming languages.

So, I think Renovate probably ought to handle version ranges of this sort if it is to be useful to Rust developers.

**Comment by djcsdy** [comment]
I wrote some tests to try to narrow down the problem and discovered that this problem only occurs when the range strategy is `widen`.

Here is a test case that demonstrates the problem if added to `test/versioning/cargo.spec.ts`:

```typescript
  it('widens short version', () => {
    expect(semver.getNewValue('1.0', 'widen', '1.0.0', '1.1.5')).toEqual(
      '1.0, 1.1'
    );
    // Expected: "1.0, 1.1", Received: "1.0, ||, 1.1"
  });
```

The problem is that `versioning/cargo` doesn’t handle disjunctions correctly. In npm the syntax is `1.0 || 1.1`. In Cargo, the equivalent is `1.0, 1.1`.

**Comment by djcsdy** [comment]
There is unfortunately no way to specify a disjunction of version ranges in Cargo. You can write a version range like `1.0, 1.1`, but that means that the version must satisfy *both* `1.0` and `1.1`, which of course is not possible. This is equivalent to `1.0 1.1` in npm, which is similarly useless.

In the above case Renovate could produce `>1.0, <=1.1` instead.

This could lead to the version range being widened more than expected. For example when upgrading from version 1.0.x to 1.2.x, Renovate would have to produce `>1.0, <=1.2`, which includes `1.1.x`, whereas for npm it can produce `1.0 || 1.2`. However I think this would be a reasonable compromise.

**Comment by rarkins** [comment]
@djcsdy thanks very much for documenting your research into this. We definitely want to support the most common ways of specifying dependencies.

`widen` is actually a pretty rare use case. The main use for it was in npm when we tried to work out what to do by default about peer dependencies, and we then expanded it as default behaviour for any complex ranges.

If you have 1.0 and then 1.2 is released, and policy is widen, `>=1.0, <=1.2` sounds correct to me for widening.

Anyway, if there are updates we are not doing correctly, the best way to express that would be for someone to create a Draft/WIP PR editing this test file only: https://github.com/renovatebot/renovate/blob/master/test/versioning/cargo.spec.ts

i.e. create some failing tests, we can debate if we agree on what the expect value should be, and then if agreed then we can work out the best way to implement.

This seems to have diverged from the original content of this issue though, which was about "unsupported value" getting returned.

**Comment by djcsdy** [comment]
@rarkins You are right, the problem with `widen` is unrelated to this issue. Sorry for the noise. I got confused and went down a rabbit hole.

**Comment by rarkins** [comment]
If someone can set up a simple reproduction of the original issue where a library is defined as something like `0.1` or `1.0` and there exists an update e.g. to `0.2` or `1.1` and Renovate fails to do it, that would be a helpful start.

**Comment by djcsdy** [comment]
Here is a minimal test case for this issue: https://github.com/djcsdy/renovate-issue-4276-test-case.

In the test case, bitflags 1.0 should be upgraded to 1.2.
