### ISSUE TITLE
npm audit fix plugin / config option

### ISSUE THREAD

**Issue by wyardley** [renovatebot/renovate#4286]
**What would you like Renovate to be able to do?**
We had a user inquire as to whether Renovate could run `npm audit fix` as a post-step (presumably this would be a configurable option, defaulting to off).
It seems that, as of now, while renovate will update dependencies, it won't (AFAIK) update nested dependencies when the enclosing package itself isn't updated, whereas `npm audit` will.

**Describe the solution you'd like**
A plugin / option (defaulting to `false`) to allow the user to have `npm audit fix` run as a step.

**Describe alternatives you've considered**
We already do check for some types of vulnerabilities as a check in CI.

**Additional context**
Maybe somewhat related to #2951?
Let me know if simply changing lockfile maintenance strategy would accomplish the same thing (currently, we don't have any config around it, so should be taking defaults on `lockFileMaintenance`; we have `"rangeStrategy": "bump"` set).
We have a pro account, if it matters.

**Comment by rarkins** [comment]
Lock file maintenance will update every single dependency to the latest within its range. In many cases this results in "fixing" vulnerable transitive dependencies because they just needed a bump within the existing range.

`npm audit fix` is essentially a form of selective lock file maintenance, where it will bump only those transitive dependencies that resolve a vulnerability. AFAIK it may also bump the version in `package.json` too, although that's something Renovate is doing all the time too, naturally.

I think `npm audit fix` defaults to non-major updates only but you can "force" it to bump majors in `package.json` too.

One more strategy when it comes to resolving a transitive vulnerability is needed when all the above don't work. If you have a path of A->B->C and maybe also D->C, where A and D are direct dependencies in `package.json`, there may be cases where the only way to fix a vulnerable C is actually to update the definitions for both A and D within `package.json`, including to a new major of each. I'm not aware of any tool smart enough to do that yet.

BTW one more relevant point to this discussion is about which vulnerability DB you're relying on. If you're on github/GHE then it's got the feed from GitHub baked in, which includes not only JS but other languages as well. `npm` uses its own DB which doesn't have a publicly documented API, although it's possible to reverse engineer it like Yarn has done.

**Comment by rarkins** [comment]
Back to your original question, it's feasible that we could run `npm audit fix` as one of "postUpdateOptions" - we already have `npm dedupe` as an option there. I don't consider that to be logically sound though, e.g. you'd end up with every PR bundling together vulnerability fixes, where the original PR could be a simple patch while the vulnerability fix is a riskier minor update.

I'll think about if there's a more elegant way to combine it.

**Comment by wyardley** [comment]
@rarkins Thanks for the quick and thoughtful response.

Yeah, I'm not sure why we're seeing some deps that don't seem to get caught up (FWIW, we're on GH now, and will eventually be on GHE).

I agree that it would be better to have it be a separate update rather than bundled with others (and potentially something that could get run on a different schedule.

**Comment by rarkins** [comment]
@wyardley in that case I might close this is in favour of #3080, and combine the ideas there. The aim of that one is to increase the number of vulnerabilities we can remediate within transitive dependencies. `npm audit fix` may be one approach that's included in the toolbelt there
