### ISSUE TITLE
Open up Gitter channel

### ISSUE THREAD

**Issue by deiga** [renovatebot/renovate#4405]
It would be great to have a chat like https://gitter.im to interact with people to get faster help for configuration issues.
Would that be possible? :)

**Comment by rarkins** [comment]
We had a gitter channel in 2018, but it tended to bring out the laziness in many questioners. When it was a "chat" interface, many users tended to ask vague help questions before doing any troubleshooting themselves. Moving help to https://github.com/renovatebot/config-help has worked better because people tend to try a few things first, attach logs, etc.
