### ISSUE TITLE
shouldn't update indirect dependencies

### ISSUE THREAD

**Issue by caarlos0** [renovatebot/renovate#4586]
**What Renovate type are you using?**

github app.

**Describe the bug**
On a `go.mod` file, in my understanding, an indirect dependency is a dependency of a dependency, so, it does not make sense to update an indirect dependency.

On `go.sum` you can even see that the checksum for both the old and new version is there.

**Did you see anything helpful in debug logs?**

**To Reproduce**

**Expected behavior**

I would expect renovate to update only direct dependencies. If those dependencies are using newer indirect dependencies, `go mod` will fix the `go.mod` and `go.sum` file any way.

**Screenshots**

**Additional context**

- https://github.com/goreleaser/goreleaser/pull/1172

**Comment by caarlos0** [comment]
cc/ @rarkins thoughts?

if you folks agree I can try to work on this :)

**Comment by rarkins** [comment]
Hi @caarlos0, I'm not 100% sure if we want to permanently stop updating indirect, but the idea I had was to start by adding depType=indirect during [the extraction phase](https://github.com/renovatebot/renovate/blob/master/lib/manager/gomod/extract.ts), which would then allow users to disable them with a packageRule:

```json
  "packageRules": [{
    "managers": ["gomod"].
    "depTypeList": ["indirect"].
    "enabled": false
  }]
```

And the above could be made into a preset so that it's one line too.

**Comment by caarlos0** [comment]
sounds good to me, but I don't see why anyone would want to update indirect deps as they won't be used anyway 🤔

**Comment by caarlos0** [comment]
@rarkins done: #4615 🚀
