### ISSUE TITLE
Should we not pin nodejs library?

### ISSUE THREAD

**Issue by foray1010** [renovatebot/renovate#4640]
**What would you like Renovate to be able to do?**
I'm always frustrated when my application will be detected as app or library by rule `rangeStrategy: auto`
I digged into the code and see <https://github.com/renovatebot/renovate/blob/master/lib/manager/npm/extract/type.ts>. I wonder why we pin it when it is a nodejs library? I thought it will be better to also pin it to align with the documentation `Pin dependencies if we detect that it's an app and not a library`

**Describe the solution you'd like**
If yes then there may be more optimizations, for example we can identify it is a library by checking if it has `peerDependencies`

I'm willing to open PR if u agree on it

**Comment by rarkins** [comment]
If an npm package is private, we know it's not published, so therefore it cannot be a library. So we pin.

If the package has no `main` then we know it cannot be required/imported so we assume it's not a library and pin.

Otherwise, we cannot be sure so we leave pinning disabled.

For any other rules you have in mind, let's discus here before creating a PR. I think if it has peerDependencies, that's a good sign that it's a library? But have you seen a library that has peerDependencies yet is private or with no `main` ?

**Comment by foray1010** [comment]
I should have clarify my question, the real question is I am not sure why for npm, we check if it is a browser library (the function name is `mightBeABrowserLibrary`, and there is todo comment: `TODO: how can we know if it's a node.js library only, and not browser?`), I think we don't care if it is browser library or a nodejs library, all libraries should not be pinned.

> I think if it has peerDependencies, that's a good sign that it's a library? But have you seen a library that has peerDependencies yet is private or with no main ?

I have never seen any app has `peerDependencies`, it should be exclusively for library

I have seen library without `main`, I think it may be a valid use case for forcing user to minimize bundle size manually (without automatic tree shaking)
example: https://github.com/kelektiv/node-uuid/blob/master/package.json

**Comment by rarkins** [comment]
You're welcome to submit a PR where it checks for existence of `peerDependencies` and uses that as an indication of of it being a library. Do you know of any cases where private=true and main is null and yet there are `peerDependencies`? I'm interested to know if you have some examples I can point at where they are mistakenly pinned instead of maintaining ranges.

The reason for singling out Node.js specifically versus browser is because there are few situations where a duplication of dependencies (e.g. due to incompatible ranges/versions) in a backend application causes a functionality or performance problem. And even if you can name one or two situations (e.g. embedded systems with limited space/performance), we want Renovate's defaults to aim for the most common uses case. Anyone who has an abnormal use case here can override the auto default with one line of config (rangeStrategy=replace or rangeStrategy=bump).

**Comment by foray1010** [comment]
> Do you know of any cases where private=true and main is null and yet there are peerDependencies? 

I didn't see one in real case but I can imagine one use case
1. `private=true` because developer is using monorepo like lerna, and wanna avoiding publishing before the new package is done (lerna will publish all packages in same repo unless you mark it as `private=true` via `lerna publish` command)
2. `main=null` because there is no default export like https://github.com/kelektiv/node-uuid/blob/master/package.json , I personally have a library like this (https://github.com/foray1010/babel-preset-foray1010, I added back `main` field to workaround renovate) because I want user to pick one preset (flow-react or typescript-react)
3. has `peerDependencies` because it is a library with peer dependencies

> there are few situations where a duplication of dependencies (e.g. due to incompatible ranges/versions) in a backend application causes a functionality or performance problem.

I think this point is supporting we should not pin backend libraries? Because pinning backend libraries will lead to incompatible ranges like u said.

by seeing [this lines](https://github.com/renovatebot/renovate/blob/87863f165ecfee691a938bafedc590898c16f279/lib/manager/npm/extract/index.ts#L82-L84), we can see that the original intention is to not pin frontend libraries but pin backend libraries. Which I think we can just rename to `mightBeALibrary`, all libraries should not be pinned.

**Comment by rarkins** [comment]
Backend-only (Node.js) libraries should be pinned by default. Incompatible ranges are not a problem for Node.js - it was designed to support multiple versions of the same library if necessary. 

But right now we done detect Node.js vs browser anyway so it doesn’t matter.
