### ISSUE TITLE
Wait for Docker hub releases being available before opening PRs for Docker images

### ISSUE THREAD

**Issue by armenzg** [renovatebot/renovate#4668]
**What would you like Renovate to be able to do?**
In this [PR](https://github.com/mozilla/treeherder/pull/5519) an update to the MySql Docker version was requested but [Travis failed](https://travis-ci.org/mozilla/treeherder/jobs/598353538) with:
> Pulling mysql (mysql:5.7.28)...
> 5.7.28: Pulling from library/mysql
> ERROR: no matching manifest for unknown in the manifest list entries

This is because the MySql image was not yet available on [Docker Hub](https://hub.docker.com/_/mysql).

Please keep an eye on the Docker tags rather than source code tags. Thanks!

**Comment by rarkins** [comment]
> Please keep an eye on the Docker tags rather than source code tags. Thanks!

The docker datasource in Renovate queries only the Docker Hub tags, so that is not an issue here.

If Renovate proposed a PR with 5.7.28, it's because Docker Hub returned a list of tags for `mysql` that included it. My best guess is that either:
(a) Travis has some cache/proxy somehow involved that didn't return the "very latest" results, or
(b) There was a delay in building the amd64 version of mysql 5.7.28 due to [Docker's invisible multi-platform support](https://www.docker.com/blog/docker-official-images-now-multi-platform/) and Docker Hub was returning 5.7.28 as a valid tag before it was available for amd64

Possible solutions:
- If we can get a releaseDate from Docker's metadata, we could use Renovate's new `stabilityDays` feature so that you don't get Docker PRs immediately, reducing the chance of a race condition, or
- Define your Dockerfile using `amd64/mysql` instead of `mysql` and remove the chance of this type of race condition

**Comment by rarkins** [comment]
So to summarise: Renovate only proposes new Docker tags if Docker Hub says they're available. It's possible that this was caused because a non-amd64 platform was built before amd64, so in this case it's recommended to use the amd64 prefix for all Docker Hub library images, e.g. https://hub.docker.com/r/amd64/mysql
