### ISSUE TITLE
Invalid update suggestion (from  2.0.0-rc.18 to 2.0.0-rc.8-1)

### ISSUE THREAD

**Issue by bartjkdp** [renovatebot/renovate#4808]
**What Renovate type are you using?**
We are using hosted Renovate on Gitlab, see [here](https://gitlab.com/commonground/nlx/nlx/merge_requests/1074).

**Describe the bug**
Renovate suggests an upgrade that is actually a downgrade. It proposes to upgrade from version 2.0.0-rc.18 to 2.0.0-rc.8-1. Probably this has to do with the way Renovate parses version strings.

![afbeelding](https://user-images.githubusercontent.com/5213690/68783315-14cc6c80-063b-11ea-8ce4-ea3f1ab3dc51.png)

**Comment by rarkins** [comment]
This is actually the correct ordering according to Semver. Version suffixes are sorted alphabetically and not by number as you’d expect 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ehotting** [comment]
@rarkins I believe the reason is to be found in [Semver spec item 11](https://semver.org/#spec-item-11):

`(..) Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows: identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order. Numeric identifiers always have lower precedence than non-numeric identifiers. (..)`

The problem seems to be that redoc did not take into account the `Numeric identifiers always have lower precedence than non-numeric identifiers' rule... 

https://github.com/Redocly/redoc/releases?after=v2.0.0-rc.9

The one release with `rc.8-1` takes precedence over every release with just `rc.$number`

Will contact the people of Redoc about it. :)

**Comment by bartjkdp** [comment]
Thanks a lot @rarkins

**Comment by rarkins** [comment]
Thanks for looking that up!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
