### ISSUE TITLE
[Maven] Trouble with obsolete packages

### ISSUE THREAD

**Issue by rassie** [renovatebot/renovate#4869]
**What Renovate type are you using?**

Self-hosted.

**Describe the bug**

Given is the following Maven configuration:

```
    <!-- Keycloak -->
    <dependency>
      <groupId>org.keycloak</groupId>
      <artifactId>keycloak-spring-boot-2-adapter</artifactId>
      <version>${keycloak.version}</version>
    </dependency>
    <dependency>
      <groupId>org.keycloak</groupId>
      <artifactId>keycloak-spring-boot-adapter-core</artifactId>
      <version>${keycloak.version}</version>
    </dependency>
    <dependency>
      <groupId>org.keycloak</groupId>
      <artifactId>keycloak-tomcat8-adapter</artifactId>
      <version>${keycloak.version}</version>
    </dependency>
```

`keycloak.version` is currently set to `4.8.3.Final`. The problem is that while all three packages used to have the same version with `4.8.3.Final`, `keycloak-tomcat8-adapter` has been replaced in 7.0.0 and thus can only be updated to `6.0.1` instead of `8.0.0` for the other two packages. 

![image](https://user-images.githubusercontent.com/23448/69526078-af954700-0f69-11ea-89c0-279bd5a6ad4b.png)

Renovate creates an MR with the lowest common available version, i.e. `6.0.1`. On the next run, it notices that `6.0.1` is outdated (based on two other packages) and rebases the MR, but only includes `6.0.1` again, which leads to a rebase on every Renovate run. So basically, there is a discrepancy between finding a version to upgrade to and the actualy version written to the commit. 

I would expect Renovate to propose an update to `6.0.1` for all components, until a higher version for all components is available.

**Comment by rarkins** [comment]
It's a challenging problem when you have a shared placeholder that is no longer valid, because the dependencies no longer have a shared latest version. There already exists an issue on the same topic: https://github.com/renovatebot/renovate/issues/4522

Ideally we should not be rebasing each run even if there's a problem like this.

> I would expect Renovate to propose an update to `6.0.1` for all components, until a higher version for all components is available.

But wouldn't that be literally waiting forever, because one of those will never be updated past `6.0.1`? Is it really your goal that Renovate would never tell you about the v7 or v8 upgrades to the other versions? I haven't yet figured out the perfect solution but I know most users don't want us to suppress upgrades forever just because we can't synchronise them.

Question: assuming you now have Renovate able to update dependencies with automated commits/PRs, is there still a need for a placeholder, especially considering the placeholder can cause problems when dependencies get out of sync? Apart from "it would make it easier for a human to jump in and update manually", are there any other advantages to retaining placeholder versions?

**Comment by rassie** [comment]
> It's a challenging problem when you have a shared placeholder that is no longer valid, because the dependencies no longer have a shared latest version. There already exists an issue on the same topic: #4522

Ah, yes, that looks like exactly the same issue I'm describing, so this issue is a duplicate.

> Ideally we should not be rebasing each run even if there's a problem like this.

That's basically the only problem with current behavior -- otherwise it's actually fine, since the developer stays informed about new versions and the MR is a conservative minimal-invasion change.

> > I would expect Renovate to propose an update to `6.0.1` for all components, until a higher version for all components is available.
> 
> But wouldn't that be literally waiting forever, because one of those will never be updated past `6.0.1`? Is it really your goal that Renovate would never tell you about the v7 or v8 upgrades to the other versions?

I think you've right and my expectation is wrong, I would very much like to know about v7 and v8.

> Question: assuming you now have Renovate able to update dependencies with automated commits/PRs, is there still a need for a placeholder, especially considering the placeholder can cause problems when dependencies get out of sync? Apart from "it would make it easier for a human to jump in and update manually", are there any other advantages to retaining placeholder versions?

I haven't actually thought about that in in detail, but that's a viable course at least in our projects. I can certainly imagine something like a parent-POM project, where these placeholders are used in other projects which don't use Renovate or something like that. But in our case, it's a valid point.  

Thank you, I'll be following #4522 for updates.
