### ISSUE TITLE
prConcurrentLimit checks PRs, not branches - many pending branches if prCreation=not-pending

### ISSUE THREAD

**Issue by kurtisvg** [renovatebot/renovate#5162]
**What Renovate type are you using?**

Hosted App - Github

**Describe the bug**

In GoogleCloudPlatform/java-docs-samples, we have a [`prConcurrentLimit=5` set](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/7f400e5bc6a91bd4e60b82ee0b95d7868c26662b/renovate.json#L19). On at least 2 separate occasions we've noticed renovate has gone rogue and ignored this limit. It had over ~40 different PRs open at a single time. We can see from our [master issue](https://github.com/GoogleCloudPlatform/java-docs-samples/issues/1989) that the updates are rate limited, but it's unclear why it temporarily ignored this limit. 

This last time it seems to have triggered after a [modification to our renovate.json](https://github.com/GoogleCloudPlatform/java-docs-samples/pull/1910). However `prConcurrentLimit` wasn't modified. 

**Did you see anything helpful in debug logs?**

I don't seem to have access to the job logs at the given url - maybe because it's an org repo?

**To Reproduce**

Not sure how to reproduce, but we've managed to make it happen twice so far :)

It maybe be related to renovate configuration updates, but it's unclear to me. 

**Additional context**

**Comment by rarkins** [comment]
We need to check the logs. What time stamps can you provide? Eg PR creation times?

**Comment by kurtisvg** [comment]
Taking a look at emails sent, it looks like they all were generated around ~1:25pm PST.

**Comment by rarkins** [comment]
Thanks, and in that case can you tell me some of the newly created PR numbers so that Incan correlate?  BTW were you aware there’s a dashboard where you can check the logs directly in future?

**Comment by kurtisvg** [comment]
>  can you tell me some of the newly created PR numbers so that Incan correlate?

It looks like 1952 - 1958 - here's the [full list](https://github.com/GoogleCloudPlatform/java-docs-samples/pulls?utf8=%E2%9C%93&q=is%3Apr+renovate+created%3A2020-01-15..2020-01-16+).

>  were you aware there’s a dashboard where you can check the logs directly in future?

Yes, but when I go to is I'm not able to surface any jobs. My guess is that this might be because the repo belongs to an Organization instead me specifically, but I'm not sure.

**Comment by rarkins** [comment]
Thanks for the info. I believe the bug is caused by the intersection of `prConcurrentLimit` and `"prCreation": "not-pending"` (which is [now removed](https://github.com/GoogleCloudPlatform/java-docs-samples/commit/267c1478e72c41c34c8188d4939fc5be8d529a36#diff-76e62915fba4048ac877a875e2e3b8d2)).

What goes wrong is that we're counting PRs, not branches. So when there's 4 Renovate PRs open, it thinks "I can create one more" and creates a branch - but not the PR. Then it runs again and does the same, and only stops once one of those branches is no longer in "pending" state and its PR is created. Eventually, all of those pending branches reach succeeded or failed status and get created.

For now, with the removal of custom `prCreation`, I don't think this should happen to you again.

**Comment by kurtisvg** [comment]
Great, thanks for following up. I'll be sure to update here if we experience any more issues.
