### ISSUE TITLE
NuGet: Support for configuring feed version

### ISSUE THREAD

**Issue by fgreinacher** [renovatebot/renovate#5165]
**What would you like Renovate to be able to do?**
The protocol version of a NuGet feed is currently detected via the configured URL:

https://github.com/renovatebot/renovate/blob/d19709aebd9e82e2c8a978ec63d2c3baa7acca09/lib/datasource/nuget/index.ts#L9-L14

This works for the official feed but fails for self-hosted v3 feeds that don't end with `.json` (e.g. Artifactory).

**Describe the solution you'd like**
Configure the protocol version in the `nuget/registryUrls` setting:

```js
module.exports = {
  nuget: {
    registryUrls: [
      { value: "https://my-nuget-v3-feed", protocolVersion: "3" } 
    ],
```

**Describe alternatives you've considered**
- Not using v3 feeds
- Not using Artifactory

**Comment by rarkins** [comment]
The problem, restated:
- The nuget datasource needs to be able to distinguish between v2 and v3 feeds
- For self-hosted feeds, it currently cannot tell directly by looking at the `registryUrls` value

I have two other ideas, please let me know your thoughts:

Idea 1: What if Renovate instead "dynamically" tried to determine the version of each URL? It would only need to determine it once per run and then use the saved value for all subsequent lookups. Assuming there's some URL we can hit that confirms a feed's version is correct or not (e.g. returns 404 if not, and something else if so) then could augment out current logic to instead be:
- Based on the URL, guess what we think it likely is
- Test that first guess, and use it if successful
- If unsuccessful, try the other one

At worst this results in one failed/additional request per run, which is negligible.

Also, this idea is kind of "future proof" in that it will also work for any cases where URLs are automatically determined/extracted from the repository or file system instead of from config.

Idea 2: Instead of destructuring  the string URL into url/value, could we "hack" in the protocol version like `https://my-nuget-v3-feed#renovateProtocolVersion=3` which then gets stripped out before use? This would make it a *lot* less work/complexity config-wise.

**Comment by fgreinacher** [comment]
Thanks for your thoughts!

I somewhat prefer configuring the protocol version explicitly, because that’s closer to what needs to be done when configuring feeds in NuGet.config files (and what renovate would need to consider once we add support for reading those). 

I like your hack idea, just because it’s super lightweight — hopefully 😀

I’ll investigate in whether that’s feasible once I find some free hours!

**Comment by rarkins** [comment]
@fgreinacher I didn't see anything in the nuget.config docs that made me confident that Renovate could know for sure if it's v2 or v3, but did I miss something? If we *can't* be sure from the config then we'd also need the try/fail approach for it too.

**Comment by fgreinacher** [comment]
The docs are very unspecific on this. Most of the samples explicitly define protocol version 3 if necessary. The NuGet client seems to have a [implementation similar to what Renovate currently has](https://github.com/NuGet/NuGet.Client/blob/c5c6ba438f4929e7ebe75e45ad69a8b113f7c388/src/NuGet.Core/NuGet.Protocol/Providers/ServiceIndexResourceV3Provider.cs#L48). Try/fail would be possible, but different to NuGets behavior, so I'd vote for keeping the current behavior plus explicit configuration.

https://github.com/NuGet/NuGet.Client/blob/c5c6ba438f4929e7ebe75e45ad69a8b113f7c388/src/NuGet.Core/NuGet.Protocol/Providers/ServiceIndexResourceV3Provider.cs#L48

**Comment by rarkins** [comment]
How do you explicitly define the protocol version for nuget? Eg is it a specified field?

**Comment by fgreinacher** [comment]
Yes, it's an attribute in `NuGet.config` (see https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#package-source-sections)

```xml(2)
<packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="Contoso" value="https://contoso.com/packages/" />
    <add key="Test Source" value="c:\packages" />
</packageSources>
```

**Comment by rarkins** [comment]
Thanks for clarifying :)

In that case I'd still like to to with `https://api.nuget.org/v3/index.json#protocolVersion=3` so that we can keep registryUrls defined as type url.
