### ISSUE TITLE
missing diff links when mixing npm + docker in a group

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/renovate#5217]
**What Renovate type are you using?**
Renovate App

**Describe the bug**
Normally, in the PR description, `Change` column, there are links to renovate pages showing diffs e.g. https://github.com/brainhubeu/react-carousel/pull/190
<img width="961" alt="Screenshot 2020-01-23 at 21 35 52" src="https://user-images.githubusercontent.com/20856232/73021712-5ee68100-3e28-11ea-8aaf-54dec9e15cc9.png">

However, this PR description https://github.com/brainhubeu/react-carousel/pull/169 doesn't contain such links.
<img width="965" alt="Screenshot 2020-01-23 at 21 36 39" src="https://user-images.githubusercontent.com/20856232/73021806-9a814b00-3e28-11ea-9429-ccdcf99f420c.png">

**Comment by rarkins** [comment]
Renovate can only provide links if either:
- The dependencies/images have declared their source repo in their metadata, or
- The dep->url mappings have been contributed manually to https://github.com/renovatebot/renovate/blob/master/lib/datasource/metadata.ts

In this case, circleci/node does not declare its source repo in image metadata. Although it's probably a special case and ideally would point to the Node.js repo so that release notes can be got from there.

**Comment by piotr-s-brainhub** [comment]
So how can you explain this?
<img width="1309" alt="Screenshot 2020-01-24 at 15 59 53" src="https://user-images.githubusercontent.com/20856232/73078533-aa4d6d80-3ec2-11ea-85b2-3357945c6c32.png">

**Comment by rarkins** [comment]
Sorry, I misunderstood - I thought you were pointing out the circleci/node dependency was missing a link altogether. I think it is the cause though. I suspect if you made your PR npm-only then you'd see the links again, because they are only enabled for npm.
