### ISSUE TITLE
Helm values extract failure due to duplicate keys

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#5298]
Example error from the hosted app:

```
"message": "duplicated mapping key at line 2, column 1:\n    replicaCount: 5\n    ^"
```

We should ignore these duplicate keys and not error.

**Comment by dominik-bln** [comment]
I'll have a look

**Comment by rarkins** [comment]
Thanks. I know we do the same in at least one other of our managers. But you need the tank order you use to support ignoring duplicates.

**Comment by dominik-bln** [comment]
As far as I can tell this was only occurring on updates, at least that is the only place where I could reproduce the problem. I'm not sure how it's possible to get into this situation in the first place because the extraction seems to be skipped in these cases.

Anyways, I think putting a try-catch around the update part makes probably sense either way.

**Comment by rarkins** [comment]
I'll see if the error logs give us any more information too

**Comment by viceice** [comment]
@rarkins are we see those errors or is this fixed?
