### ISSUE TITLE
sluggify and/or truncate branch names to reduce branchName length

### ISSUE THREAD

**Issue by ssube** [renovatebot/renovate#5390]
### Which Renovate are you using?

Renovate Open Source CLI

### Which platform are you using?

GitLab self-hosted

### Have you checked the logs? Don't forget to include them if relevant

With default branch prefix/topic:

```
DEBUG: Committing files to branch renovate/docker-nexus-repo.builds.example.com-renovate-renovate-19.x (repository=renovate-bot/renovate-config, branch=renovate/docker-nexus-repo.builds.example.com-renovate-renovate-19.x)
DEBUG: Error commiting files (repository=renovate-bot/renovate-config, branch=renovate/docker-nexus-repo.builds.example.com-renovate-renovate-19.x)
       "err": {
         "message": "remote: GitLab: Branch name does not follow the pattern '^[-\\/\\w]{1,59}$'
```

We use branch names with a prefix for internal DNS and kubernetes `kind: Service`s, which have a hard limit of 63 characters, so we restrict branch names to 59. Truncating branch names during the deploy was very confusing, and the push rule a much better developer experience.

### What would you like to do?

I'd like to truncate and/or sluggify branch names, so they match the push rule: `^[-\/\w]{1,59}`

Currently working around this by omitting some information:

```
  branchPrefix: 'deps/',
  branchTopic: '{{{depNameSanitized}}}',
```

While that _usually_ works, a long package name would still break.

**Comment by rarkins** [comment]
I've transferred this issue into the main Renovate repo and labeled it as a feature request.

As you've kind of identified, using more compact branches could mostly resolve the problem, but can't be guaranteed unless our branches were made extremely compact.

The next challenge is that branch name is critically important to Renovate, because it determines:
- What updates go together
- How Renovate knows if it's created the same branch/PR before

If Renovate was to arbitrarily truncate branches (e.g. to 59 chars) then it could remove some of the most important information from the end of the branch name - the version. e.g. a minor and a major update of the same dependency might get grouped together because the version information gets stripped from both.

I don't have a perfect answer right now, so have left this as `needs-requirements`.

**Comment by ssube** [comment]
The loss of data/detail and subsequent grouping are concerning, although in most cases, I think we could find unnecessary details to remove: the branches most likely to break are our `docker-nexus-repo.builds.example.com` (longer in reality) docker images, which can get to 100 characters or more. Other bits that come to mind are `github.com/` prefixes from Go packages, version info (already done through `branchTopic`).

Not sure what template syntax is being used for the config - I saw handlebars in `package.json` - but a `substring` or `replace` helper might be enough. The latter would let us remove prefixes as well as sanitize other characters.

There are quite a few packages (the babel, eslint, and webpack families come to mind) for which groups are probably a better solution. I'll look into getting those set up too.

**Comment by rarkins** [comment]
So if we supported a handlebars "replace" function then at least you should be able to fix up the problem yourself (e.g. replace github.com and your nexus repository URLs with something shorter). Alternatively we could give the concept "first class support" some some type of aliases or branch replace object, but I'm not sure it's necessary to make it so complicated.

**Comment by rarkins** [comment]
FYI I added a `replace` function to handlebars yesterday.

Example of using it from https://github.com/renovatebot/renovate/blob/aa7f29127554b63aac08b53cbfe88749fc9b0295/lib/manager/npm/index.ts#L17:

```
{{replace '/' '%2f' depName}}
```

So you could do something similar like this with config:

```json
{
  "docker": {
    branchTopic: "{{{replace "docker-nexus-repo.builds.example.com" "" depNameSanitized}}}-{{{newMajor}}}.x"
  }
}
```

**Comment by rarkins** [comment]
A new idea from #8496 is to use a hash function. @Turbo87 can you elaborate on your proposed approach and reasoning for the various design choices?

**Comment by Turbo87** [comment]
interestingly we seems to have a rather similar setup to what @ssube describes above. we are also using kubernetes and we use the branch names as the subdomains, which limits their lengths.

I was aware of the issue that we can't simply cut off the regular `branchTopic` since it would lead to potential conflicts, so my naive idea was to use a hashed version of the `branchTopic` and then cut off the hash after a configurable number of characters. This allows us to keep all the information in the `branchTopic` that it previously contained, but also to shorten it with a significantly reduced chance of conflicts.

The implementation in #8496 is using hex encoding for the output to avoid using non-URL-safe characters, but even if we cut it off after 10 characters that leaves us with `16^10` possible hash values (1,099,511,627,776), which should be sufficient to avoid conflicts.

I also decided to only hash the `branchTopic`, not the `branchName`, since it might still be beneficial to prefix the branch name with e.g. `dep-`, which the `branchPrefix` then still allows.

**Comment by rarkins** [comment]
Is the chance of a hash collision realistically a problem? I don't think we have any reason to worry about *malicious* collisions and would consider essentially any hashing algorithm including md5 to be "safe enough".

Presumably there is no need to give Renovate bot admins *control* of the algorithm choice either, because it's not being consumed by any outside system. We simply must have a hash algorithm that's *safe enough*, and produces url-safe characters.

We definitely need to keep `branchPrefix` as-is, i.e. unhashed, but the rest of the branch could/should be hashed (including `additionalBranchPrefix` if configured).

So, could we have something as simple as a `maximumBranchLength` field - defaulting to 0 or null - and everything else is "implementation details"? There's two possibilities:
- only hash if the regular branch name exceeds the maximum length, or
- hash all branches if this option is enabled

If you were having problems with url-safe branch names *before* then hashing everything in a url-safe manner may then solve two problems at once?

**Comment by Turbo87** [comment]
> Is the chance of a hash collision realistically a problem?

no, with a 1:1,099,511,627,776 at a 10 character limit, I don't think it's a realistic problem.

> and would consider essentially any hashing algorithm including md5 to be "safe enough".

absolutely. I only used SHA512 since it appears to be the default in the `hasha` library which was already used by other parts of the codebase.

> Presumably there is no need to give Renovate bot admins control of the algorithm choice either, because it's not being consumed by any outside system. We simply must have a hash algorithm that's safe enough, and produces url-safe characters.

agreed. the proposal in the PR only lets the admins turn it on/off and configure the length, but **not** the actual hashing algorithm or output encoding.

> but the rest of the branch could/should be hashed (including additionalBranchPrefix if configured).

including `additionalBranchPrefix` in the hash might be a bit complicated since that is added by the `branchName` template and at that point the hashing has already happened. hashing only parts of the template might be complicated.

while writing this I realized that this might also be achievable with handlebars helpers. for example we could allow admins to do something like this:

```json
branchName: "{{{branchPrefix}}}{{md5 (concat additionalBranchPrefix branchTopic) length=10}}"
```

> So, could we have something as simple as a maximumBranchLength field - defaulting to 0 or null - and everything else is "implementation details"?

I think I would find this a bit confusing since it wouldn't match what the admin configures in the `branchName` and `branchTopic` options. I named the option in my PR `hashBranchTopic` to make it clear what part of the branch name would be hashed. If I saw an option called `maximumBranchLength` I would think of it truncating the branch name, but I would be quite surprised if it suddenly started to hash things then.

> If you were having problems with url-safe branch names before then hashing everything in a url-safe manner may then solve two problems at once?

we worked around it by removing the `.x` from the `branchTopic` and all of our npm dependency names are already URL safe, so that part isn't much of a problem. the problem becomes more relevant though when the `latin1` or `base64` output options of `hasha` are used, because they can include non-URL-safe characters.

**Comment by rarkins** [comment]
> I think I would find this a bit confusing since it wouldn't match what the admin configures in the `branchName` and `branchTopic` options. I named the option in my PR `hashBranchTopic` to make it clear what part of the branch name would be hashed. If I saw an option called `maximumBranchLength` I would think of it truncating the branch name, but I would be quite surprised if it suddenly started to hash things then.

Whatever we do will be an opt-in feature, and we'd make sure it's documented. If someone enables the feature without reading the paragraph explaining what it does and they're then *confused*.. I can live with that. After all everything will still *work* even if they're confused.

Additionally I ideally don't want to link it to `branchTopic` because that's something perhaps 99% of Renovate users don't normally have any familiarity with, and I also would ideally like to improve on it - potentially changing names or meanings - in a major release one day.

Renovate users wouldn't care about the *topic* length unless we make them care - they care about the branch length, so ideally that's how we let them configure it.

I still think:
- Let users define the maximum branch length, and document that if enabled then branch names will be partially hashed
- Don't make them think about how branch names are constructed
- I don't mind using an option name which is more descriptive, but can't think of anything perfect. Maybe `hashBranchToLength` ?

**Comment by Turbo87** [comment]
> Don't make them think about how branch names are constructed

I think in that case we would need to deprecate the `branchName` and `branchTopic` options though, no?

as I mentioned above, since `branchName` by default is defined as `{{{branchPrefix}}}{{{additionalBranchPrefix}}}{{{branchTopic}}}` I don't know how to hash only `additionalBranchPrefix + branchTopic` while keeping the `branchPrefix` the same, especially if the user reconfigures the composition of `branchName`.

**Comment by viceice** [comment]
🤔 i like `branchName: "{{{branchPrefix}}}{{hash (concat additionalBranchPrefix branchTopic) length=10}}"` this gives the any user the abillity to configure hashing parts as required.

we can internall add a hash helper to the template compiler

**Comment by rarkins** [comment]
> I think in that case we would need to deprecate the `branchName` and `branchTopic` options though, no?

No. But this option would not be compatible with manually configuring `branchName`.

**Comment by Turbo87** [comment]
@viceice Ember.js is a pretty big user of Handlebars and there is a `hash` helper there that behaves quite a bit differently (see https://guides.emberjs.com/release/components/helper-functions/#toc_the-hash-). I would recommend to use some other helper name if we decide to go that way 😉

**Comment by Turbo87** [comment]
@rarkins what you're suggesting is something like this?

```js
function generateBranchName() {
  if (options.maximumBranchLength) {
    let hashLength = options.maximumBranchLength - branchPrefix.length;
    return branchPrefix + hasha(additionalBranchPrefix + branchTopic).slice(0, hashLength);
  }

  // ...
}
```

**Comment by rarkins** [comment]
@Turbo87 yes, that would be the logic.

BTW I'm thinking about what steps to take to deprecate editing of `branchName` officially. At a minimum to just make sure `branchPrefix` can be enforced as a top-level option and branchName is then branchPrefix + branchPayload or something similar in name. Not sure branchSuffix works without something in the middle, and branchContent is more likely to confuse
