### ISSUE TITLE
packageRules paths does not work for gradle multi-project files

### ISSUE THREAD

**Issue by sll552** [renovatebot/renovate#5403]
**What Renovate type are you using?**

self-hosted renovate connected to self-hosted GitLab

**Describe the bug**

I have the following renovate config for a repo, that should basically assign merge requests based on the path of the file in which the version of the dependency is changed (here if it changed somewhere under `sample/project/src/`):
```json
{
  "recreateClosed": true,
  "packageRules": [
    {
      "paths": ["**"],
      "assignees": ["user1"],
      "prCreation": "immediate"
    },
    {
      "paths": ["sample/project/src/**/*"],
      "assignees": ["user2"],
      "prCreation": "immediate"
    }
  ]
}
```
The repo contains a gradle multi-project build with the main `build.gradle` in root and some `.gradle` files in sub dirs.

It works for a Dockerfile in `sample/project/src/main/Dockerfile` but does not work for a gradle file that defines dependencies in `sample/project/src/main/dependencies.gradle`.
Just to be clear: in both cases MRs get created but for the dependencies defined in the `dependencies.gradle` file `user1` gets assigned instead of `user2` but for the Dockerfile its correctly assigning `user2`.

It seems that despite renovate is able to update the dependency in the correct file, it ignores path rules that match the file.

**Did you see anything helpful in debug logs?**

renovate does not seem to log how the assignee was determined even with debug enabled.

**To Reproduce**

Unfortunately I can't post the full repo here because it is closed source company code but the following files should be enough to create a working example:

settings.gradle:
```groovy
def tree = fileTree(dir: './', includes: ['**/artifacts.gradle', '**/dependencies.gradle'])
def projlist = []
tree.each {File f ->
  def projpath = f.getParent().replace(rootDir.getAbsolutePath(), '').replace(File.separator, ':')
  projlist << projpath
}
include(projlist as String[])
```

.renovaterc.json:
```json
{
  "recreateClosed": true,
  "packageRules": [
    {
      "paths": ["**"],
      "assignees": ["user1"],
      "prCreation": "immediate"
    },
    {
      "paths": ["sample/project/src/**/*"],
      "assignees": ["user2"],
      "prCreation": "immediate"
    }
  ]
}
```
sample/project/src/main/dependencies.gradle:
```gradle
configurations {
  lib
}
dependencies {
  lib group: 'org.apache.xmlbeans', name: 'xmlbeans', version: '2.4.0', ext: 'jar', changing: false
}
```
sample/project/src/main/Dockerfile:
```Dockerfile
FROM centos:7.2.1511
```
This creates 4 MRs:
* 2 for `org.apache.xmlbeans` (major and minor version) assigned to `user1`
* 2 for `centos` (major and minor version) assigned to `user2`

`org.apache.xmlbeans` is therefore assigned to the wrong user (should be `user2`)

**Comment by rarkins** [comment]
This would be because the `paths` selector is based on whatever is returned in the `packageFile` field, which is probably the root `build.gradle` in this case. For cases where a manager like gradle has the capability to replace values in *other* files, and it knows the actual file name as part of its extract process, we could have them return a new field like `editFile` with the full filename of the file that contains the value to be edited. The `paths` selector could then check against both `packageFile` and `editFile` to apply rules.

**Comment by sll552** [comment]
This would be a very welcome feature and I think its also more intuitive to handle it this way for the cases you mentioned

**Comment by rarkins** [comment]
Needs a reproduction so that we can confirm if it's still applicable to our new gradle manager

**Comment by Churro** [comment]
There are very solid indicators that this is not an issue anymore since the removal of the `deepExtract` functionality.

Gradle files are now parsed one by one:
https://github.com/renovatebot/renovate/blob/b4f5f88526c8ed4870a62bae1809feca9e535bdd/lib/modules/manager/gradle/extract.ts#L40

Whenever a dependency is extracted, the Gradle file containing the definition, is set as a reference:
https://github.com/renovatebot/renovate/blob/b4f5f88526c8ed4870a62bae1809feca9e535bdd/lib/modules/manager/gradle/parser.ts#L154

Tests like the following warrant this behavior:
https://github.com/renovatebot/renovate/blob/b4f5f88526c8ed4870a62bae1809feca9e535bdd/lib/modules/manager/gradle/extract.spec.ts#L105-L136
