### ISSUE TITLE
Support renovating apk add commands in Dockerfiles

### ISSUE THREAD

**Issue by felixfbecker** [renovatebot/renovate#5422]
**What would you like Renovate to be able to do?**
Out builds frequently break because versions get removed from the `apk` repositories and replaced with newer versions. When using pinned versions in the Dockerfiles (which is a good idea), this causes build failures. It would be nice if Renovate could detect `apk add` lines in Dockerfiles and proactively open PRs to update.

**Describe the solution you'd like**
Renovate could use a simple regex match to detect lines with `apk add` (should work across multiple lines too) in Dockerfiles and shell scripts.

**Describe alternatives you've considered**
#1938, but that seems up in the air

**Additional context**
Example PR: https://github.com/sourcegraph/sourcegraph/pull/8342/files

**Comment by rarkins** [comment]
Looks like the first step is an `apk` datasource. After that, it would be a good candidate for generic version replacement or a dedicated `apk` manager.

**Comment by rarkins** [comment]
Docs on the regex manager just released: https://docs.renovatebot.com/modules/manager/regex/

This now needs an `apk` datasource added.

**Comment by rarkins** [comment]
@ppmathis is this also enabled by your repology datasource?

**Comment by ppmathis** [comment]
This specific issue can indeed be solved by using the new repology datasource. While I am mostly working with Alpine packages, Repology supports all other kinds of OS repositories.

As Debian unfortunately does not keep old package versions, a Dockerfile with outdated package versions immediately breaks as described by @felixfbecker. As I was struggling with the same issue on Alpine, I've decided to configure Renovate to group all  OS package upgrades together, as this will guarantee that status checks may still pass when multiple dependencies are outdated.

First of all, you have to configure a regex manager to parse version environment variables within your Dockerfile, e.g.:

```json
{
  "regexManagers": [
    {
      "fileMatch": [
        "(^|/)Dockerfile$"
      ],
      "matchStrings": [
        "#\\s*renovate:\\s*datasource=(?<datasource>.*?) depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?\\sENV .*?_VERSION=\"?(?<currentValue>.*?)\"?\\s"
      ],
      "versioningTemplate": "{{#if versioning}}{{versioning}}{{else}}semver{{/if}}"
    }
  ]
}
```

Then you may configure a package rule for grouping all OS package upgrades together to avoid CI failure when multiple packages are out of date, as this will allow Renovate to upgrade these dependencies in one shot. Please note that you may have to change/adjust the package patterns based on your needs, as the example would match all dependencies named `debian_stable/<anything>`:

```json
{
  "packageRules": [
    {
      "datasources": [
        "repology"
      ],
      "packagePatterns": [
        "^debian_stable/"
      ],
      "separateMajorMinor": false,
      "groupName": "debian packages",
      "groupSlug": "debian"
    }
  ]
}
```

After that has been done, you may start adding environment variables to your Dockerfile which contain the package version and annotate them using comments, which the regex manager will end up parsing:

```Dockerfile
# renovate: datasource=repology depName=debian_stable/make-dfsg versioning=loose
ENV MAKE_VERSION="4.2.0"
# renovate: datasource=repology depName=debian_stable/libssl-dev versioning=loose
ENV LIBSSL_DEV_VERSION="1.1.1c-0+deb10u3"
```

The  examples above will look for the newest version of `make-dfsg` within the `debian_stable` repository on Repology, which can be found [here](https://repology.org/repository/debian_stable). Repology is still working on adding version-specific repositories for Debian (e.g. Debian 9, Debian 10, ... instead of stable/unstable), but for now `debian_stable` just always refers to the newest version.

Please note that in case of Debian, it is usually recommended to specify the source package name as `depName`. You may find that name by looking for `Source: ` in the output of `apt info <package>` or by looking at the package [on the Debian website](https://packages.debian.org/buster/make). The Debian package mappings are fairly complex in Repology and while the datasource has some heuristics for resolving ambiguous package results, the source package is usually more reliable. If any specific issues with some packages come up, please feel free to tell me, as I'm happy to analyze such cases in more detail.

Last but not least, you may find a example of the above instructions (contains both Debian and CentOS, although only the first is relevant to you) at [snapserv/renovate-test](https://github.com/snapserv/renovate-test). You may also take a look at [this PR](https://github.com/snapserv/renovate-test/pull/4) to see how these grouped package updates end up.

If you want to see a more advanced example, you may take a look at [this repository](https://github.com/snapserv/docker-netbox/blob/master/Dockerfile). While it is using Alpine, you can see how it uses regex managers to keep all dependencies of the image up-to-date.

**Comment by viceice** [comment]
We should add the grouping info to the docs
