### ISSUE TITLE
Add an option to only match using minimatch

### ISSUE THREAD

**Issue by karfau** [renovatebot/renovate#5438]
**What would you like Renovate to be able to do?**
When trying to configure a file on the root directory that also exists in subdirectories, it can currently only be done by applying additional glob syntax (e.g. `+(package.json)`).

**Describe the solution you'd like**
>  Maybe we could introduce an option like "pathGlobOnly" defaulting to false and let people enable it for glob-only matching, which I think then would behave more sensibly.

**Describe alternatives you've considered**
Since more people might be familiar using regular expressions, there could also be an option to treat paths (only in the scope of `packageRules`?) as such, instead of using `.includes` & `minimatch`.

**Additional context**
See https://github.com/renovatebot/config-help/issues/519 for a related discussion

**Comment by rarkins** [comment]
I'm not sure this is needed now, as the workaround seems like a more elegant approach. What do you think?

Here's the updated documentation from #5433:

### paths


Renovate will match `paths` against both a partial string match or a minimatch glob pattern. If you want to avoid the partial string matching so that only glob matching is performed, wrap your string in `+(...)` like so:

```
  "paths": ["+(package.json)"],
```

The above will match only the root `package.json`, whereas the following would match any `package.json` in any subdirectory too:

```
  "paths": ["package.json"],
```
