### ISSUE TITLE
regex manager docs: enumerate data sources

### ISSUE THREAD

**Issue by mykter** [renovatebot/renovate#5701]
**What would you like Renovate to be able to do?**
When using regex manager (#1938), find the ids of all the data sources that can be used

**Describe the solution you'd like**
The docs should either explain how to identify the id for each source, or just provide a complete list.

**Describe alternatives you've considered**
Go hunting through the code. Guess. Try and find a config-validation mode, run it locally on guessed ids.

**Comment by rarkins** [comment]
There's some TBD code to fill this in here in the docs: https://docs.renovatebot.com/modules/datasource/

**Comment by HonkingGoose** [comment]
This issue is 3 years old, the [`manager/regex/readme.md` file](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/regex/readme.md) has more information now. And we have a list of `Supported Datasources` in the [Renovate docs for Datasources](https://docs.renovatebot.com/modules/datasource/). I don't know if those things are enough to consider this issue fixed, I'll let the maintainers decide. 😉 

Related issue:

- #15075
