### ISSUE TITLE
Gitea: status will never be green

### ISSUE THREAD

**Issue by NateScarlet** [renovatebot/renovate#5775]
There is a bug in lib/platform/gitea/gitea-helper.ts :

https://github.com/renovatebot/renovate/blob/63b5094915bfa85a9de849950fe0b7c749218ad6/lib/platform/gitea/gitea-helper.spec.ts#L792-L797

says recent status is most important 

But it tested in same order as https://github.com/renovatebot/renovate/blob/63b5094915bfa85a9de849950fe0b7c749218ad6/lib/platform/gitea/gitea-helper.ts#L179-L186

If status ordered as  `pending`, `success`,
`getCombinedCommitStatus` will always returns `pending`. @ppmathis 
https://github.com/renovatebot/renovate/blob/63b5094915bfa85a9de849950fe0b7c749218ad6/lib/platform/gitea/gitea-helper.ts#L510-L513

## Fix

change 
https://github.com/renovatebot/renovate/blob/63b5094915bfa85a9de849950fe0b7c749218ad6/lib/platform/gitea/gitea-helper.ts#L511

to
```js
function filterStatus(data) {
  const ret = {};
  for (const i of data) {
    if (
      ret[i.context] &&
      new Date(ret[i.context].created_at) >= new Date(i.created_at)
    ) {
      continue;
    }
    ret[i.context] = i;
  }
  return Object.values(ret);
}
```
```js
for (const cs of filterStatus(res.body)) {
```

**Comment by viceice** [comment]
@NateScarlet Feel free to send a PR to fix it. 🙃

**Comment by ppmathis** [comment]
@NateScarlet Thanks for the report. You are right, the API endpoint seems to return all previous states with the same context instead of only the most recent one, so the implementation would have to filter for the most recent state of the given context instead of analyzing all returned states. Feel free to submit a PR if you want, otherwise I'm also happy to take a look at it.
