### ISSUE TITLE
Vulnerability alerts based on open source tools

### ISSUE THREAD

**Issue by bilby91** [renovatebot/renovate#6277]
**What would you like Renovate to be able to do?**
I would like renovate to be able to use open source tools to detect vulnerability alerts instead of only depending on the platform vulnerabilities system (currently only GitHub).

**Describe the solution you'd like**
I was thinking that maybe we could extend the vulnerabilities module so that we could enrich this alerts not only with the platform system but with other tools like the following:

- https://github.com/rubysec/bundler-audit
- https://github.com/RustSec/cargo-audit
- https://github.com/mirego/mix_audit

I was thinking that maybe this could be modeled as `plugins` that you could add to your configuration.

**Comment by bilby91** [comment]
What do you think about a feature like this one @rarkins ? I might have some time to prototype something initially for `bundler-audit`

**Comment by rarkins** [comment]
I think it needs planning for how it would fit in. I definitely don't want any "hacked-in" solution. The advantage GitHub vulnerabilities have is that they are already *ready* when we start a run on the repo. Any other type of checking would need to be inserted somewhere in the middle of the job.

**Comment by zejji** [comment]
This feature would be incredibly useful.

We are using Bitbucket, so cannot take advantage of the GitHub vulnerabilities feature. However, Renovate's default position of raising PRs for all dependency updates generates far too much noise for us, since the Node ecosystem is incredibly fast-moving and we are required to perform manual tests on all releases (even for minor and patch updates).

Ultimately we are primarily interested in automating required security updates and spotting potential vulnerabilities, i.e. other updates are nice-to-haves only.

Is this feature still on the near roadmap by any chance?

**Comment by tennox** [comment]
FYI GitLab's Vulnerability DB has a variant that is allowed to be use by 3rd party tools:
https://gitlab.com/gitlab-org/advisories-community

& tools to check for those dependencies:
https://gitlab.com/gitlab-org/security-products/analyzers/gemnasium

Sadly, I cannot assess how much effort it would be to integrate with renovate / if it's worth it.
But I thought the info might help :)

(& I thought this is the most relevant issue)
Thanks for the great product! :heart:

**Comment by philippe-granet** [comment]
See #6562 
@JamieMagee is currently implementing a solution based on [Open Source Vulnerabilities](https://osv.dev)

**Comment by meskio** [comment]
If renovate decides to go into integrating language specific vulnerability checkers another to include in the list is the go vuln check tool: https://go.dev/blog/vuln

**Comment by viceice** [comment]
i think this can be closed as resolved. the new feature was released on renovate

@JamieMagee @rarkins WDYT?
