### ISSUE TITLE
Define custom dependencies from yaml file

### ISSUE THREAD

**Issue by machine424** [renovatebot/renovate#6301]
Thank you for this great tool.

**What would you like Renovate to be able to do?**
Suppose I have a yaml file (or any file) with a key:
```
...
dep-version: v1.0.0
foo: bar
...
```
Is there a way to tell (teach) Renovate to watch `dep` (let's say a python package) releases and update the key's value ? Can we manually define dependencies for Renovate ? Can renovate parse the file and detect that `dep-version`'s value correspond to sth that can be updated ?

If it's not already the case and you would like supporting this, I could help implementing.

**Comment by rarkins** [comment]
I've looked at JSON pointer and JSONpath and don't fully like either. Unfortunately I don't see any other feasible approaches yet.

Here's my thinking so far:
- The goal of this is to have a custom manager similar to regex manager but which lets you operate on a JSON structure as input instead of raw text
- We could support not just JSON but also well-known formats like YAML and TOML. Parsing could be done automatically based on file extension but we could also support a config override to specify the parser type
- The function should return an array of extracted dependencies and ideally *not* need you to configure one manager per dep or dep type

A good aim would be that this manager would be capable of extracting a basic `package.json` (e.g. including `dependencies` and `devDependencies`) although it could be a little challenging.

I'm also thinking we lean heavily on handlebars templating again.

**Comment by brad-jones** [comment]
What would be really cool is if renovate supported some kind of plugin based architecture. Maybe based on gRPC similar to how hashicorp tools work or even just a javascript module loaded at runtime. So that one could add custom / non-standard package managers to renovate without having to fork the project.

**Comment by rarkins** [comment]
I'm going to close in favor of #15193
