### ISSUE TITLE
Dependency Dashboard reporting some merged PRs are unmerged + closed

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/renovate#6336]
As seen here https://github.com/HRZNStudio/playhrzn-k8s/issues/37

With `masterIssue` enabled, it seems there are some pull requests indicated to be closed unmerged whereas they are all merged.

**Comment by rarkins** [comment]
We need to think of alternate wording. The ones in this list indicate that:
- There is an update/PR pending
- An identical update/PR already existed but is no longer open
- Therefore, the pending PRs are suppressed

Normally this is because the original PR was closed, and normally that's because the user wants to ignore it.

But there are also other cases:
- Something was wrong with the upgrade so the user manually reverted it later. Therefore it's good that the PR is being suppressed
- The user may have added the old version to somewhere else in a monorepo and now that old version needs updating but it's being suppressed
- Maybe the user has a test repo they're playing around with and so they are upgrading and downgrading and want to test and upgrade again but it's being suppressed

**Comment by ChipWolf** [comment]
@rarkins I'd normally be inclined to agree with you, but I just removed the 'branch protection rules' from master and they all merged in
