### ISSUE TITLE
eslint plugin

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#648]
As suggeseted by @destroyerofbuilds as part of https://github.com/singapore/renovate/issues/647#issuecomment-320741870:

> Maybe a eslint-plugin-renovate that validates your renovate configuration in your project, ensuring all options are valid, no duplicated options, no configuration that leads to no effect (such as if I managed to set pin to true and false for all dependencies, causing renovate to be unable to do anything) etc.

**Comment by mbrevda** [comment]
Perhaps it would be simpler to just check this server side and open an issue if the config is invalid or problematic?

**Comment by destroyerofbuilds** [comment]
> Perhaps it would be simpler to just check this server side and open an issue

In the short term perhaps.

However, I would rather not submit an invalid configuration to my project's `master` branch to begin with. Once submitted `renovate` may not be able to upgrade my project until I notice the filed issue you mentioned and submit a fix.

Moving validation to build-time improves my project's mean-time-to-recovery by effectively eliminating outages caused by invalid configuration.
