### ISSUE TITLE
Renovate suggests versions of libraries that do not exist

### ISSUE THREAD

**Issue by rahulsom** [renovatebot/renovate#6629]
**What Renovate type are you using?**

Hosted App on Github.

**Describe the bug**

Renovate attempts to update a library to a newer version. The problem is that the version does not exist in Maven Central.
Here's the PR - https://github.com/rahulsom/grooves/pull/555
Here's Maven Central's page for that library - https://search.maven.org/artifact/org.codehaus.groovy.modules.http-builder/http-builder

**Did you see anything helpful in debug logs?**

This is hosted

**To Reproduce**

1. Create a gradle project with a `build.gradle` that looks like this.
    ```groovy
    buildscript {
        repositories {
            mavenCentral()
            gradlePluginPortal()
        }
        dependencies {
        }
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        compile 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.1'
    }
    ```
2. Add a gradle wrapper using `gradle init`.
3. Add a `renovate.json` that looks like this
    ```json
    {
      "extends": [
          "config:base"
      ],
      "automerge": true
    }
    ```
4. Push to github and wait for renovate to send a PR.

**Additional context**

**Comment by rarkins** [comment]
I can confirm that the version 0.7.2 you see in the PR is coming from https://plugins.gradle.org/m2/org/codehaus/groovy/modules/http-builder/http-builder/maven-metadata.xml and not maven central.

@ikesyo do you have any insight into what might be going wrong here?

**Comment by rarkins** [comment]
`registryUrls` are set per-repo here: https://github.com/renovatebot/renovate/blob/93130c56340b4c81ebe826a31073bb8c175db042/lib/manager/gradle/gradle-updates-report.ts#L139

It seems like repos are collected per-project here: https://github.com/renovatebot/renovate/blob/93130c56340b4c81ebe826a31073bb8c175db042/lib/manager/gradle/gradle-updates-report.ts#L47-L51 and here: https://github.com/renovatebot/renovate/blob/93130c56340b4c81ebe826a31073bb8c175db042/lib/manager/gradle/gradle-updates-report.ts#L101

So it seems like this might be a design flaw, because we collect a single set of registryUrls to be shared by all dependencies.

**Comment by rarkins** [comment]
@zharinov can you check if `gradle-lite` handles this correctly?

**Comment by zharinov** [comment]
For `gradle-lite` it seems to be fixed

**Comment by rarkins** [comment]
Please use either `:enableGradleLite` or `:switchToGradleLite` presets
