### ISSUE TITLE
Provide custom environment variable configuration option

### ISSUE THREAD

**Issue by candrews** [renovatebot/renovate#6758]
**What would you like Renovate to be able to do?**

With [`trustLevel`](https://docs.renovatebot.com/self-hosted-configuration/#trustlevel) set to `low`, no environment variables are passed through.

With [`trustLevel`](https://docs.renovatebot.com/self-hosted-configuration/#trustlevel) set to `high`, all environment variables are passed through.

I'd love to see another option, where custom environment variables can be provided.

**Did you already have any implementation ideas?**

One approach would be for `config.js` to have a new option, "environment" demonstrated by this configuration:
```javascript
module.exports = {
    environment: {
        MY_VAR: "my value",
        PASSED_THROUGH: process.env.PASSED_THROUGH
    }
}
```
Ideally, this would work with `trustLevel` set to low.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**
Not really... setting `trustLevel` to high exposes all environment variables, and there are some that I really don't want to expose (such as the git private key).

**Is this a feature you'd be interested in implementing yourself?**
Probably not? I'm fluent in a number of languages, but typescript isn't currently one of them.

**Comment by viceice** [comment]
You forgot to fill which renovate version and platform are you using. So please fill the full issue template. Thanks

**Comment by candrews** [comment]
> renovate version and platform

Renovate Open Source CLI (Self hosted, docker, `renovate/renovate:latest`)

```
$ renovate --version
21.29.3
```

Thanks!

**Comment by rarkins** [comment]
I think a new admin option could be ok: an array of strings, that lists env variables to pass through for child processes.

I had also been thinking about letting repo configs specify literal env variable values to pass through, until I saw this article that made me think we need some controls: https://www.elttam.com/blog/env/

**Comment by candrews** [comment]
> I think a new admin option could be ok: an array of strings, that lists env variables to pass through for child processes.

I think instead of only allowing pass through, it would be better to specify both name and values for environment variables available to the child processes as given in the description of this issue. That way, the admin could calculate new environment variables, or modify existing ones, as appropriate. For example, I have a use case where I have an environment variable containing a username, another containing a password, and a third containing a URL, and I'd like to use javascript in config.js to combine the 3 into a new environment variable containing a URL with the username and password embedded in it.

> I had also been thinking about letting repo configs specify literal env variable values to pass through, until I saw this article that made me think we need some controls: https://www.elttam.com/blog/env/

Agreed - this should be an admin-only `config.js` configuration option.

**Comment by rarkins** [comment]
Proposed solution:

Add a new admin option `customEnvValues` which is an object of key/value strings. If configured, these env values will be added to every child process env, regardless of `trustLevel`. I think probably best to apply them *after* other env values, so that they can be used to override (although I can't think of a use case for that yet).

**Comment by hisener** [comment]
I have also a use-case for this feature request. We have a private registry source in our `Pipfile`s. Something like:

```
[[source]]
url = "https://'${PRIVATE_PYPI_USERNAME}':'${PRIVATE_PYPI_PASSWORD}'@private-pypi-uri/simple/"
```

I have a host rule and a registry URL in the config file, so Renovate can find the upgrade for dependencies but when it delegates to the sidecar container (`renovate/python`), it fails with the following error:

```
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for internal-dependency==version
```

Because the environment variables are missing. If I pass the required environment variables, it can resolve the dependencies and update `Pipfile.lock` file as expected. 

```
docker run -it --rm -v $(pwd):/opt/renovate -e PRIVATE_PYPI_USERNAME=${PRIVATE_PYPI_USERNAME} -e PRIVATE_PYPI_PASSWORD=${PRIVATE_PYPI_PASSWORD} renovate/python:3.8.6 /bin/bash
```

@rarkins I can pick up this issue. I looked at [`exec` function]( https://github.com/renovatebot/renovate/blob/master/lib/util/exec/index.ts) a bit but a few pointers would definitely help.

**Comment by rarkins** [comment]
@hisener I think the main logic needing updating is here: https://github.com/renovatebot/renovate/blob/326c00091deceef23add97c6c14aad010c9a137c/lib/util/exec/index.ts#L49-L84

There's two possible way to approach this:
1. Have it as an array of env var names. If they are defined in the environment then pass the values to the child processes. In other words you need to define them in env *plus* add them to the new custom env array
2. Have an object of name:value pairs so you define them just once.

I'm not sure which is preferred? Also not sure if there's any elegant way to allow both approaches, e.g. allowing it to be an object *or* array.

**Comment by hisener** [comment]
The first approach is more convenient for my use case because I already pass those credentials for maven and npm, but it might be annoying for other people since it requires two steps. Also, it allows passing Renovate generated environment variables (say, for example, the main process does `process.env.KEY=VALUE`). I don't know if there is a use case for this.

OTOH, we could achieve passing the main process' environment variable to the child process with the second approach.

```
"extraEnvForChild": {
  "KEY": "VALUE",
  "ANOTHER_KEY": process.env.KEY_FROM_MAIN_PROCESS
}
```

So, I am in favor of the second approach if we can use `process.env` in the configuration file. WDYT?

**Comment by viceice** [comment]
`process.env` is only usable in bot `config.js`.

@rarkins what about adding a new env dictionary object to hostRule and allo reuse of secrets in values. So we can pass the env to exec / docker layer?

I'm not sure if this causes any security implications. 🤔

**Comment by hisener** [comment]
IMHO the solution should be more generic since binding it `hostRule` will not cover other use cases.

Given that `process.env` doesn't work, I am in favor of the second approach. The first approach would be cumbersome and would not make sense, say, for example if you want to set `MAVEN_OPTS` environment variable for the child process. It's not secret and not applicable for the main process. In the second approach, we might need to duplicate some values but at least it's simpler.

**Comment by viceice** [comment]
You are right, the env dict should be in package rule instead of host rule. 🤦‍♂️
