### ISSUE TITLE
Creating PRs only for critical vulnerabilities

### ISSUE THREAD

**Issue by janbaer** [renovatebot/renovate#6949]
**What would you like Renovate to be able to do?**

We would like to create PR's only for critical vulnerability issues, which would be reported when running `yarn audit --level-critical`
Is this possible at the moment, and if yes, how would it possible? Thanks!

We're using a self-hosted Bitbucket server.

**Comment by rarkins** [comment]
Dependent on / semi-duplicate of #6027

Renovate only supports GitHub vulnerability alerts today because those are very easy to query and use (GitHub's backend already does the indexing and calculation).

[WhiteSource for Developers](https://www.whitesourcesoftware.com/whitesource-for-developers/) is a commercial solution supporting Bitbucket Server that includes Renovate + WhiteSource's vulnerability scanning. i.e. it achieves the same thing as you're after, and the WhiteSource database includes everything in the npm vulnerability DB plus other sources.

**Comment by janbaer** [comment]
Thanks for the quick clarification
