### ISSUE TITLE
GitHub: Detect branch protection per-baseBranch

### ISSUE THREAD

**Issue by rarkins** [renovatebot/renovate#7077]
**What Renovate type are you using?**

N/A

**Describe the bug**

Renovate detects branch protection only for the default branch and then applies it to all base branches.

**To Reproduce**

1. Create a simple repo with default branch and a second branch (e.g. `next`)
2. In the `renovate.json` in the default branch, configure `"baseBranches": ["next"]`
3. Enable branch protection in the base branch, e.g. PR reviews reviewed

Then, observe that Renovate is blocked thinking it needs reviews when actually `next` doesn't need any reviews.

**Additional context**

https://github.com/renovatebot/config-help/issues/813#issuecomment-679024253

**Comment by viceice** [comment]
Maybe we should be more optimistic and try always automerge and only check for protection if merge failed.

**Comment by rarkins** [comment]
Before we had the proactive approach, a lot of people said our previous try/fail approach was annoying or sub-optimal. It could mean a lot of unnecessary API failures.

**Comment by bodinsamuel** [comment]
Can we just have an option to disable the check?

**Comment by rarkins** [comment]
@bodinsamuel which specific branch protections are blocking you currently?

**Comment by bodinsamuel** [comment]
The one mentionned in the issue, when using a baseBranch without protection and master with protection.
On top of that, the PR do not mention anything about branch protection and will just report ` Automerge: Enabled.` instead of `Automerge: Require approval`

**Comment by rarkins** [comment]
"branch protection" is not one thing - there's around a page of settings. If your question is "Can Renovate just repeatedly try over and over to merge no matter what?" then the answer is no, we won't do that. But if you tell me which particular protections are on your default branch that are causing us to preempt our automerge, then I'll look into the impact of allowing you to ignore them. Here's an example of the list of protections:

![image](https://user-images.githubusercontent.com/6311784/93089937-5a632700-f69c-11ea-9a0c-936935d44036.png)

**Comment by bodinsamuel** [comment]
Hello,

Sorry for the delay I though I had answered.
Our issue is not really about branch protection, it's that we should not be subject to it. We use a different `baseBranches` so renovate would never encounter an issue if you tried to merge.

On our case:
- `master`: protected for everyone without approval and CI (required for certification)
- `chore/renovateBaseBranch` is the renovate base branch, no protection.
- renovate-bot is not an admin on the repo

![image (6)](https://user-images.githubusercontent.com/1637651/99679034-c6d31b80-2a7b-11eb-8685-a6e8023615f4.png)

>  If your question is "Can Renovate just repeatedly try over and over to merge no matter what?" then the answer is no, we won't do that. 

I completely understand that's why I was asking for a flag, so that this choice is consciously made.

--- 
> Automerge: Enabled. instead of Automerge: Require approval

This is still to be solved imo


Best Regards,

**Comment by rarkins** [comment]
Detecting branch protection per-base branch would include detecting when it is *not applicable*. In your case if we detected there was no branch protection for the PR then it would be automerged.

**Comment by rarkins** [comment]
Replaced by #19549
