### ISSUE TITLE
Update PR/MR or comment when rebasing

### ISSUE THREAD

**Issue by nesl247** [renovatebot/renovate#7247]
**What would you like Renovate to be able to do?**

Dependabot updates the PR whenever it's made aware that it needs to rebase. It would be great if renovate would automatically update the GitLab MR when it detects the box is checked, or for any other reason the MR is requested to be rebased. This way it lets us know that renovate is aware it needs to take action.

**Did you already have any implementation ideas?**

See how dependabot does this.

**Comment by rarkins** [comment]
I don't see the benefit of this - it just creates noise. Dependabot may do this because it uses a "chat" interface that's prone to human error or typos but our checkbox approach is not.

**Comment by nesl247** [comment]
It's beneficial for us because we actually have no idea when renovate is going to work on the MR. We check the box and it could be hours before it's rebased. This allows us to know that renovate is aware that it needs to update the MR, and the webhook didn't fail (GitLab doesn't have a way to see failed webhooks as far as I can tell).

**Comment by rarkins** [comment]
Which type of Renovate are you using?

**Comment by nesl247** [comment]
The public @renovate-bot on GitLab.

**Comment by rarkins** [comment]
When the rebase/retry box is checked, it triggers a webhook, and Renovate runs right away and then unticks the cbeckbox. Unfortunately a few days ago GitLab's systems accidentally blocked our user account due to high traffic so you may have seen a service interruption because of that. There's otherwise no practical use for this because Renovate will do the work and untick the checkbox as fast as it can.

Thanks for suggesting it, but I don't think this is the right fit for the way Renovate works.
