### ISSUE TITLE
Refactor node js schedule handling

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#7507]
**What would you like Renovate to be able to do?**

Fetch nodejs schedule on renovate build time and mock travis schedule test.

**Did you already have any implementation ideas?**

* mock the schedule json file for travis tests, so they don't fail in future
* download the schedule on prepare phase (like we generating code)
* add some tests to verify the json to be there and have the desired schema.

**Are there any workarounds or alternative ideas you've tried to avoid needing this feature?**

Regularly update the node js schedule manually as we do currently.

**Is this a feature you'd be interested in implementing yourself?**

sure

ref #2443

**Comment by viceice** [comment]
Some more ideas:

* convert the json to typescript ( so we can use simple import without `async / await` )
* read the file in node versioning to support policies for all managers
* move the policies code from travis to node versioning

**Comment by rarkins** [comment]
One downside would be that if they change the format of this file or even remove/rename it, then all old commits will fail to build without being patched? i.e. it's not immutable

**Comment by viceice** [comment]
🤔 So maybe just add a test which checks for outdated schedule?

**Comment by viceice** [comment]
or just validate the schedule in a schedules github-action job, so we get a mail if it fails, but it won't disturb normal workflow any longer.

maybe we can use a action to automatically open an issue / pr for updating the schedule. 🤔

**Comment by rarkins** [comment]
The ideal solution is a new `filesync` manager in Renovate itself that sends PRs updating the file :)

**Comment by rarkins** [comment]
But in the meantime if there's a simple action that mails us or creates an issue if the file is out of date, it would be good too

**Comment by HonkingGoose** [comment]
Hi @rarkins and @viceice, I think I found a nice (partial) solution to our problems:

I found this package: https://github.com/ralphtheninja/lts-schedule, the big idea is that it bundles the `schedule.json` file so you can import it into your code. The repository is no longer maintained (`schedule.json` on the repo is outdated compared to upstream), test suite is not testing latest LTS of Node, and devDependencies are out of date to name a few things).

If you like the general concept of this package, I can fork and publish it under a **new name**, and clean it up for us to use. The benefit for you would be that you could add my package to your `devDependencies` and use that as source-of-truth for the Node.js schedule.

Having a package that we own could also fix this problem:

> One downside would be that if they change the format of this file or even remove/rename it, then all old commits will fail to build without being patched? i.e. it's not immutable

And also, we could add the ideas from @viceice directly into the package (as we control it ourselves!)

> Some more ideas:
> 
>  * convert the JSON to TypeScript (so we can use simple import without `async / await` )
> 
>  * read the file in node versioning to support policies for all managers
> 
>  * move the policies code from travis to node versioning

The package is published under the **MIT** license, I don't know if you're free to use MIT licensed packages in your Renovate code base?

Let me know what you think of this idea! 😄

**Comment by rarkins** [comment]
I like the idea! Would you mind if we make it in a repo within `renovatebot` org, as long as you have full commit rights? Wondering also if we need to publish it to npm or GCR or just depend on it as a git-based dependency with tags?

Either way, please go ahead with experimenting on it. MIT license is fine and we should make sure to give as much credit as is due to the original author.

**Comment by HonkingGoose** [comment]
**Repo under `renovatebot org`**

> Would you mind if we make it in a repo within `renovatebot` org, as long as you have full commit rights?

That's fine, saves me the work of figuring out how to transfer ownership to your org later on. I don't intend for the repo and package/release to remain under my namespace anyway. I'd rather share it with you, and get help/feedback/contributions from the pros. 😉 

**Commit rights fine by me**

Commit rights would probably be enough to get started with. It would be impractical to create pull requests for all the things I want/need to change.

**Publishing the package/making a release**

> Wondering also if we need to publish it to npm or GCR or just depend on it as a git-based dependency with tags?

I know nothing about publishing on GitHub Packages/npm/Google Container Registry, so I'll let you choose what's easiest. 😉

Might be a good way to try out the `release-please` action, that you have been meaning to test. `release-please` seems easy enough for me to use once the setup/configuration work is done. The only thing I'd need to do is follow Conventional Commits and SemVer, and let `release-please` worry about the publishing steps.

I'd like to learn about publishing software, but it seems so overwhelming to get started, I'd sure appreciate help/advice from you on this.

**Licensing/credit original author**

> MIT license is fine and we should make sure to give as much credit as is due to the original author.

Will do!

---

**Keep full Git history/keep partial history/delete all history**

Do we want to keep the Git history of the original repository, or do we want to start fresh? The old repository is at version `v2.2.0`, but any new work by me should be back to unstable SemVer `0.x.x` releases (for now). I also don't intend to give back the work upstream, because the changes I'm/we're making will make it a completely different package to what the original author started with:

- different test suite (Jest vs Tape)
- different release process (whatever @rarkins decides is best to use)
- different README (obviously)
- different linter setup (Prettier vs Standard, ESLint vs nothing)
- different versioning scheme (SemVer starts back at `0.x.x`)
- we'll probably have Renovate bot specific code (that upstream doesn't want or need)

I've never done a "hard-fork" before. I basically either own most of my work in my own repository with few contributions from others, or have a fork to help the upstream project. So I don't know what would be the best way forward with the history.

I'll let you decide what's best.

**Name for repository**

We also need a good name that's not in use, and doesn't imply that we're publishing an "official Node.js" package.

Some obvious names are in use already:

- https://github.com/node-schedule/node-schedule (Unofficial package, doing a different thing)
- https://github.com/nodejs/lts-schedule (Name of official node project!)
- https://github.com/ralphtheninja/lts-schedule (name of original project)

Maybe we could use `renovate-node-schedule-utils` or something like that? Would that make it clear enough that this is not an official thing?

**Comment by HonkingGoose** [comment]
Hi @rarkins can you maybe give some feedback on the comment I posted above? I'm nearly ready to start, but I'd still need answers to the questions above, or else I might paint myself into a corner pretty soon... 😄

**Comment by rarkins** [comment]
So first question is: to preserve history or not? There's essentially only one author, so you will preserve *credit* regardless. I think it's best not to fork, because then the repo will always show up as a fork no matter how far you have diverged from the original source.

So start with a single squashed commit by the original author, and we make sure that it's always mentioned in the README for appropriate credit.

We can defer the decision on publishing until later.

You should have `main` branch commit rights so that you can update rapidly without PRs or approval.

I would prefer `semantic-release` for consistency although if you would like to experiment with `release-please` then I won't veto it.

Use whatever tools you like, of course best if they align with here.

I quite like `node-schedule`, especially as on github it would be `github.com/renovatebot/node-schedule` and if published would be like `@renovate/node-schedule`

**Comment by HonkingGoose** [comment]
> So first question is: to preserve history or not? There's essentially only one author, so you will preserve _credit_ regardless. I think it's best not to fork, because then the repo will always show up as a fork no matter how far you have diverged from the original source.

Oh yeah, that always looks a bit odd, if the fork is way way different than the original source. I had not considered that yet, but I wasn't going to fork with the GitHub fork button anyways. 😄 

> So start with a single squashed commit by the original author, and we make sure that it's always mentioned in the README for appropriate credit.

Sounds like a good plan to me. Will do!

> We can defer the decision on publishing until later.

Yeah, there's no proper package to publish for a while anyway, so we can worry about publishing when the package is stable enough to start using. 😄 

> You should have `main` branch commit rights so that you can update rapidly without PRs or approval.

Yep.

> I would prefer `semantic-release` for consistency although if you would like to experiment with `release-please` then I won't veto it.

Let's stick with `semantic-release` then! 😉 

> Use whatever tools you like, of course best if they align with here.

Will try to align as close as I can to the way we do things over here.

> I quite like `node-schedule`, especially as on github it would be `github.com/renovatebot/node-schedule` and if published would be like `@renovate/node-schedule`

The `@renovate` scope in the package name would make it clear that it's not an "official Node.js package". 😄

---

Just on more thing, and then I'm out of your hair on this matter:

Do you want to create the initial repository, or do you want me to do the initial repo work and then transfer it over?

**Comment by rarkins** [comment]
Created: https://github.com/renovatebot/node-schedule/invitations

**Comment by HonkingGoose** [comment]
What's the status of this issue, now that we made some related changes?

We have a [`update-data.yml` workflow](https://github.com/renovatebot/renovate/blob/main/.github/workflows/update-data.yml), and we moved code from the `renovatebot/node-schedule` repository into the main `renovatebot/renovate` repository.

**Comment by viceice** [comment]
we need to check the tests for properly mocked date
