### ISSUE TITLE
Clone with Git LFS

### ISSUE THREAD

**Issue by jdanil** [renovatebot/renovate#7894]
**What would you like Renovate to be able to do?**

Use renovate with files stored in git lfs.

Using yarn v2, the release is checked into the repository as well as any plugins for the package manager. Previously, I'd been checking the yarn release and plugins into git lfs, so that updating the files doesn't bloat my git history.

When using renovate, I got an error...

```
/mnt/renovate/gh/<org>/<repo>/.yarn/releases/yarn-2.4.0.cjs:1
version https://git-lfs.github.com/spec/v1

SyntaxError: Unexpected identifier
```

The contents of the file where the error is being thrown looks to be the reference to the git lfs file, so it looks like those lfs files haven't been pulled.

Untracking the releases and plugins from git lfs allowed me to work around the issue.

**Did you already have any implementation ideas?**

I'm wondering if its possible to add a config option for git lfs, that would tell renovate to run something like `git lfs pull` after cloning the repo.

**Comment by viceice** [comment]
https://github.blog/2021-03-09-git-clone-vulnerability-announced/

**Comment by fgblomqvist** [comment]
Would this be solved by simply having git LFS installed before doing the `git pull` or do you need to actually run `git lfs pull`?

**Comment by viceice** [comment]
As far as I know it will work by just install to path.

**Comment by amacneil** [comment]
Running `git lfs install` will configure it for the current user so that every git clone will also fetch LFS.

However, rather than configuring git to clone all LFS files, a better method would be manually run `git lfs pull --include .yarn/`. This way, only required LFS files are downloaded (avoid downloading any other massive files people might be including in their repos).

**Comment by fgblomqvist** [comment]
@amacneil While I do like that approach, there are use-cases where people might LFS files that Renovate might want to update. One of the repos I work on has a file size limit of 1MB which means that even package-lock files get LFSd. I'm not sure what a good compromise would be? Allow people to specify a list of patterns to include and call `git lfs pull --include <patterns>`? Have a pre-defined list, e.g. `.yarn/,**/*/package-lock.json`?

**Comment by amacneil** [comment]
Sure, you could add `package.json`, `package-lock.json`, `yarn.lock` files to the list of things to pull. Is there any scenario where a user would want to pull files outside of that pre-defined list? I can't think of one.

**Comment by fgblomqvist** [comment]
Well, that's the hard thing to say. Doing git lfs on the lock-files + the `.yarn` folder is better than what we got today, but if the goal is more universal compatibility, I think some sort of configuration is necessary. Either a list of patterns of stuff to lfs-pull or perhaps a switch that enables full lfs-pulling. Not sure :thinking:

**Comment by fgblomqvist** [comment]
@viceice @rarkins How do you guys prefer to solve this? Just do `git lfs install` and let take time/space if someone has a lot of large files in their repo, or make the pulling/pushing logic more intricate?

Another way to look at it is this:
Since this issue is related to the official renovate docker images rather than renovate itself, one could argue that perhaps people that need LFS stuff for things to function should just install LFS on the image themselves (e.g. make a custom image based on the official Renovate one).

**Comment by rarkins** [comment]
We are in general looking for ways to clone *less* per run, so I don't think we want to clone `lfs` by default, although it would be good if self-hosted users have the ability to enable that.

I like the idea of a new config option which can be added to `renovate.json` which matches the `git lfs fetch --include` patterns. This means that the Renovate config file you use (e.g. `renovate.json`, `.github/renovate.json`, etc) needs to be non-LFS but then any/all package files after that could not be.

We'd also want to have a way to gracefully catch when LFS is not installed but the user has configured LFS patterns to fetch.

**Comment by viceice** [comment]
Duplicate of #6842
