### ISSUE TITLE
Support GitHub App authentication in addition to Personal Access Token

### ISSUE THREAD

**Issue by statik** [renovatebot/renovate#8196]
**What would you like Renovate to be able to do?**

Self hosted renovate works great with a GitHub personal access token. I would like to extend renovate to also work [GitHub App Authentication](https://docs.github.com/en/free-pro-team@latest/developers/apps/differences-between-github-apps-and-oauth-apps#machine-vs-bot-accounts).

There are two practical problems that this additional authentication option would solve
1. When using a personal access token, I have a single point of failure on 1 of my organization admins, rather than being able to rely on any organization admin to update a token if needed.
2. The renovate-submitted PRs appear as the person who generated the personal access token, which interacts poorly with CODEOWNER rules as that person cannot perform a code review on their own branches. In the case of renovate PRs, taking a senior person out of the pool of available reviewers slows us down quite a bit.

**Did you already have any implementation ideas?**

The good news is the implementation of this is simple, and it seems like this could work very smoothly as an extension of the exiting auth token code without introducing any backward compatibility issues.

I am definitely interested in implementing this and submitting a PR. Here is an example implementation in plain javascript:
https://github.com/kindlyops/examples/blob/dc327eccb4f697e62c9c3e36bf72100fa1b04793/.github/actions/appauth/index.js#L9-L26

I would imagine implementing this in such a way that the config code that retrieves the github PAT would be extended to check for RENOVATE_GITHUB_APP_ID and RENOVATE_GITHUB_APP_KEY, and if those exist, then use them to generate a token to be handed off to the rest of the code. I would be happy to write docs for how to configure a private github app for this use case as well - the setup is very simple and only needs to be done once for an entire github org.

**Comment by rarkins** [comment]
We don't plan to add app support to this CLI core. Complications include:

- `autodiscover` doesn't work with an app token, because it's a different API to the one that lets a user retrieve all repos they are a collaborator on
- if you install into more than one user/org, you would need different tokens for each
- token is only valid for maximum one hour

If you have only one org then you could consider fetching the token as part of your `config.js` and injecting it that way. Make sure:
- your token is defined like `x-access-token:<app token>`
- you specify the `username` and `gitAuthor` as well, matching with the configured bot's (e.g. `renovate[bot]`
- you define the list of repositories in the config

Alternatively, [WhiteSource Renovate On-Premises](https://github.com/whitesource/renovate-on-prem) works in app mode and is free to use with registration.

**Comment by statik** [comment]
Thank you for the detailed and thoughtful consideration! These other options are super helpful and I agree with you.

**Comment by statik** [comment]
For the benefit of future readers, one snag I ran into with fetching the installation token in config.js is generating the initial JWT for doing the github app auth step, so I don't think that approach will work without adding access to something like the `jswonwebtoken` library (or at a higher level, "@octokit/auth-app".
