### ISSUE TITLE
CI: fix lint error visibility

### ISSUE THREAD

**Issue by viceice** [renovatebot/renovate#8408]
Currently we don't see the lint issues on ci. We only see there is an error but not where and what.

**Comment by rarkins** [comment]
This?

![image](https://user-images.githubusercontent.com/6311784/105669127-eef95380-5ede-11eb-9fcc-96d68bc4dd57.png)

**Comment by viceice** [comment]
🤔 yes, maybe we should print the prettier diff 🤔

**Comment by HonkingGoose** [comment]
## Maybe use `--check` instead of `--list-different`?

We are currently using `--list-different`, but we could maybe use `--check` instead?

Are we piping the list of unformatted files to another command? If so we need to keep using `--list-different`.

If we are not passing the list of unformatted files to some other command, we should be safe to use `--check`.

Quote from Prettier CLI docs:
>If you need to pipe the list of unformatted files to another command, you can use `--list-different` flag instead of `--check`.

## Example output for `--list-different`:

```cli
$ npm run prettier

> renovate@0.0.0-semantic-release prettier PATH
> prettier --list-different "**/*.{ts,js,mjs,json,md}"

lib\workers\repository\result.spec.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! renovate@0.0.0-semantic-release prettier: `prettier --list-different "**/*.{ts,js,mjs,json,md}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the renovate@0.0.0-semantic-release prettier script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Example output for `--check`:

```
$ npm run prettier

> renovate@0.0.0-semantic-release prettier PATH
> prettier --check "**/*.{ts,js,mjs,json,md}"

Checking formatting...
[warn] lib\workers\repository\result.spec.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! renovate@0.0.0-semantic-release prettier: `prettier --check "**/*.{ts,js,mjs,json,md}"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the renovate@0.0.0-semantic-release prettier script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

## Prettier docs:

https://prettier.io/docs/en/cli.html#--list-different
https://prettier.io/docs/en/cli.html#--check

**Comment by HonkingGoose** [comment]
By the way there's an issue open at the Prettier project that discusses adding a `diff` to the `--list-different` command.

See https://github.com/prettier/prettier/issues?q=is%3Aissue+is%3Aopen+4612

**Comment by rarkins** [comment]
I don't think it's *too* critical because a developer is unlikely to do anything except check out the branch and run `yarn prettier-fix`.
