### ISSUE TITLE
docs: mention container filesize limits?

### ISSUE THREAD

**Issue by HonkingGoose** [renovatebot/renovate#8472]
**What would you like Renovate to be able to do?**

A user was running into problems with their Docker container growing outside of the defined limits (see https://github.com/renovatebot/renovate/discussions/8460).
The problem was that when the renovate bot was installing the dependencies, the total filesize on disk grew outside of the container limits, and the docker container stops working.
The problem was solved by moving the repo from an SSD disk to an EBS disk which has a larger disk filesize limit.

Should we maybe mention that there is a Docker container filesize limit, and what those limits are for the respective disk types (SSD, EBS)? Or is this such an edge case that it's not worth documenting it?

**Did you already have any implementation ideas?**

We could probably mention the SSD and EBS disk filesize limits in the docs.

I searched for `ssd`, `ebs`, `filesize` and `quota`, and I found nothing, so it doesn't seem we mention this in any way.

**Comment by rarkins** [comment]
This is part of the app rather than open source code, and not part of any SLA either. e.g. if someone has a wasteful "archive" repo than we might be unlikely to dedicate gigs of space just to clone and check it repeatedly.

We might add it to the docs.renovatebot.com site but it wouldn't be sourced from this repo.
