### ISSUE TITLE
Display missing baseBranch name in the dependency dashboard

### ISSUE THREAD

**Issue by divyenduz** [renovatebot/renovate#8657]
**What would you like Renovate to be able to do?**

If a branch name in `baseBranches` does not exist, its name is logged in the renovate logs but it is not mentioned on the "Dependency Dashboard". 

Example of renovate CLI output

```
 WARN: Base branch does not exist - skipping (repository=prisma/renovate-test)
       "baseBranch": "automated/patch-dev"
```

Screenshot of "Dependency Dashboard". The name of the "skipped" branch is not mentioned. 

![image](https://user-images.githubusercontent.com/746482/107669730-5579c200-6c92-11eb-8125-8e1792890c61.png)

**Comment by HonkingGoose** [comment]
I think this is more of a bug report than a feature request.
I think it's a bug because if something is going wrong, Renovate should tell you **what's** wrong.

Can you please fill in the [bug report template](https://github.com/renovatebot/renovate/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and provide us with a reproduction repository?

**Comment by HonkingGoose** [comment]
@rarkins What do you want to do with this?

**Comment by divyenduz** [comment]
Sorry couldn't get to a reproduction and I won't have time to do that. Please feel free to close this or push it forward accordingly. This should be super easy to reproduce though with renovate CLI 🙏
