### ISSUE TITLE
go.mod dependencies versions not detected properly when number for deps with 1000+ tags

### ISSUE THREAD

**Issue by adamko147** [renovatebot/renovate#8852]
**What Renovate type, platform and version are you using?**

Github App

**Describe the bug**

I have go repository working with https://github.com/aws/aws-sdk-go-v2
the aws-sdk-go-v2 has multiple "submodules" in subfolders. In my case, the issue is config module.
while the root module has latest release v1.2.0, the config module is at version v1.1.1
when running renovate on go.mod file with
```
require github.com/aws/aws-sdk-go-v2/config v1.1.1
```
the renovate suggest to upgrade to `aws-sdk-go-v2/config v1.2.0`. However such version does not exists and renovate reports on opened PR following error

##### File name: go-aws-sdk/go.sum

```
Command failed: docker run --rm --name=renovate_go --label=renovate_child -v "/mnt/renovate/gh/adamko147/renovate-tests":"/mnt/renovate/gh/adamko147/renovate-tests" -v "/tmp/renovate-cache":"/tmp/renovate-cache" -v "/tmp/renovate-cache/others/go":"/tmp/renovate-cache/others/go" -e GOPATH -e CGO_ENABLED -w "/mnt/renovate/gh/adamko147/renovate-tests/go-aws-sdk" docker.io/renovate/go:1.16.0 bash -l -c "git config --global url.\"https://**redacted**@github.com/\".insteadOf \"https://github.com/\" && go get -d ./..."
go: github.com/aws/aws-sdk-go-v2/config@v1.2.0: reading github.com/aws/aws-sdk-go-v2/config/config/go.mod at revision config/v1.2.0: unknown revision config/v1.2.0

```

**Have you created a minimal reproduction repository?**

Minimal repo at https://github.com/adamko147/renovate-tests/tree/master/go-aws-sdk
PR by renovate https://github.com/adamko147/renovate-tests/pull/11

- [ ] This is a really small bug, it does not need a reproduction (think small typo)
- [x] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

tag `v1.2.0` on root aws-sdk-go-v2 module https://github.com/aws/aws-sdk-go-v2/releases/tag/v1.2.0
tag `config/v1.1.1` on aws-sdk-go-v2/config module https://github.com/aws/aws-sdk-go-v2/releases/tag/config%2Fv1.1.1

also running locally `go get github.com/aws/aws-sdk-go-v2/config@v1.2.0` reports
```
$ go get github.com/aws/aws-sdk-go-v2/config@v1.2.0
go get: module github.com/aws/aws-sdk-go-v2@v1.2.0 found, but does not contain package github.com/aws/aws-sdk-go-v2/config
``` 

I'm using **go 1.16**

**Comment by adamko147** [comment]
I was able to run renovate with trace enabled and observed that when retrieving tags from aws-sdk-go-v2, the list contains 1000 tags but the `config/v1.1.1` is not there. if I remember correctly, the 1000 is limit on GH how many items can be retrieved... :(

**Comment by adamko147** [comment]
and exploring the releases on the aws-sdk-go-v2, the config/v1.1.1 is somewhere between on 26th page (100 items per page)
curl https://api.github.com/repos/aws/aws-sdk-go-v2/tags?page=26&per_page=100
```json
{
    "name": "config/v1.1.1",
    "zipball_url": "https://api.github.com/repos/aws/aws-sdk-go-v2/zipball/config/v1.1.1",
    "tarball_url": "https://api.github.com/repos/aws/aws-sdk-go-v2/tarball/config/v1.1.1",
    "commit": {
      "sha": "be1c89938486820ef47f075e7db95d4ad7411ccd",
      "url": "https://api.github.com/repos/aws/aws-sdk-go-v2/commits/be1c89938486820ef47f075e7db95d4ad7411ccd"
    },
    "node_id": "MDM6UmVmOTYwMDQzNzU6cmVmcy90YWdzL2NvbmZpZy92MS4xLjE="
  }
```

**Comment by adamko147** [comment]
ok, after looking into the code and analysing I was able to resolve that with running `RENOVATE_PAGINATE_ALL=true` in env.

**Comment by rarkins** [comment]
Is there more than one problem?
1. Release `1.1.1` was not found because it wasn't on the first 26 pages
2. Release `1.2.0` was suggested but it doesn't exist?

BTW I think we really need #8677 so this type of thing wouldn't happen

**Comment by adamko147** [comment]
I think the only one problem that renovate retrieves only 1000 tags for hierarchical go modules. It might be good to have an option in config to set up max number of tags or unlimited number of tags similar to  `RENOVATE_PAGINATE_ALL` env variable does.

**Comment by fgblomqvist** [comment]
To clarify this issue for other people that find it: For extremely large mono-repos that release/tag very often, you could potentially end up in a scenario where the tag you're looking for does not exist within the first 10 pages of tags (each page is 100 tags, this is a max limit set by GitHub). Since Renovate only fetches max 10 pages by default, you'd get problems (since you can't find the tag). 

However, it's possible to bypass that 10-page stop by setting the env var `RENOVATE_PAGINATE_ALL` to `true`. Though, you could argue that you shouldn't have to do that. But, as far as I can see, there is no way to avoid it since the GitHub tag API doesn't allow any sort of filtering (e.g. in GitLab, you can tell it that you're looking for tags starting with `config/`).

So, with that said, I'm not sure if it's possible to do anything reasonable about this situation. Besides, it should be rare to need a version that's over 1000 tags away. Perhaps it's better to let people needing that to just set the env var, update the dep, and then assume that the next time an update needs to be retrieved, it'll be within the first 1000 tags.

**Comment by fgblomqvist** [comment]
The mentioned optimization for GitLab is this:
Utilize the `search` field: https://docs.gitlab.com/13.10/ee/api/tags.html#list-project-repository-tags
However, if one hits the same repo a lot it could still make sense to just get all the tags since those requests will be cached 🤷‍♂️ .

**Comment by codyoss** [comment]
I believe I have run into this issue as well. We recently did a big module split where all packages used to be in one package, but now there are ~100 packages. Our root module, `cloud.google.com/go` is currently at v0.94.0 while our sub-modules are now all at v0.1.0. For these submodules renovate is suggesting to update to a non-existing version which is the current version of the root module.

Example:
Current root module: `cloud.google.com/go` v0.93.3
Current sub module: `cloud.google.com/go/accessapproval` v0.1.0
Suggested update for sub module: v0.1.0 -> v0.93.3

PR: https://github.com/googleapis/google-cloud-go/pull/4660

I had a downstream consumer of our library that also uses renovate to manage dependencies reach out to me on that PR to report they are seeing this in their personal project too.

**Comment by codyoss** [comment]
I did not read this issue through closely enough the first time. I don't think my issue has anything to do with number of tags. (The repo mentioned above has less than 400). This issue seems solely related to a sub-module having a version that is less than the root module. @rarkins Would you consider this the same issue or would you like me to create a new issue for this?

**Comment by rarkins** [comment]
@codyoss sounds like a different issue, so please go ahead with a separate bug report

**Comment by at-wat** [comment]
Currently, `go` datasource without GOPROXY is based on `github/gitlab/bitbucket-releases` datasource.
By https://github.com/renovatebot/renovate/pull/15653, `github-releases` datasource fetches 10000 items.
So, the current occurrence condition of this issue seems to be 10000+ tags instead of 1000+ on GitHub.
(However on github.com/aws/aws-sdk-go-v2, current number of the git tags is 26134 and increasing)
