### ISSUE TITLE
Go mod update from v1 to v2 results in duplicate import

### ISSUE THREAD

**Issue by ViRb3** [renovatebot/renovate#9127]
**What Renovate type, platform and version are you using?**
- Public Renovate Github Bot

**Describe the bug**

I have a Go module repo that, in its `Go.mod` file, references:
```
github.com/gofiber/fiber v1.14.6
```
The latest version of `fiber` is `v2.4.1`. When Renovate sends a PR, it looks like this:

https://github.com/ViRb3/renovate-bug-mrr/pull/4/files
```diff
-require github.com/gofiber/fiber v1.14.6
+require (
+	github.com/gofiber/fiber v1.14.6
+	github.com/gofiber/fiber/v2 v2.6.0
+)
```

Notice that both the old v1 import and the new v2 import are present. The old v1 import should be instead replaced by the v2 import.

**Relevant debug logs**
N/A

**Have you created a minimal reproduction repository?**

Yes. It can be found [here](https://github.com/ViRb3/renovate-bug-mrr/) and the bad PR is [here](https://github.com/ViRb3/renovate-bug-mrr/pull/4).

**Comment by rarkins** [comment]
@56KBs looks related to your recent changes, but maybe fixed by #3348?

**Comment by 56KBs** [comment]
> @56KBs looks related to your recent changes, but maybe fixed by #3348?

Yes this should be fixed by #3348. The fix for #8946 has exposed this issue, which is pretty much unavoidable until #3348 is completed.

Here's a long answer explaining why this is happening:

Renovate will update `require github.com/gofiber/fiber v1.14.6` into `require github.com/gofiber/fiber/v2 v2.6.0` within the `go.mod` file correctly.

Following this change it will run `go get -d ./...` to ensure all the transitive dependencies found within `go.sum` are updated correctly, however this also checks for imports used in the source which do not have matching entries in the `go.mod` file - Causing it to re-add the `github.com/gofiber/fiber v1.14.6` entry alongside the updated version. When #3348 is completed these imports will reference the new version, meaning the updates will occur correctly.

Whilst not perfect, at least following the fix for #8946 you are made aware a major update has occurred even if it still requires manual intervention.

**Comment by rarkins** [comment]
Closed by #9144

**Comment by ViRb3** [comment]
@rarkins Looking at the reproduction repository from the OP, it seems like the renovate PR only updates the `go.mod` file now, none of the imports are actually updated:
```git
go 1.15

require github.com/gofiber/fiber v1.14.6
require github.com/gofiber/fiber/v2 v2.7.1
```
Is this intended? If yes, is there a way to make it update imports as well?

**Comment by rarkins** [comment]
Imports should now be updated too. Rebase/retry any existing Pr if they're old. Create a public reproduction and raise a new issue if not working.
