### ISSUE TITLE
renovate stopped updating aws-cdk version after cdk versiob:1.89.0

### ISSUE THREAD

**Issue by Ranjith072** [renovatebot/renovate#9414]
**What Renovate type, platform and version are you using?**

hosted App
GitHub

**Describe the bug**
renovate stopped updating aws-cdk version after version:1.89.0, we are using cdk python version and it was working pretty good since we started to use renovate.after version 1.89.0 renovate never created any PR for updating aws-cdk. currently cdk has a version 1.96.0.  cdk update involves updating both cdk core which is a nodejs application and individual service applications which are in pythion .
when there is update for cdk usually it will update 3 files package.json, package-lock.josn for cdk-core and setup.py for individual service python implementation. 
not sure what has gone wrong suddenly but its not working. i am not sure if attaching renovate logs will really help in this case.

**Relevant debug logs**

<details><summary>Click me to see logs</summary>

```
Copy/paste any log here, between the starting and ending backticks
```

</details>

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/master/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [ ] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

**Comment by HonkingGoose** [comment]
@Ranjith072 In future please check your spelling, and use paragraphs. It's hard to read and understand your report this way.

I have fixed your text, so that it's readable for the Renovate maintainers.

## Cleaned up bug description:

Renovate stopped updating `aws-cdk` after version `1.89.0`. We are using cdk Python version and it was working pretty good since we started to use Renovate.

After version 1.89.0 Renovate never created any PR to update `aws-cdk`. The latest version of cdk is `1.96.0`.

cdk update involves updating both cdk core which is a Node.js application and individual service applications which are in Python.

When there is a update for cdk usually it updates 3 files:
- `package.json`
- `package-lock.json` for `cdk-core`
- and `setup.py` for individual service Python implementation.

Not sure what has gone wrong suddenly but its not working. I am not sure if attaching Renovate logs will really help in this case.

**Comment by Ranjith072** [comment]
Hi,
any update on this issue? 
i cannot reproduce this issue as there is nothing i can do .

**Comment by rarkins** [comment]
We're not able to fix issues which don't reproduce.

**Comment by Ranjith072** [comment]
how can i reproduce the issue if it has suddenly stopped to create pull requests ?
this is really rude you cant close the issue.

**Comment by rarkins** [comment]
@Ranjith072 this is not the first time that you have posted lazy issues and been disrespectful of maintainer time. In this case you didn't even post a log or use our bug report template. Please consider this to be your last warning, or we will remove your access to this org. This is an open source project which relies on the efforts of all parties.
