### ISSUE TITLE
Renovate keeps trying to refresh our lockfile

### ISSUE THREAD

**Issue by G-Rath** [renovatebot/renovate#9725]
**What Renovate type, platform and version are you using?**

I'm using the hosted app on Github.

**Describe the bug**

Renovate keeps opening "lock file maintenance" PRs, despite having opened ones already on the same day which were successfully merged.

We've had four on our eslint config repo:

  * https://github.com/ackama/eslint-config-ackama/pull/93
  * https://github.com/ackama/eslint-config-ackama/pull/94
  * https://github.com/ackama/eslint-config-ackama/pull/95
  * https://github.com/ackama/eslint-config-ackama/pull/97

The most recent one seems to be in response to me having had [to re-generate the lockfile and restore the peer dependency constraint for `eslint`](https://github.com/ackama/eslint-config-ackama/pull/96), which resulted in `fsevents` being added to the lock - it seems `renovate` is having issues with optional dependencies.

We also had a double up over at `eslint-plugin-jest`:
  * https://github.com/jest-community/eslint-plugin-jest/pull/834
  * https://github.com/jest-community/eslint-plugin-jest/pull/835

Twice it seems actually:
  * https://github.com/jest-community/eslint-plugin-jest/pull/827
  * https://github.com/jest-community/eslint-plugin-jest/pull/828

And finally, we seemed to have had renovate open PRs that it shouldn't have: the config we're using for `eslint-config-ackama` matches what `eslint-plugin-jest` is using, yet `eslint-config-ackama` got PRs for individual packages which `eslint-plugin-jest` did not:
  * https://github.com/ackama/eslint-config-ackama/pull/83
  * https://github.com/ackama/eslint-config-ackama/pull/84
  * https://github.com/ackama/eslint-config-ackama/pull/85
  * https://github.com/ackama/eslint-config-ackama/pull/86
  * https://github.com/ackama/eslint-config-ackama/pull/87
  * https://github.com/ackama/eslint-config-ackama/pull/88
  * https://github.com/ackama/eslint-config-ackama/pull/91
  * https://github.com/ackama/eslint-config-ackama/pull/92

I didn't open a bug for this because it only seemed to happen a couple of times and I figured it was caused by #9635 & co, but am mentioning it here as it might be related.

**Relevant debug logs**

I don't know what logs are actually relevant - looking over them, they all seem to make logical sense on their own; I suspect this is an infrastructure issue.

Happy to provide logs upon request :)

**Have you created a minimal reproduction repository?**

Please read the [minimal reproductions documentation](https://github.com/renovatebot/renovate/blob/main/docs/development/minimal-reproductions.md) to learn how to make a good minimal reproduction repository.

- [ ] I have provided a minimal reproduction repository
- [x] I don't have time for that, but it happens in a public repository I have linked to
- [ ] I don't have time for that, and cannot share my private repository
- [ ] The nature of this bug means it's impossible to reproduce publicly

**Additional context**

I suspect that this is more of an infrastructure problem - specifically I'd say that renovate is being run every hour without any check on if its already done a lockfile refresh today.

**Comment by rarkins** [comment]
> Renovate keeps opening "lock file maintenance" PRs, despite having opened ones already on the same day which were successfully merged.

There is no concept that "if you've already opened one today on the same repo then don't open another one", so this particular point is not relevant.

Renovate will by default attempt lock file maintenance according to the schedule [before 5am on monday](https://github.com/renovatebot/renovate/blob/00cb277bb6d612f63a517644705e060abfde957f/lib/config/definitions.ts#L1409) so if it raises a PR early Monday and you merge it, it will try again to see if the lock file needs updating. If you plan to eagerly automerge such PRs then you could consider lowering the default schedule window to 2-3 hours.

The process for lock file maintenance is also very simple:
- Renovate deletes the existing lock file
- Renovate runs `npm install` or `yarn install`
- If the resulting lock file is different from the original, it creates a PR

Therefore the contents of the lock files are direct output from the respective package managers.

> The most recent one seems to be in response to me having had [to re-generate the lockfile and restore the peer dependency constraint for `eslint`](https://github.com/ackama/eslint-config-ackama/pull/96), which resulted in `fsevents` being added to the lock - it seems `renovate` is having issues with optional dependencies.

This is a result of how optional dependencies work with package managers. Renovate runs on Linux, which doesn't use `fsevents`, so they won't be included in the lock file result.

If yarn or npm had reliable enough "update absolutely everything" commands instead of Renovate deleting the lock file fully then it's possible they themselves would preserve optional dependencies, but we found early on that not everything got upgraded.


> And finally, we seemed to have had renovate open PRs that it shouldn't have: the config we're using for `eslint-config-ackama` matches what `eslint-plugin-jest` is using, yet `eslint-config-ackama` got PRs for individual packages which `eslint-plugin-jest` did not:

Please raise a discussion for this separately.

> I don't know what logs are actually relevant - looking over them, they all seem to make logical sense on their own; I suspect this is an infrastructure issue.

There's no obvious bug evident, and it would require logs to identify if there is one. But so far it appears to be running as expected based on the feature described above.

> Happy to provide logs upon request :)

FYI logs are available via the app portal for 3 days

> I suspect that this is more of an infrastructure problem - specifically I'd say that renovate is being run every hour without any check on if its already done a lockfile refresh today.

There is no such logic/feature to check if a refresh was already done today. People are free to define any schedule for lock file maintenance, including continuous.
